### ISSUE TITLE
[Colima] [hostagent] Waiting for the essential requirement 1 of 5: "ssh"

### ISSUE THREAD

**Issue by deepak-katiyar** [lima-vm/lima#1039]
### Description

Hi,
When i try to start colima by running command **colima start --memory 8 --arch x86_64** it gets stuck and then it give below error:

colima start --memory 8 --arch x86_64                                              ✔  11:49:37
INFO[0000] starting colima
INFO[0000] runtime: docker
INFO[0000] preparing network ...                         context=vm
INFO[0000] creating and starting ...                     context=vm
> [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
> [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
> [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
> [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
> [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
> did not receive an event with the "running" status
FATA[0600] error starting vm: error at 'creating and starting': exit status 1.

I have McBook M1 with apple chip.
Colima version: stable 0.4.4 (bottled)

**Comment by deepak-katiyar** [comment]
serial.log

**Comment by deepak-katiyar** [comment]
[serial.log](https://github.com/lima-vm/lima/files/9452668/serial.log)

**Comment by AkihiroSuda** [comment]
Does Lima's default template work? (`limactl start template://default`)

If Lima's default works but Colima does not, please report your issue to Colima

**Comment by deepak-katiyar** [comment]
It's same issue with lima's default template. Below are the logs:
? Creating an instance "default" Proceed with the current configuration
INFO[0002] Attempting to download the image from "https://cloud-images.ubuntu.com/releases/22.04/release-20220712/ubuntu-22.04-server-cloudimg-arm64.img"  digest="sha256:e1ce033239f0038dca5ef09e582762ba0d0dfdedc1d329bc51bb0e9f5057af9d"
578.44 MiB / 578.44 MiB [-----------------------------------] 100.00% 4.64 MiB/s
INFO[0128] Downloaded the image from "https://cloud-images.ubuntu.com/releases/22.04/release-20220712/ubuntu-22.04-server-cloudimg-arm64.img"
INFO[0128] Attempting to download the nerdctl archive from "https://github.com/containerd/nerdctl/releases/download/v0.22.2/nerdctl-full-0.22.2-linux-arm64.tar.gz"  digest="sha256:73ecaa66e9d2debbe6a1c47a3ca0bbc14d3e6f9e99f2f5a5a28129c2d745f0ba"
185.63 MiB / 185.63 MiB [-----------------------------------] 100.00% 4.75 MiB/s
INFO[0169] Downloaded the nerdctl archive from "https://github.com/containerd/nerdctl/releases/download/v0.22.2/nerdctl-full-0.22.2-linux-arm64.tar.gz"
INFO[0169] [hostagent] Starting QEMU (hint: to watch the boot progress, see "/Users/deepak/.lima/default/serial.log")
INFO[0170] SSH Local Port: 60022
INFO[0170] [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
INFO[0187] [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
INFO[0187] [hostagent] The essential requirement 1 of 5 is satisfied
INFO[0187] [hostagent] Waiting for the essential requirement 2 of 5: "user session is ready for ssh"
INFO[0228] [hostagent] Waiting for the essential requirement 2 of 5: "user session is ready for ssh"
INFO[0268] [hostagent] Waiting for the essential requirement 2 of 5: "user session is ready for ssh"
INFO[0308] [hostagent] Waiting for the essential requirement 2 of 5: "user session is ready for ssh"

**Comment by deepak-katiyar** [comment]
Here are the full log after i get error:
limactl start                                                                     1 ✘  14:43:51
? Creating an instance "default" Proceed with the current configuration
INFO[0002] Attempting to download the image from "https://cloud-images.ubuntu.com/releases/22.04/release-20220712/ubuntu-22.04-server-cloudimg-arm64.img"  digest="sha256:e1ce033239f0038dca5ef09e582762ba0d0dfdedc1d329bc51bb0e9f5057af9d"
578.44 MiB / 578.44 MiB [-----------------------------------] 100.00% 4.64 MiB/s
INFO[0128] Downloaded the image from "https://cloud-images.ubuntu.com/releases/22.04/release-20220712/ubuntu-22.04-server-cloudimg-arm64.img"
INFO[0128] Attempting to download the nerdctl archive from "https://github.com/containerd/nerdctl/releases/download/v0.22.2/nerdctl-full-0.22.2-linux-arm64.tar.gz"  digest="sha256:73ecaa66e9d2debbe6a1c47a3ca0bbc14d3e6f9e99f2f5a5a28129c2d745f0ba"
185.63 MiB / 185.63 MiB [-----------------------------------] 100.00% 4.75 MiB/s
INFO[0169] Downloaded the nerdctl archive from "https://github.com/containerd/nerdctl/releases/download/v0.22.2/nerdctl-full-0.22.2-linux-arm64.tar.gz"
INFO[0169] [hostagent] Starting QEMU (hint: to watch the boot progress, see "/Users/deepak/.lima/default/serial.log")
INFO[0170] SSH Local Port: 60022
INFO[0170] [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
INFO[0187] [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
INFO[0187] [hostagent] The essential requirement 1 of 5 is satisfied
INFO[0187] [hostagent] Waiting for the essential requirement 2 of 5: "user session is ready for ssh"
INFO[0228] [hostagent] Waiting for the essential requirement 2 of 5: "user session is ready for ssh"
INFO[0268] [hostagent] Waiting for the essential requirement 2 of 5: "user session is ready for ssh"
INFO[0308] [hostagent] Waiting for the essential requirement 2 of 5: "user session is ready for ssh"
INFO[0348] [hostagent] Waiting for the essential requirement 2 of 5: "user session is ready for ssh"
INFO[0388] [hostagent] Waiting for the essential requirement 2 of 5: "user session is ready for ssh"
INFO[0428] [hostagent] Waiting for the essential requirement 2 of 5: "user session is ready for ssh"
INFO[0468] [hostagent] Waiting for the essential requirement 2 of 5: "user session is ready for ssh"
INFO[0508] [hostagent] Waiting for the essential requirement 2 of 5: "user session is ready for ssh"
INFO[0549] [hostagent] Waiting for the essential requirement 2 of 5: "user session is ready for ssh"
INFO[0589] [hostagent] Waiting for the essential requirement 2 of 5: "user session is ready for ssh"
INFO[0629] [hostagent] Waiting for the essential requirement 2 of 5: "user session is ready for ssh"
INFO[0669] [hostagent] Waiting for the essential requirement 2 of 5: "user session is ready for ssh"
INFO[0709] [hostagent] Waiting for the essential requirement 2 of 5: "user session is ready for ssh"
INFO[0749] [hostagent] Waiting for the essential requirement 2 of 5: "user session is ready for ssh"
FATA[0769] did not receive an event with the "running" status

**Comment by AkihiroSuda** [comment]
`lima sudo cat /var/log/cloud-init-output.log` may provide more logs

**Comment by deepak-katiyar** [comment]
[cloud-init-output.log](https://github.com/lima-vm/lima/files/9460857/cloud-init-output.log)

**Comment by AkihiroSuda** [comment]
@deepak-katiyar 
Some env var seems to have an unexpected value.
Could you try unsetting that env var?

```
+ exec /mnt/lima-cidata/boot.sh
/mnt/lima-cidata/boot.sh: 25: export: <snipped>: bad variable name
```

https://github.com/lima-vm/lima/blob/1af48114f55b0c80eaf0981f6ffcf7a7550f3f7c/pkg/cidata/cidata.TEMPLATE.d/boot.sh#L25
