### ISSUE TITLE
Stuck on SSH start (`EFI stub: Exiting boot services...`)

### ISSUE THREAD

**Issue by jhay06** [lima-vm/lima#1089]
### Description

Hi , i have mac os with M1 , macbook Air specifically with Monterey

i tried lima from homebrew but every time i start instance, it stuck on 
![image](https://user-images.githubusercontent.com/5191437/194692125-615a0108-ab61-48f0-a3f5-8b7eedb67d61.png)

then checking on the logs below 
BdsDxe: starting Boot0002 "UEFI Misc Device 2" from PciRoot(0x0)/Pci(0x4,0x0)
InstallProtocolInterface: 605DAB50-E046-4300-ABB6-3DD810DD8B23 13B918A68
FSOpen: Open '\EFI\BOOT\fbaa64.efi' Success
FSOpen: Open '\EFI\BOOT\fbaa64.efi' Success
FSOpen: Open 'EFI' Success
FSOpen: Open 'ubuntu' Success
FSOpen: Open 'BOOTAA64.CSV' Success
FSOpen: Open '\EFI\ubuntu\BOOTAA64.CSV' Success
FSOpen: Open '\EFI\ubuntu\shimaa64.efi' Success
[Security] 3rd party image[0] can be loaded after EndOfDxe: PciRoot(0x0)/Pci(0x4,0x0)/HD(15,GPT,5A7DB324-1B31-456A-8B09-F3B96334BC5E,0x800,0x31801)/\EFI\ubuntu\shimaa64.efi.
InstallProtocolInterface: 5B1B31A1-9562-11D2-8E3F-00A0C969723B 13E287240
Loading driver at 0x0013B7B7000 EntryPoint=0x0013B7B8000
Loading driver at 0x0013B7B7000 EntryPoint=0x0013B7B8000 
InstallProtocolInterface: BC62157E-3E33-4FEC-9920-2D3B36D750DF 13E287A18
ProtectUefiImageCommon - 0x3E287240
  - 0x000000013B7B7000 - 0x00000000000D1000
SetUefiImageMemoryAttributes - 0x000000013B7B7000 - 0x0000000000001000 (0x0000000000004008)
SetUefiImageMemoryAttributes - 0x000000013B7B8000 - 0x0000000000065000 (0x0000000000020008)
SetUefiImageMemoryAttributes - 0x000000013B81D000 - 0x000000000006B000 (0x0000000000004008)
[Variable]: Rewritten a preexisting variable(0x00000006) with different attributes(0x00000007) - 605DAB50-E046-4300-ABB6-3DD810DD8B23:MokListRT
[Variable]: Rewritten a preexisting variable(0x00000006) with different attributes(0x00000007) - 605DAB50-E046-4300-ABB6-3DD810DD8B23:MokListXRT
[Variable]: Rewritten a preexisting variable(0x00000006) with different attributes(0x00000007) - 605DAB50-E046-4300-ABB6-3DD810DD8B23:SbatLevelRT
InstallProtocolInterface: 605DAB50-E046-4300-ABB6-3DD810DD8B23 13B830A68
FSOpen: Open '\EFI\ubuntu\grubaa64.efi' Success
MnpAddFreeTxBuf: Add TxBufWrap 13CB71018, TxBuf 13CB71041
MnpAddFreeTxBuf: Add TxBufWrap 13CB71698, TxBuf 13CB716C1
MnpAddFreeTxBuf: Add TxBufWrap 13CB70018, TxBuf 13CB70041
MnpAddFreeTxBuf: Add TxBufWrap 13CB70698, TxBuf 13CB706C1
MnpAddFreeTxBuf: Add TxBufWrap 13CB6F018, TxBuf 13CB6F041
MnpAddFreeTxBuf: Add TxBufWrap 13CB6F698, TxBuf 13CB6F6C1
MnpAddFreeTxBuf: Add TxBufWrap 13CB6E018, TxBuf 13CB6E041
MnpAddFreeTxBuf: Add TxBufWrap 13CB6E698, TxBuf 13CB6E6C1
MnpAddFreeTxBuf: Add TxBufWrap 13CB6D018, TxBuf 13CB6D041
MnpAddFreeTxBuf: Add TxBufWrap 13CB6D698, TxBuf 13CB6D6C1
MnpAddFreeTxBuf: Add TxBufWrap 13CB6C018, TxBuf 13CB6C041
MnpAddFreeTxBuf: Add TxBufWrap 13CB6C698, TxBuf 13CB6C6C1
MnpAddFreeTxBuf: Add TxBufWrap 13CB6B018, TxBuf 13CB6B041
MnpAddFreeTxBuf: Add TxBufWrap 13CB6B698, TxBuf 13CB6B6C1
MnpAddFreeTxBuf: Add TxBufWrap 13CB6A018, TxBuf 13CB6A041
MnpAddFreeTxBuf: Add TxBufWrap 13CB6A698, TxBuf 13CB6A6C1
MnpAddFreeTxBuf: Add TxBufWrap 13CB69018, TxBuf 13CB69041
MnpAddFreeTxBuf: Add TxBufWrap 13CB69698, TxBuf 13CB696C1
MnpAddFreeTxBuf: Add TxBufWrap 13CB68018, TxBuf 13CB68041
MnpAddFreeTxBuf: Add TxBufWrap 13CB68698, TxBuf 13CB686C1
MnpAddFreeTxBuf: Add TxBufWrap 13CB67018, TxBuf 13CB67041
MnpAddFreeTxBuf: Add TxBufWrap 13CB67698, TxBuf 13CB676C1
MnpAddFreeTxBuf: Add TxBufWrap 13CB66018, TxBuf 13CB66041
MnpAddFreeTxBuf: Add TxBufWrap 13CB66698, TxBuf 13CB666C1
MnpAddFreeTxBuf: Add TxBufWrap 13CB65018, TxBuf 13CB65041
MnpAddFreeTxBuf: Add TxBufWrap 13CB65698, TxBuf 13CB656C1
MnpAddFreeTxBuf: Add TxBufWrap 13CB64018, TxBuf 13CB64041
MnpAddFreeTxBuf: Add TxBufWrap 13CB64698, TxBuf 13CB646C1
MnpAddFreeTxBuf: Add TxBufWrap 13CB63018, TxBuf 13CB63041
MnpAddFreeTxBuf: Add TxBufWrap 13CB63698, TxBuf 13CB636C1
MnpAddFreeTxBuf: Add TxBufWrap 13CB62018, TxBuf 13CB62041
MnpAddFreeTxBuf: Add TxBufWrap 13CB62698, TxBuf 13CB626C1
EFI stub: Booting Linux Kernel...
EFI stub: Using DTB from configuration table
EFI stub: Exiting boot services...
SetUefiImageMemoryAttributes - 0x000000013F500000 - 0x0000000000040000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x000000013C190000 - 0x0000000000040000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x000000013C140000 - 0x0000000000040000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x000000013F4C0000 - 0x0000000000030000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x000000013C0F0000 - 0x0000000000040000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x000000013BCB0000 - 0x0000000000040000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x000000013BB00000 - 0x0000000000030000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x000000013BAC0000 - 0x0000000000030000 (0x0000000000000008)

it said thet exiting boot services.

have i missed something ?

**Comment by AkihiroSuda** [comment]
Could you try downloading the image again
```
limactl rm -f default
limactl prune
limactl start
```

**Comment by jhay06** [comment]
> Could you try downloading the image again
> 
> ```
> limactl rm -f default
> limactl prune
> limactl start
> ```

already done this , but same result

**Comment by AkihiroSuda** [comment]
What is your QEMU version?

**Comment by jhay06** [comment]
its okay now , hahaha . i need to reinstall the qemu and relink qemu
