### ISSUE TITLE
Support customize editor for limactl

### ISSUE THREAD

**Issue by Zheaoli** [lima-vm/lima#1091]
### Description

For now, the limactl allows the user to customize the editor by passing `$EDITOR` variable in the environment variable.

But the people should set a pure binary command in `$EDITOR`, if not, the code will choose another default text editor instead. See https://github.com/norouter/norouter/blob/master/cmd/norouter/editorcmd/editorcmd.go#L39-L42

In some circumstances, we need to set a text editor with a config file to get highlights or others features like `nvim -u $HOME/.local/share/lunarvim/lvim/init.lua`

So maybe we can allow people to set default editor in config file like git?

```text
[core]
  autocrlf = input
  editor = "nvim -u $HOME/.local/share/lunarvim/lvim/init.lua"
```

**Comment by jandubois** [comment]
I don't know; it seems easy enough to create a shell wrapper that passes the additional arguments:

```bash
#!/bin/bash
nvim -u "$HOME/.local/share/lunarvim/lvim/init.lua" "$@"
```

And then set `EDITOR` to `$HOME/.local/bin/lua-nvim.sh` or whatever you call the wrapper.

**Comment by Zheaoli** [comment]
But people may don't want to make an extra shell wrapper and add an extra environment variable in bash/zsh config file. Making all limactl-related config options into one file may be a good idea, just like .gitconfig

**Comment by jandubois** [comment]
> But people may don't want to make an extra shell wrapper and add an extra environment variable in bash/zsh config file.

Why not? Would they not run into the same issue in every other place that uses the `EDITOR` variable?

And how is creating the wrapper (that works universally) different from creating another config file (that only works for limactl)?

> Making all limactl-related config options into one file may be a good idea, just like .gitconfig

So what are all the other options that should go in there?

If we have indeed more config options to warrant creating another file, then I would have fewer objections to creating one just to set the editor.

**Comment by Zheaoli** [comment]
> If we have indeed more config options to warrant creating another file, then I would have fewer objections to creating one just to set the editor.

OK, I got your means

**Comment by jandubois** [comment]
I'm going to close this for now. We can re-open it if/when we actually end up having more settings and really needing an extra config file.

I generally push back against features that can easily be achieved with existing tools like the shell: the idea behind the Unix toolkit is to have a bunch of tools that do one thing well, and that can be combined in many different ways. 

Duplicating all the features of other tools into all other tools doesn't really make things easier to use; especially for new users, as there is so much more documentation to read then and stuff to learn. Every little feature doesn't seem like much, but after a while it really adds up.

**Comment by int19h** [comment]
This is rather unfortunate behavior because `limactl` gives no indication whatsoever as to why `$EDITOR` is not respected.

**Comment by jandubois** [comment]
> This is rather unfortunate behavior because `limactl` gives no indication whatsoever as to why `$EDITOR` is not respected.

You could file an issue that `limactl edit` should generate a warning when `EDITOR` is set, but does not point to an executable binary.

You would still only see the warning once you edit `vi` or whatever fallback edit will be chosen. Or we could decide to make it an error when `EDITOR` is set to an unusable value; I don't have strong preferences either way. We can discuss in the issue.

But you need to create a new issue and not comment on an old, closed one.
