### ISSUE TITLE
Promote `{rocky, almalinux, oracle, centos-stream}-9` from experimental

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/lima#1099]
EL8 distros do not work on M1:
- https://github.com/lima-vm/lima/issues/841

So I'm planning to promote `{rocky, almalinux, oracle, centos-stream}-9` from experimental:
e.g., `experimental/rocky-9.yaml` -> `rocky.yaml`

The old `rocky.yaml` will be renamed to `rocky-8.yaml`, or `deprecated/rocky-8.yaml` if we want to deprecate EL8 now.

**Comment by afbjorklund** [comment]
Would it be possible to get some better naming for these, that doesn't change so much ?

The yaml files can be moved around, just thinking something like `rocky:9` or similar

**Comment by AkihiroSuda** [comment]
> The yaml files can be moved around, just thinking something like `rocky:9` or similar

Maybe we can just `ln -s rocky-9.yaml rocky` so that both `template://rocky-9` and `template://rocky` will work.
For windows support in the future, `:` can't be used in a template name.

**Comment by afbjorklund** [comment]
I was more thinking of metadata or a mapping table, but it is a different topic so will continue elsewhere.
