### ISSUE TITLE
`limactl shell` does not consider potential `ssh` shell aliases

### ISSUE THREAD

**Issue by antoineco** [lima-vm/lima#1131]
### Description

_This issue is somewhere between a bug report and a feature request._

`lima shell` always invokes the `ssh` executable instead of whichever `ssh` command the user may have defined in their own shell (e.g. via a shell alias):

https://github.com/lima-vm/lima/blob/8cc56933cef9808e2b62981f231adb8dd56a5246/cmd/limactl/shell.go#L129

My concern with this approach is that the potential of terminal emulators with advanced shell integrations over SSH, such as [kitty](https://sw.kovidgoyal.net/kitty/shell-integration/#shell-integration-over-ssh), cannot be fully utilized with `limactl`.

For example, I alias `ssh` to `kitty +kitten ssh`.
To be able to benefit from SSH integrations provided by my terminal emulator, I currently need to export the SSH config of my VMs using `limactl show-ssh` then use plain SSH commands.

I can think about three ways to approach this:

- Run `ssh` commands through the active shell instead of directly (e.g. `/bin/bash -c ssh`).
    Potential problem: we need to use the actual user's shell instead of a hardcoded default value.

- If `LIMA_SHELL` is set, use that value.
    Potential problem: the user might legitimately want to use different shells inside and outside the VM.

- Introduce an optional `LIMASHELL_SSH` setting, and use that if defined. (_my favourite_)

**Comment by AkihiroSuda** [comment]
> Potential problem: we need to use the actual user's shell instead of a hardcoded default value.

I guess `$SHELL -c ssh` should work

**Comment by antoineco** [comment]
@AkihiroSuda Indeed that would work, good point.

I just submitted an implementation of option 3 in #1132, which works like a charm and is non-intrusive for the user.
Let me know what you think about it.

If you prefer option 1, I'm happy to re-visit my proposal.

**Comment by AkihiroSuda** [comment]
Thanks, I'd prefer 1 (with `$SHELL`), as I'd prefer to avoid adding new env vars if avoidable.

@jandubois @afbjorklund PTAL, WDYT?

**Comment by afbjorklund** [comment]
Initially I thought it was asking for a `limactl ssh` alias, which is something I sometimes type myself due to muscle memory from docker-machine and podman-machine...

**Comment by afbjorklund** [comment]
It is probably OK to use shell instead of exec, should be rather minimal overhead (like `lima`)

**Comment by jandubois** [comment]
Oops, saw the PR first before looking at this issue. Yes, I prefer `$SHELL -c ssh` as well.
