### ISSUE TITLE
`limactl ls $INSTANCE` should exit with non-0 status if $INSTANCE does not exist

### ISSUE THREAD

**Issue by jandubois** [lima-vm/lima#1139]
I wonder why `limactl ls $INSTANCE` just shows a warning and still has an exit code of `0` when the instance doesn't exist.

_Originally posted by @jandubois in https://github.com/lima-vm/lima/issues/957#issuecomment-1183514039_

**Comment by sdemura** [comment]
I work around this with ```limactl list $INSTANCE --json | jq -res 'if . == [] then null else .[] | .status end'```

**Comment by BajuMcBites** [comment]
Hello, I was wondering if I could be assigned this issue?
