### ISSUE TITLE
vz: warn ignored YAML fields

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/lima#1162]
>  Warnings should be printed for ignored YAML propertries: https://github.com/containerd/nerdctl/blob/c1a4159035b77a4a739a503b98139a17ac3440b8/pkg/composer/serviceparser/serviceparser.go#L38
>
> Can be another PR though

_Originally posted by @AkihiroSuda in https://github.com/lima-vm/lima/pull/1147#discussion_r1016138374_

**Comment by balajiv113** [comment]
I will work on this next
