### ISSUE TITLE
`limactl list`: dynamically reduces the column, depending on the terminal width

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/lima#1204]
- https://github.com/lima-vm/lima/pull/1203

We are going to have too many columns:
```console
$ limactl ls
NAME       STATUS     SSH            VM TYPE    ARCH      CPUS    MEMORY    DISK      DIR
default    Stopped    127.0.0.1:0    qemu       x86_64    4       4GiB      100GiB    /Users/suda/.lima/default
vz         Stopped    127.0.0.1:0    vz         x86_64    4       4GiB      100GiB    /Users/suda/.lima/vz
```

When the terminal is small, some columns (especially "DIR") can be just hidden.

**Comment by jandubois** [comment]
One thing we could do to save some small amount of space would be to replace `$HOME` in "DIR" with `~`:

```console
$ limactl ls
NAME       STATUS     SSH            VM TYPE    ARCH      CPUS    MEMORY    DISK      DIR
default    Stopped    127.0.0.1:0    qemu       x86_64    4       4GiB      100GiB    ~/.lima/default
vz         Stopped    127.0.0.1:0    vz         x86_64    4       4GiB      100GiB    ~/.lima/vz
```

**Comment by jandubois** [comment]
Another idea: check if **all** instances use the native arch (which I suspect will be true for most users), and drop the "ARCH" column if there are no emulated instances.

**Comment by AkihiroSuda** [comment]
> `~`

Yes, already opened a PR
- https://github.com/lima-vm/lima/pull/1205

**Comment by AkihiroSuda** [comment]
> Another idea: check if **all** instances use the native arch (which I suspect will be true for most users), and drop the "ARCH" column if there are no emulated instances.

SGTM

**Comment by afbjorklund** [comment]
Some of these could probably be delegated to a "wide" option, ilke in kubectl ?

**Comment by afbjorklund** [comment]
> drop the "ARCH" column if there are no emulated instances

Can do the same for vmtype, perhaps ?

**Comment by afbjorklund** [comment]
If evaulating which columns should be visible, one that _could_ be useful is the containerd version...

Could be adopted to show some other version, like docker version or podman version, as discussed.

This was just when comparing the output of docker-machine and lima ("containerd-machine"):

```console
$ docker-machine ls
NAME      ACTIVE   DRIVER   STATE     URL                     SWARM   DOCKER      ERRORS
default   *        qemu     Running   tcp://127.0.0.1:44729           v20.10.12   
```

```console
$ limactl ls
NAME       STATUS     SSH                VMTYPE    ARCH      CPUS    MEMORY    DISK      DIR
default    Running    127.0.0.1:60022    qemu      x86_64    4       4GiB      100GiB    ~/.lima/default
```

That "active" thing is just comparing the $DOCKER_HOST, it would here be the $LIMA_INSTANCE.
