### ISSUE TITLE
Using file:/// URLs with digest fails due at digest check

### ISSUE THREAD

**Issue by pnasrat** [lima-vm/lima#1217]
### Description

Reproducer (hit this while building ppc64le iso and then trying to use - but this reproducer doesn't need that_

1. wget -P /tmp https://cloud.debian.org/images/cloud/bullseye/20221108-1193/debian-11-generic-amd64-20221108-1193.qcow2
2. Replace location: with "file:///tmp/debian-11-generic-amd64-20221108-1193.qcow2" in examples/debian.yaml
3. ./_output/bin/limactl --debug start ./examples/debian.yaml

The fix is easy in `pkg/downloader/download.go` I made the `validateLocalFileDigest` in `copyLocal` use the canonical local path `srcPath` not `src` which is a file URL.

Happy to submit a PR, but wanted to check about testing as currentlyonly the remote path is currently tested in `download_test.go`

```
DEBU[0000] interpreting argument "./examples/debian.yaml" as a file path for instance "debian"
? Creating an instance "debian" Proceed with the current configuration
DEBU[0001] Make sure "shared" network is stopped
DEBU[0001] Make sure "bridged" network is stopped
DEBU[0001] Make sure "host" network is stopped
INFO[0001] Attempting to download the image from "file:///tmp/debian-11-generic-amd64-20221108-1193.qcow2"  digest="sha512:c24edc82a8e3c9764d39b4b45cd8ad3d48f2927fc3b99431dde4ff69de8098d5f824fec570a520d38f1f95dd1f32c630803a473253f7d10a20de7dd3c09ccca0"
DEBU[0001] verifying digest of local file "file:///tmp/debian-11-generic-amd64-20221108-1193.qcow2" (sha512:c24edc82a8e3c9764d39b4b45cd8ad3d48f2927fc3b99431dde4ff69de8098d5f824fec570a520d38f1f95dd1f32c630803a473253f7d10a20de7dd3c09ccca0)
FATA[0001] failed to download the image, attempted 1 candidates, errors=[failed to download "file:///tmp/debian-11-generic-amd64-20221108-1193.qcow2": open file:///tmp/debian-11-generic-amd64-20221108-1193.qcow2: no such file or directory]
```

**Comment by AkihiroSuda** [comment]
Thanks, PR is appreciated, and it should be tested in `download_test.go`.
The test should create a local dummy file inside `t.TempDir()`.
