### ISSUE TITLE
Information about a guest

### ISSUE THREAD

**Issue by deitch** [lima-vm/lima#1246]
### Description

How do I get detailed information about a guest? I assume I just missed it, but nothing in `limactl info` or `limactl ls` (including `--json`) provides it.

I want to be able to inspect a VM (running or stopped) to find out information similar to `docker inspect`:

* what is the VM image?
* what are the mounts, r/w and r/o?
* resources (cpu, memory)
* containerd
* etc

All of the above might be reasonable handled if I can see the template that was used to launch it and its contents.

In theory, I can run `limactl start --list-templates`, but that doesn't give me the template contents, or which template (if any of those) was used to create a particular VM.

**Comment by AkihiroSuda** [comment]
It's in `~/.lima/<INSTANCE>/lima.yaml`.
Additional configuration are also applied from `~/.lima/_config/{default.yaml, override.yaml}`.

I think we should have `limactl inspect <INSTANCE>` command to inspect them in a single JSON.

**Comment by deitch** [comment]
Thanks for the quick response @AkihiroSuda!

Based on the above, is `~/.lima/<instance>/lima.yaml` the entire template that was used? Or the one before applying the stuff in `~/.lima/_config/{default.yaml, override.yaml}`? I am not quite sure how those files play together.

**Comment by AkihiroSuda** [comment]
The latter one

**Comment by deitch** [comment]
> The latter one

OK, so if I want to know the current state right now, what is the merging logic?

**Comment by AkihiroSuda** [comment]
> > The latter one
> 
> OK, so if I want to know the current state right now, what is the merging logic?

1. Apply `~/.lima/_config/default.yaml` if exists
2. Apply `~/.lima/<INSTANCE>/lima.yaml`
3. Apply `~/.lima/_config/override.yaml` if exists

https://github.com/lima-vm/lima/blob/585d6e25af62d0337cec83ffca226a2c8146a428/examples/default.yaml#L393-L431

**Comment by deitch** [comment]
Cool, thanks.

If I can find a few minutes, do you want a PR for `limactl inspect`?

**Comment by AkihiroSuda** [comment]
> Cool, thanks.
> 
> If I can find a few minutes, do you want a PR for `limactl inspect`?

Yes, thanks
