### ISSUE TITLE
ability to provide template via stdin?

### ISSUE THREAD

**Issue by deitch** [lima-vm/lima#1247]
### Description

In addition to the supported `template://`, `http://`, `https://`, `file://`, it would be helpful to be able to do:

```sh
$ cat template.yaml | limactl start -
# or maybe `limactl start stdin://`? Doesn't matter really.
```

**Comment by AkihiroSuda** [comment]
SGTM, but that will need to be used `--tty=false`.

**Comment by AkihiroSuda** [comment]
This also works
```
cat template.yaml | limactl start --tty=false --name=default /dev/stdin
```

**Comment by deitch** [comment]
Haha, that is so obvious, and I didn't think of it. 😄 

If I can find 10 minutes, do you want a PR on it? And if so, do we want `limactl start -` or `limactl start stdin://` or something else?

**Comment by AkihiroSuda** [comment]
> PR

Yes, thanks. I'd prefer `-`, not `stdin://`

Some design questions:
- This should just fail when `--tty=false` is not specified?  Or printing a warning is enough?
- This should fail when `--name=<NAME>` is not specified?

**Comment by deitch** [comment]
> This should just fail when --tty=false is not specified? Or printing a warning is enough?

Or we could say, "using stdin implies `--tty=false`

> This should fail when --name=<NAME> is not specified?

I would think so.

**Comment by jandubois** [comment]
> Or we could say, "using stdin implies `--tty=false`

I think that makes sense.
