### ISSUE TITLE
Rewrite tests in Go

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/lima#127]
The current test suite is written in bash and perl, but we should rewrite tests in Go

**Comment by balajiv113** [comment]
Am looking into taking this up. To support tests for both vz and qemu drivers and also try to make it more stable (tests passing in first run and not via retries). Also github actions now supports macos-13 runner in beta.

Is there any specific approach we need to take here ?? 
The plan i was thinking is to have it more of a integration tests. Tests run on top of limactl built binary.

**Comment by jandubois** [comment]
FWIW, I agree with rewriting the Perl bits, but I don't think Go is an appropriate language for integration tests (obviously it is the correct choice for unit tests).

I think using a framework like [BATS](https://github.com/bats-core/bats-core) (combined with `jq`) lets you write integration tests that are much easier to maintain and debug.

Having said that, whoever is going to spend the time on implementing this should have the final word on how it is done. 😄

**Comment by jandubois** [comment]
As an example of using BATS, [creds.bats](https://github.com/rancher-sandbox/rancher-desktop/blob/main/bats/tests/registry/creds.bats) is a Rancher Desktop integration test that makes sure you can access a registry.

It uses some helper scripts, so it runs on macOS, Linux, and Windows (in WSL) and can test both moby and containerd configurations (and on Windows can test both Linux and Windows binaries to talk to moby/containerd).

I very much like the brevity and simplicity of the test code, making it easy to write and change the tests once you understand how the helper functions make it work in the different environments. E.g. `ctrctl` is running either `docker` or `nerdctl` depending on which container engine has been configured.
