### ISSUE TITLE
`limactl list --json` now returns an array instead of newline delimited JSON

### ISSUE THREAD

**Issue by jandubois** [lima-vm/lima#1280]
### Description

Originally reported in https://github.com/abiosoft/colima/issues/572

I don't think this was intentional, and should be fixed before the next release, as it breaks backwards compatibility.

And I think `limactl inspect` should be changed accordingly for consistency.

**Comment by AkihiroSuda** [comment]
Yes, this is a bug, regression in https://github.com/lima-vm/lima/commit/75594fa33bd73a2cc80a389993c7573b4bf3ec58

**Comment by AkihiroSuda** [comment]
PR https://github.com/lima-vm/lima/pull/1281
