### ISSUE TITLE
CI: Windows unit tests should be executed on real Windows, not on Wine

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/lima#1290]
https://github.com/lima-vm/lima/blob/2b516bb3f1776eb3fb8e9028cf84d83a4588dc39/.github/workflows/test.yml#L63-L69

**Comment by AkihiroSuda** [comment]
@afbjorklund Is there any reason to avoid using the Windows instances of GHA?

**Comment by afbjorklund** [comment]
I don't know anything about the various GitHub Actions, so ran the same tests as on a developer machine (Linux)

**Comment by ayewo** [comment]
Are you open to PR to update the Windows unit tests to run on an actual Windows machine on GHA?

**Comment by afbjorklund** [comment]
I think the one I did is called "cross-windows", so it should be possible to add more tests for "windows"
