### ISSUE TITLE
FATA did not receive an event with the "running" status (`Driver stopped due to error: "signal: abort trap"` ; `failed to kill QEMU`)

### ISSUE THREAD

**Issue by Micbut** [lima-vm/lima#1297]
### Description

Hi,
I am trying to set up lima for Macbook pro M1 2020.
When I input in the terminal "limactl start" I get the following error.
<img width="1426" alt="Screenshot 2023-01-12 at 18 16 45" src="https://user-images.githubusercontent.com/54619028/212158887-2d7b4cb1-5499-4137-b3c2-a871d0e0cec1.png">
<img width="732" alt="Screenshot 2023-01-12 at 18 16 20" src="https://user-images.githubusercontent.com/54619028/212158896-abe152a1-ab10-4c4a-acab-9ed21dcc9784.png">

I saw that many people had a similar issue but I couldn't find yet the solution

Can someone help me?

**Comment by AkihiroSuda** [comment]
`$HOME/.lima/<INSTANCE>/serial.log` might contain some information

**Comment by AkihiroSuda** [comment]
archive.ubuntu.com and similar servers are mostly down today, that might be the reason

**Comment by Micbut** [comment]
[serial copy.log](https://github.com/lima-vm/lima/files/10417432/serial.copy.log)

**Comment by Micbut** [comment]
the problem is still there, please see attached the serial.log in the previous post

**Comment by AkihiroSuda** [comment]
Seems empty
```console
$ hexdump -C serial.copy.log 
00000000  20 20                                             |  |
00000002
```

**Comment by Micbut** [comment]
Yes, indeed, the serial.log is empty: is that normal?

**Comment by AkihiroSuda** [comment]
No, other logs in the same dir may have much information.
Especially `ha.stderr.log`.

**Comment by Micbut** [comment]
[ha.stdout.log](https://github.com/lima-vm/lima/files/10418303/ha.stdout.log)
[ha.stderr.log](https://github.com/lima-vm/lima/files/10418304/ha.stderr.log)

**Comment by AkihiroSuda** [comment]
> {"level":"debug","msg":"qemu[stderr]: qemu-system-x86_64: Unknown Error","time":"2023-01-14T14:11:00+01:00"}

Please try reinstalling QEMU and Lima.

> Macbook pro M1 2020.

Looks like Rosetta is accidentally used.
Please make sure that you have ARM64 version of `limactl` (`file $(which limactl)`)

**Comment by Micbut** [comment]
Thank you for the great assistance AkihiroSuda. 
I did what you suggested but it still doesn't work.
In the terminal I run "lima -v" and it says "limactl version 0.14.2" : is that what you asked for?

**Comment by Micbut** [comment]
these are the new logs
[ha.stderr.log](https://github.com/lima-vm/lima/files/10418445/ha.stderr.log)
[ha.stdout.log](https://github.com/lima-vm/lima/files/10418446/ha.stdout.log)

**Comment by Micbut** [comment]
I reinstalled qemu and lima using brew

**Comment by AkihiroSuda** [comment]
Please provide the following 
```
uname -rsm
sw_vers
which limactl
file $(which limactl)
sysctl sysctl.proc_translated
```

If any command contains "x86_64" on M1, the installation is broken.

**Comment by Micbut** [comment]
Darwin 22.1.0 arm64
ProductName:		macOS
ProductVersion:		13.0.1
BuildVersion:		22A400
/usr/local/bin/limactl
/usr/local/bin/limactl: Mach-O 64-bit executable x86_64
sysctl.proc_translated: 0

**Comment by AkihiroSuda** [comment]
> /usr/local/bin/limactl: Mach-O 64-bit executable x86_64

This installation is broken for M1.
Maybe you have to reinstall the entire Homebrew, or install Lima and QEMU from the source (or another package manager).

**Comment by Micbut** [comment]
I reinstalled homebrew and reinstalled lima and now works fine! 

I think i had the wrong homebrew version because i recently migrated from an older macbook, that was not M1.

Thank you for the great assistance!
