### ISSUE TITLE
Starting VM with vz crashes due to Video being null

### ISSUE THREAD

**Issue by balajiv113** [lima-vm/lima#1364]
### Description

Starting VM using vz driver without video configuration in yaml crashes in hostagent

**Stacktrace**
```
github.com/lima-vm/lima/pkg/hostagent.(*HostAgent).Run(0xc000168120, {0x100b4fbb0?, 0xc000196008})
        /Users/balaji/Desktop/GitSource/Personal/lima1/pkg/hostagent/hostagent.go:294 +0x3d1
main.hostagentAction(0xc0002fe300, {0xc0002f8230, 0x1, 0x7?})
        /Users/balaji/Desktop/GitSource/Personal/lima1/cmd/limactl/hostagent.go:99 +0x7cd
github.com/spf13/cobra.(*Command).execute(0xc0002fe300, {0xc0002f81c0, 0x7, 0x7})
        /Users/balaji/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000270300)
        /Users/balaji/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/balaji/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
        /Users/balaji/Desktop/GitSource/Personal/lima1/cmd/limactl/main.go:24 +0x1e
```

This is related to the condition here 
https://github.com/lima-vm/lima/blob/master/pkg/hostagent/hostagent.go#L294

This doesn't happen for QEMU because we set video to none only for QEMU
https://github.com/lima-vm/lima/blob/master/pkg/limayaml/defaults.go#L186

**Comment by balajiv113** [comment]
Happening only in Lima HEAD

**Comment by afbjorklund** [comment]
This is from the VNC feature...

Seems like the vz driver is not being tested (?), and it is hard to see the problem on a developer machine (Linux)

**Comment by AkihiroSuda** [comment]
> Seems like the vz driver is not being tested (?), and it is hard to see the problem on a developer machine (Linux)

We need macOS 13 CI 😞
