### ISSUE TITLE
DNS logging should be opt-in

### ISSUE THREAD

**Issue by jandubois** [lima-vm/lima#1367]
Right now the host agent always logs at the DEBUG level, and at that level the hostresolver writes every single lookup to the log files.

This is problematic for some users who are not allowed to share internal server names, so they can't share log files.

It seems like HA logging is intentionally locked at the DEBUG level instead of inheriting the `--debug` setting from the `limactl start` command, so not sure what the right solution would be?

Should we move DNS logging to TRACE level, and switch from DEBUG to TRACE level logging when the instance was started by `limactl --debug start ...`?

Or just move it to TRACE level, and let the developer create a debugging binary where the hostagent logs at TRACE level, if we ever need to debug the hostresolver again? Maybe that will never happen anyways if we switch to gvisor for the user level networking.

Thoughts?

**Comment by AkihiroSuda** [comment]
Let's just move them to the TRACE level, and print them only when `limactl` was launched with `--log-level trace` or maybe `--debug-full`

**Comment by jandubois** [comment]
> print them only when `limactl` was launched with `--log-level trace` or maybe `--debug-full`

We don't have support for `--log-level` yet, and Host Agent was using a hard-coded DEBUG logging level. In the PR I just changed this to TRACE if you explicitly run with `--debug`, so Host Agent is one level more verbose than the `limactl start` process itself.

Does that make sense?

**Comment by jandubois** [comment]
> Can we just have `--log-level debug|trace`, and let `--debug` to be an alias of `--log-level debug`? And/or `--debug-full` for the trace level

We could, but isn't that a separate issue (that is being discussed in #1308)?

And there remains the question if we need to be able to set the logging level of HA independently of the logging level of the app running inside the terminal.
