### ISSUE TITLE
Any plan to support Container Linux, such as CoreOS, Flatcar?

### ISSUE THREAD

**Issue by ronnin** [lima-vm/lima#1406]
### Description

I don't know how to assign the ignition file/content to vm during its first-time boot.

Generally, how to apply cloud-init to vm?

Thank you. 

Great job!

**Comment by afbjorklund** [comment]
Mentioned some of the issues in:
* #1372

Basically it doesn't fully support the standard cloud-init, but uses a custom system called "ignition"

**Comment by AkihiroSuda** [comment]
Let me close this issue as a duplicate, and continue the discussion in #1372
