### ISSUE TITLE
downloader.copyLocal should use Clonefile on macOS

### ISSUE THREAD

**Issue by jandubois** [lima-vm/lima#1411]
### Description

Most of the copies made by `downloader` will remain identical copies of files in the cache (e.g. `basedisk`), and the files are often quite large.

On macOS (with apfs) using `unix.Clonefile` instead of `fs.CopyFile` will be much faster and save disk space, as the copy will point to the same datablocks as the source until they are modified (via "Copy on Write"). Only file metadata is copied.

Clonefile was added to `x/sys/unix` in https://github.com/golang/sys/commit/2334cc1a136f0a5b4384f1a27e3634457be08553

**Comment by afbjorklund** [comment]
There is reflink on Linux, but only on select filesystems.

**Comment by AkihiroSuda** [comment]
This should be implemented in
- https://github.com/containerd/continuity/issues/181

**Comment by AkihiroSuda** [comment]
Implemented in:
- https://github.com/lima-vm/lima/pull/1544
