### ISSUE TITLE
Environment variable does not pass-through by `limactl shell`

### ISSUE THREAD

**Issue by ningziwen** [lima-vm/lima#1419]
### Description

```
$ cat printenv.sh 
echo $MY_VAR

# in host
$ MY_VAR=test ./printenv.sh
test

$ MY_VAR=test limactl shell default ./printenv.sh
# print nothing

# in guest
$ MY_VAR=test ./printenv.sh
test
```

So the environment variables are not passed through by `limactl shell` today. Is this the expected behaviour? If so, I'm interested to learn the reason of it.

I'm aware of Lima yaml has a field to pass env var but seems it can only be populated one time during booting, instead of passing-through in each `limactl shell` command.

[Context of my use case](https://github.com/runfinch/finch/issues/295#issuecomment-1469276619).

**Comment by jandubois** [comment]
`limactl shell` is just establishing an ssh connection. You would have to configure both the client and the server side to allow transfer of an environment variable.

An easier way is to just assign the variable explicitly in your remote command:

> $ MY_VAR=test limactl shell default ./printenv.sh
> \# print nothing

```console
$ MY_VAR=foo; limactl shell default printenv MY_VAR
$ MY_VAR=foo; limactl shell default MY_VAR=$MY_VAR printenv MY_VAR
foo
```
