### ISSUE TITLE
[Rancher Desktop] Lima fails to start with Rosetta on M1 Apple Silicon (`can't create /proc/sys/fs/binfmt_misc/register: nonexistent directory`)

### ISSUE THREAD

**Issue by michaelbauerinc** [lima-vm/lima#1443]
### Description

I've spent a few days trying to configure rancher desktop with lima on a 2020 M1 mac running Ventura 13.0. Initially I believed the issue to be with rancher desktop itself, but after exploring some logs and processes running on the vm after boot, I believe the root of the issue is lima itself.

```
limactl version 0.15.0
```

I sshed into the lima-created VM and the first thing that I noticed with ```ps -a``` was is that its running qemu and not rosetta. Upon further inspection of ```/var/log/lima-init.log``` I see the following error:

```
/mnt/lima-cidata/boot/05-rosetta-volume.sh: line 13: can't create /proc/sys/fs/binfmt_misc/register: nonexistent directory
```
I also found this [user](https://github.com/rancher-sandbox/rancher-desktop/issues/3107) who posted about seemingly the same issue on the rancher issues page.

I was able to have success with the above solution by running:

```
sudo -s
service qemu-binfmt stop
echo ':rosetta:M::\x7fELF\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x3e\x00:\xff\xff\xff\xff\xff\xfe\xfe\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/mnt/lima-rosetta/rosetta:OCF' >/proc/sys/fs/binfmt_misc/register
```

But as mentioned on the linked thread, these changes do not persist upon restarting the VM. If there's anyone with previous insight into this that could assist, it would be very helpful 😄 Alternatively, I'm happy to begin working on a PR to explore a solution to this issue.

**Comment by michaelbauerinc** [comment]
Update: I was able to provide the following override.yaml in ``` ~/Library/Application Support/rancher-desktop/lima/_config/override.yaml``` that seems to resolve the issue:

```
rosetta:
  enabled: true
  binfmt: true

vmType: "vz"
```

This makes me believe that I was incorrect about the root of the issue being lima and instead rancher is just not properly passing the config to lima during start.

**Comment by AkihiroSuda** [comment]
This issue should be closed, and reopened in the Rancher Desktop repo?

**Comment by michaelbauerinc** [comment]
> > rancher is just not properly passing the config to lima during start.
> 
> I think it is; I believe the issue is that the Alpine ISO used by RD already has the qemu-static-* handler installed. But I haven't had a chance yet to look at it.

Hey, thanks for the response! What leads you to believe this? I was looking for where this iso is configured in RD and I can't find it any specific references to the exact/default iso. I do however see the references to the VM isos within lima itself.



> This issue should be closed, and reopened in the Rancher Desktop repo?

Np, I can close this and re-open there shortly. 😄

**Comment by nathanpiper** [comment]
I logged a similar report on Rancher Desktop and I'm pretty sure I tried the yaml override as well but it didn't seem to work. However, I will double check.
