### ISSUE TITLE
Reenable Cirrus CI

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/lima#145]
I temporarily disabled Cirrus CI for repo migration (#144).

Trying to enable Cirrus CI for `lima-vm` org via https://github.com/marketplace/cirrus-ci , but can't choose `lima-vm` ("already setup").

I guess we have to wait for a couple of hours or maybe days until something in their database gets synchronized.

**Comment by AkihiroSuda** [comment]
@jandubois 

I tried to uninstall and reinstall Cirrus CI several times, but still no success.
Could you try reinstalling Cirrus CI? 
( https://github.com/marketplace/cirrus-ci -> "Public Repositories" -> "Account: lima-vm" -> "Install it for free")

**Comment by jandubois** [comment]
> Could you try reinstalling Cirrus CI?

I've installed it; how can we test if it worked? It will only add checks to PRs created after it has been installed, right?

**Comment by AkihiroSuda** [comment]
Thanks, but seems not working...
If it works we should be able to see "➕ Create Build"  and "⚙️ Repository Settings" buttons in https://cirrus-ci.com/github/lima-vm/lima

**Comment by AkihiroSuda** [comment]
Opened PR https://github.com/lima-vm/lima/pull/153 , but Cirrus does not seem triggered 😞

**Comment by jandubois** [comment]
Maybe send email to support+ci@cirruslabs.org and ask for help?

Maybe it doesn't deal with moved repositories correctly? It does notice that it is still the same repo, as it lists all the old tasks on https://cirrus-ci.com/github/lima-vm/lima. Maybe it still has the old user/org information cached in its database somewhere?

**Comment by AkihiroSuda** [comment]
Yes, sent an email. CC'ed you.

**Comment by AkihiroSuda** [comment]
Works now 🎉
