### ISSUE TITLE
[macOS 10.14] "No available formula or cask with the name "lima"."

### ISSUE THREAD

**Issue by MarjaE2** [lima-vm/lima#1464]
### Description

Attempted to install lima using brew install lima.

MacOS 10.14.6.

(The brew page for lima only lists support for the latest versions of MacOS, but this Github page doesn't mention any lack of support for older ones.)

Error: 
  homebrew-core is a shallow clone.
  homebrew-cask is a shallow clone.
To `brew update`, first run:
  git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core fetch --unshallow
  git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask fetch --unshallow
This restriction has been made on GitHub's request because updating shallow
clones is an extremely expensive operation due to the tree layout and traffic of
Homebrew/homebrew-core and Homebrew/homebrew-cask. We don't do this for you
automatically to avoid repeatedly performing an expensive unshallow operation in
CI systems (which should instead be fixed to not use shallow clones). Sorry for
the inconvenience!
==> Searching for similarly named formulae...
This similarly named formula was found:
sdl_image
To install it, run:
  brew install sdl_image
Error: No available formula or cask with the name "lima".
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.

**Comment by AkihiroSuda** [comment]
Homebrew formula is available for macOS >= 11.

https://github.com/Homebrew/homebrew-core/blob/29bc842d5cdffde2917bce61a1d4eb742cf6d987/Formula/lima.rb#L9-L17
