### ISSUE TITLE
Error message on digest mismatch is confusing

### ISSUE THREAD

**Issue by jandubois** [lima-vm/lima#1472]
I specified an incorrect digest in the `lima.yaml` file for the `x86_64` arch. The error message is

```
FATA[0059] failed to download the image, attempted 2 candidates, errors=[failed to download "https://download.opensuse.org/distribution/leap/15.4/appliances/openSUSE-Leap-15.4-Minimal-VM.x86_64-OpenStack-Cloud.qcow2": expected digest "sha256:07a770c25f26a1b298e862c6b24096f80e0e4c37938cffa7f9261854eba15e7a", got "sha256:c686339ace6ab5d3cdf6999d00b3dec2b8adf11456f322d970d6caef74614381" unsupported arch: "aarch64"]
```

Or in edited form:

```
errors=[failed to download "xxx": expected digest "yyy", got "zzz" unsupported arch: "aarch64"]
```

I was very confused why Lima was choosing to download the aarch64 image. There is a hint in the message "attempted 2 candidates" though: these are actually 2 error messages:

```
errors=[
  'failed to download "xxx": expected digest "yyy", got "zzz"',
  'unsupported arch: "aarch64"'
]
```

I wonder if we should quote each error individually (and maybe include the URL for each error, and not just for the checksum one), to make this more obvious?

Or maybe drop the "unsupported arch" errors completely, and instead show "no images defined for arch ..." if the templates doesn't specify any?

**Comment by AkihiroSuda** [comment]
Coincidence:
- https://github.com/lima-vm/lima/pull/1465

**Comment by jandubois** [comment]
> oincidence:
> 
> * [Improve the "failed to download" error message #1465](https://github.com/lima-vm/lima/pull/1465)

Perfect! 😄

**Comment by jandubois** [comment]
Fixed by $1465
