### ISSUE TITLE
`template://experimental/opensuse-tumbleweed` is unsshable due to `OSError: Unknown user or group: "getpwnam(): name not found: 'systemd-network'"`

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/lima#1496]
`template://experimental/opensuse-tumbleweed` (x86\_64) is unsshable due to `OSError: Unknown user or group: "getpwnam(): name not found: 'systemd-network'"` in the video console (not in the serial console).

![image](https://user-images.githubusercontent.com/9248427/232229593-202f6fc7-2bd9-40ff-82fc-e98db73774a2.png)

Probably a regression on the Tumbleweed side?

**Comment by jandubois** [comment]
I've reported the issue to Minimal-VM developers (on SUSE-internal Slack).

**Comment by Verschworer** [comment]
Greetings! in my case I'm using thumbleweed cloudinit qcow2 as a template for my proxmox VMs. After investigating, I found out that there is nothing at all either for the network. A quick solution would be to use 
`virt-customize -a <your_qcow2> --run-command 'zypper in -y wicked'`

**Comment by Verschworer** [comment]
attempt to
`virt-customize -a <your_qcow2> --run-command 'zypper in -y NetworkManager'` don't fix error

**Comment by jandubois** [comment]
> Is there a public issue ticket for this?

I suspect not. I've just asked for an update; I'm afraid this may have gotten lost because it was only discussed on Slack.

**Comment by afbjorklund** [comment]
Seems to have been fixed since
