### ISSUE TITLE
Web site (https://lima-vm.io/): migrate to docsy, mkdocs, gitbook, or something else

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/lima#1499]
The https://lima-vm.io/ website just (poorly) renders markdown on the client side.
We should consider migrating the website to docsy, mkdocs, gitbook, or something else.

## Requirements
- The site SHOULD be multi-versioned (v0.15.x, v0.16.x, master, ...)
- The site MAY support multiple languages, but its maintenance cost will be probably high. Just linking to a machine translation site might be enough.

- The site MUST have the `limactl` CLI reference
- The site MUST have the built-in template list. Just linking to https://github.com/lima-vm/lima/blob/master/examples/README.md might be enough.
- The site SHOULD have the YAML reference

## Resources
Netlify base directory: https://github.com/lima-vm/lima/tree/master/website

**Comment by afbjorklund** [comment]
Would it be a good idea to keep the web site out of the lima code repository ?

The monorepo can quickly get out of hand, like it did for minikube (with hugo)

**Comment by AkihiroSuda** [comment]
> Would it be a good idea to keep the web site out of the lima code repository ?

I'd prefer monorepo

**Comment by balajiv113** [comment]
I will work on this .. Will try to provide some basic website within this week

**Comment by afbjorklund** [comment]
The Podman Desktop team added a "white" version of the logo, for use on black backgrounds (for the "dark mode")

black (light)
![](https://raw.githubusercontent.com/containers/podman-desktop/ab3434da2f0ab70eb9679e16d4e210e66512dee3/extensions/lima/logo-light.png)

white (dark)
![](https://raw.githubusercontent.com/containers/podman-desktop/ab3434da2f0ab70eb9679e16d4e210e66512dee3/extensions/lima/logo-dark.png)

We probably want to add at least the SVG version of it to the repository, for use in:

https://github.com/cncf/artwork/blob/master/examples/sandbox.md#lima-logos

So far there is no movement on the icon situation, but then again it is probably not needed for the website either...

* https://github.com/lima-vm/lima/issues/268
