### ISSUE TITLE
[IPv6] DNS failure during install of either 0.5.0 or 0.6.0 results in sshfs not found or installed.

### ISSUE THREAD

**Issue by satmandu** [lima-vm/lima#150]
Installation on Big Sur amd64 system....
Logs:
[ha.stderr.log](https://github.com/lima-vm/lima/files/6948365/ha.stderr.log)
[ha.stdout.log](https://github.com/lima-vm/lima/files/6948366/ha.stdout.log)
[serial.log](https://github.com/lima-vm/lima/files/6948367/serial.log)

**Comment by jandubois** [comment]
I think qemu user mode networking will only use a single DNS server from the host config, so if that one cannot resolve the name, name lookup will fail because it cannot fall back to a secondary server.

Unfortunately I'm not sure how qemu will pick the DNS server, but I would first check (on the Mac) with `scutil --dns` to see if the first entry is a fully functioning nameserver.

I tried playing around with passing an invalid DNS server to qemu to repro your breakage, but it always worked correctly, so I'm not really sure if I'm looking at the right spot or not.

**Comment by satmandu** [comment]
Looks like it eventually started working!

**Comment by satmandu** [comment]
Upon further analysis, it looks like I have complete failure to connect out from the VM's network.
```
 % limactl shell default
satadru@lima-default:/usr/local/bin$ ifconfig -a
enp0s1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.5.15  netmask 255.255.255.0  broadcast 192.168.5.255
        inet6 fe80::5054:ff:fe12:3456  prefixlen 64  scopeid 0x20<link>
        inet6 fec0::5054:ff:fe12:3456  prefixlen 64  scopeid 0x40<site>
        ether 52:54:00:12:34:56  txqueuelen 1000  (Ethernet)
        RX packets 755  bytes 66321 (66.3 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1404  bytes 129204 (129.2 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 710  bytes 51619 (51.6 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 710  bytes 51619 (51.6 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
satadru@lima-default:/usr/local/bin$ ip route show
default via 192.168.5.2 dev enp0s1 proto dhcp src 192.168.5.15 metric 100 
192.168.5.0/24 dev enp0s1 proto kernel scope link src 192.168.5.15 
192.168.5.2 dev enp0s1 proto dhcp scope link src 192.168.5.15 metric 100
satadru@lima-default:/usr/local/bin$ ping 192.168.5.2
PING 192.168.5.2 (192.168.5.2) 56(84) bytes of data.
64 bytes from 192.168.5.2: icmp_seq=1 ttl=255 time=0.982 ms
64 bytes from 192.168.5.2: icmp_seq=2 ttl=255 time=0.984 ms
^C
satadru@lima-default:/usr/local/bin$ ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
```

**Comment by satmandu** [comment]
This is not a networking issue insofar as it is actually a DNS issue it seems.

I can put a working dns server into `/etc/resolv.conf` and networking starts working.

**Comment by satmandu** [comment]
The permanent solution for me was to modify `/etc/systemd/resolved.conf` and add fallback solutions thus:
```
[Resolve]
# Some examples of DNS servers which may be used for DNS= and FallbackDNS=:
# Cloudflare: 1.1.1.1 1.0.0.1 2606:4700:4700::1111 2606:4700:4700::1001
# Google:     8.8.8.8 8.8.4.4 2001:4860:4860::8888 2001:4860:4860::8844
# Quad9:      9.9.9.9 2620:fe::fe
DNS=1.1.1.1 1.0.0.1 2606:4700:4700::1111 2606:4700:4700::1001
FallbackDNS=8.8.8.8 8.8.4.4 2001:4860:4860::8888 2001:4860:4860::8844
```

**Comment by jandubois** [comment]
Have you tried setting the nameserver in `/etc/resolv.conf` on the Mac and see if qemu forwards to that?

I'm just guessing based on this 10 year old comment in a [bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=625689#28):

> the implementation is rather simplistic - for DNS it merely forwards (like a NAT box) packets from guest to a nameserver from host /resolv.conf - only one nameserver, because you can't NAT to TWO destinations at once.

**Comment by satmandu** [comment]
`/etc/resolv.conf` in macos states:

```
#
# macOS Notice
#
# This file is not consulted for DNS hostname resolution, address
# resolution, or the DNS query routing mechanism used by most
# processes on this system.
#
# To view the DNS configuration used by this system, use:
#   scutil --dns
#
# SEE ALSO
#   dns-sd(1), scutil(8)
#
# This file is automatically generated.
#
search lan
nameserver <local network dns server>
```

The local network dns server does work from macos.

**Comment by jandubois** [comment]
So it looks like slirp no longer reads `/etc/resolv.conf` on macOS, but calls into [libresolv](https://github.com/qemu/libslirp/commit/5ac17660a76e321c37e6dca2e3c04d9d7d2b7ff4).

Now there should be a way to set an env variable `SLIRP_DEBUG=misc` to get additional tracing information, that should show which nameserver IPs it finds, but I haven't been able to figure out where the `g_debug` output from inside qemu ends up.

@AkihiroSuda Any pointers?

**Comment by jonatasbaldin** [comment]
I had the same issue but for a different problem.

I have an alternative DNS server (PiHole) running on my local network, on the IP 192.168.178.56, wihch is specified on my local `/etc/resolv.conf`. When the QEMU boots up, it relies on my local DNS configuration, but the VM cannot reach the aforementioned IP address, so the first `apt-get update` command fails.

I used the [solution provided](https://github.com/lima-vm/lima/issues/150#issuecomment-894599954) by @satmandu, but needed to add a `apt-get update` line before installing the `sshfs`.

**Comment by satmandu** [comment]
Updated my advice accordingly...

**Comment by amitkgupta** [comment]
> I accomplished this by modifying the `.lima/default/lima.yaml` file thus:
> 
> ```
> provision:
>   # `system` is executed with the root privilege
>   - mode: system
>     script: |
>       #!/bin/bash
>       set -eux -o pipefail
>       sed -i "/DNS=/d" /etc/systemd/resolved.conf
>       sed -i "/FallbackDNS=/d" /etc/systemd/resolved.conf
>       sed -i "/Quad9:/a DNS=1.1.1.1 1.0.0.1 2606:4700:4700::1111 2606:4700:4700::1001" /etc/systemd/resolved.conf
>       sed -i "/DNS=/a FallbackDNS=8.8.8.8 8.8.4.4 2001:4860:4860::8888 2001:4860:4860::8844" /etc/systemd/resolved.conf
>       systemctl restart systemd-resolved.service
>       export DEBIAN_FRONTEND=noninteractive
>       apt-get update && apt-get install -y vim sshfs
> ```

This more or less worked for me. I did `limactl start default`, chose to edit the config rather than go with the defaults, and made the changes suggested above. At first, it failed. Then I did `limactl stop default` and `limactl start default` and then it worked.

My guess is LIMA is trying to install `sshfs` a standard way, and the custom provisioning is also trying to do the same. This succeeds but in parallel the standard way fails, hence the initial failure. But then when you stop and start again, I guess the standard way just no-ops since now `sshfs` is already installed. That's just my guess -- but yes this seems to have worked for me.

**Comment by jandubois** [comment]
Just another datapoint:

https://github.com/rancher-sandbox/rancher-desktop/issues/572#issuecomment-911805379 claims that removing an IPv6 nameserver from `/etc/resolv.conf` on the macOS host fixed the issue.

**Comment by aleskovets** [comment]
Manual setup for DNS/FallbackDNS helped me with resolving issues with DNS server that F5 VPN sets on connection. basically I had to hard-code that DNS server as a primary DNS and use Google as fallback.

**Comment by jandubois** [comment]
I wonder if Lima shouldn't just auto-add the configured nameservers from the `en0` interface on the host to the instance resolver:

```console
$ system_profiler SPNetworkDataType -json | jq '.SPNetworkDataType[] | select(.interface == "en0").DNS.ServerAddresses'
[
  "192.168.123.53",
  "192.168.123.17"
]
```

I suspect this would fix the issue for most affected users, if not all.

Not sure what to do on Linux (if anything).

**Comment by jandubois** [comment]
I've created #199 as an attempt to address this issue.

I would appreciate if everyone who encountered this problem and is comfortable building Lima from source code test it out and report if this fixes the problem for you or not!

**Comment by aleskovets** [comment]
@jandubois, it does not fix my issue, so I have to fallback to the workaround. I assume that it is again due to VPN case - it is launched after lima was started - meaning "VPN DNS" is only known after the connection. It also starts tunnel interface different to `en0`.

**Comment by jandubois** [comment]
@aleskovets I don't think we'll be able to figure out DNS setting from VPN automatically, especially not when the VPN connection is established when the Lima instance is already running.

I've created #218 to have a mechanism to explicitly provide DNS addresses in `lima.yaml`. That way there should be no need to "manually" redo the installation of prerequisites in a provisioning script.

If you are comfortable building from source, could you test it and see if that works for you?

**Comment by aleskovets** [comment]
@jandubois , #218 resolved this issue for me. Thank you!

**Comment by jandubois** [comment]
> @jandubois , #218 resolved this issue for me. Thank you!

@aleskovets Awesome, thanks for letting me know!
