### ISSUE TITLE
Add `qemu-<VERSION>-<OS>-<ARCH>.tar.gz` to https://github.com/lima-vm/lima/releases

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/lima#1504]
Adding `qemu-<VERSION>-<OS>-<ARCH>.tar.gz` to https://github.com/lima-vm/lima/releases will be helpful for users who don't use Homebrew/Nix/MacPorts.

The existing `lima-<VERSION>-<OS>-<ARCH>.tar.gz` should remain minimalistic.

**Comment by jandubois** [comment]
Wouldn't it make more sense to have a separate repo with these releases (just like socket-vmnet)?

**Comment by afbjorklund** [comment]
Also note that QEMU uses the GPLv2 license, which could be another reason to keep it separate.

**Comment by AkihiroSuda** [comment]
Closing as unplanned, as Lima no longer uses QEMU by default
