### ISSUE TITLE
virtio-vhost and virtio-vsock from crosvm?

### ISSUE THREAD

**Issue by satmandu** [lima-vm/lima#152]
Looks like Google's crosvm supported being built on Darwin until earlier this year as per https://android.googlesource.com/platform/external/crosvm/+/98d3e59e3adb0ebedf1b7f6de8051d5f8fc9702a

Also note vhost vsock in go here: https://android.googlesource.com/platform/external/crosvm/+/98d3e59e3adb0ebedf1b7f6de8051d5f8fc9702a/vhost/src/vsock.rs

**Comment by AkihiroSuda** [comment]
I don't think we are going to use crosvm, because it seems dropped support for Darwin as you said, and yet it seems to lack support for a bunch of stuff such as QCOW2 and UEFI.
