### ISSUE TITLE
Support audio device for vz driver

### ISSUE THREAD

**Issue by balajiv113** [lima-vm/lima#1531]
### Description

This is a follow up of #1526 for vz driver

**Comment by afbjorklund** [comment]
Maybe we should add input/output as a configuration boolean ? Or always enable both, but could be surprising.

**Comment by afbjorklund** [comment]
BTW, virtio-sound is being worked on for qemu: https://wiki.qemu.org/Internships/ProjectIdeas/VirtioSound
