### ISSUE TITLE
vz: fail before running hostagent when macOS is too old

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/lima#1533]
https://github.com/lima-vm/lima/blob/23a8a7f014a30c15c79e0724bebfade8b65c79c2/pkg/vz/vz_driver_darwin.go#LL110-L122

Currently the `vz driver requires macOS 13 or higher to run` error is only visible in `~/.lima/vz/ha.stderr.log`.
This should be printed before launching the hostagent

**Comment by afbjorklund** [comment]
It would be a nice feature also for qemu (1.x) will open a separate issue for that

**Comment by AkihiroSuda** [comment]
> It would be a nice feature also for qemu (1.x) will open a separate issue for that - RHEL 7 has QEMU 1.5.3

Does Lima fail with that version?

**Comment by afbjorklund** [comment]
> Does Lima fail with that version?

Yes, the syntax changed. It works with QEMU 4, so I think that is a reasonable requirement for the legacy systems...

* https://github.com/lima-vm/lima/issues/320

The user can install a newer version through something like "backports" (or linuxbrew), it does work with the OS
