### ISSUE TITLE
USB passthrough

### ISSUE THREAD

**Issue by beriberikix** [lima-vm/lima#156]
https://qemu-project.gitlab.io/qemu/system/devices/usb.html

Is it possible to passthrough USB devices? This is a common requirement for developing really hardware and something QEMU supports well. It's also some WSL currently lacks ☺️

**Comment by AkihiroSuda** [comment]
QEMU doesn't seem to support USB passthrough for macOS hosts

**Comment by beriberikix** [comment]
Funny enough, I couldn't a good USB device for passthrough. But I was able to verify with a USB Serial device on an Intel macOS. For example, I passed in `-chardev serial,path=/dev/cu.SLAB_USBtoUART,id=esp32 -device usb-serial,chardev=esp32` and was able to communicate with the device from the guest.

Is there a way to pass QEMU flags in the config?

**Comment by jandubois** [comment]
> Is there a way to pass QEMU flags in the config?

It is only meant for debugging, but you can stuff additional arguments into `QEMU_SYSTEM_X86_64`, e.g.

```
QEMU_SYSTEM_X86_64="qemu-system-x86_64 -display cocoa" limactl start
```
