### ISSUE TITLE
Add `user-v2` to `networks.yaml` automatically (when upgraded from Lima < 0.16)

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/lima#1567]
The `net-user-v2` template fails when `user-v2` is not defined in `networks.yaml`:
```console
$ limactl start template://experimental/net-user-v2 
? Creating an instance "net-user-v2" Proceed with the current configuration
FATA[0000] the YAML is invalid, saved the buffer as "lima.REJECTED.yaml": field `networks[0].lima` references network "user-v2" which is not defined in networks.yaml 
```

Lima should automatically add `user-v2` to `networks.yaml`

**Comment by balajiv113** [comment]
@AkihiroSuda 
I will look into this.

**Comment by balajiv113** [comment]
@AkihiroSuda Do you want to add user-v2 to networks.yaml or Assume the defaults directly while running like we do in limayaml ??

Reason why am asking is, if we want to write to yaml we will loose the comments that are present in it during marshal.

**Comment by jandubois** [comment]
I think the defaults should be built-in, so it will work with an existing `networks.yaml`, but for new installations the initial `networks.yaml` should include them as well, so users will know that they can change the settings there.

**Comment by balajiv113** [comment]
Perfect, for new installation it is already been added so no issues there. 
For existing installation will keep it built-in then. Will raise a PR shortly
