### ISSUE TITLE
No ip address in lima VM also the internet sharing feature on mac arm stops working

### ISSUE THREAD

**Issue by AravindGopala** [lima-vm/lima#1594]
### Description

**_Version Information:_**
I am currently running lima version 0.16.0 and colima version 0.5.5

Macos Ventura 13.4

**_Feature Impacted_**:
I usually use Macos internet sharing feature to share my wifi with an ethernet port(external dock). when I start the colima lima VM I see the below lines in the startup logs and I do not see any ip assigned to the VM.

**_Issue_**:
The issue seems to be bootpd will no longer launch to provide dhcp leases **_after a reboot_** once after running colima start, I have to brew uninstall lima and colima and reboot for inorder to get it to working again.

I can provide any specific logs if needed. Hoping to find any immediate work arounds if possible in the meantime.

some errors observed:
```
{cmd}:» colima start                   
> [hostagent] [VZ] - vm state change: running
> [hostagent] Waiting for the essential requirement 1 of 3: "ssh"
> [hostagent] Waiting for the essential requirement 1 of 3: "ssh"
> [hostagent] 2023/05/30 17:43:27 tcpproxy: for incoming conn 127.0.0.1:49532, error dialing "192.168.5.1:22": connect tcp 192.168.5.1:22: connection was refused
> [hostagent] Waiting for the essential requirement 1 of 3: "ssh"
> [hostagent] 2023/05/30 17:43:37 tcpproxy: for incoming conn 127.0.0.1:49534, error dialing "192.168.5.1:22": connect tcp 192.168.5.1:22: connection was refused
```

```
{cmd}:» colima list                
PROFILE    STATUS     ARCH       CPUS    MEMORY    DISK     RUNTIME       ADDRESS
default    Running    aarch64    4       8GiB      36GiB    containerd   
```

**Comment by AkihiroSuda** [comment]
> I am currently running lima version 0.16.0 and colima version 0.5.5

Please include a full command in your report. e.g., `colima start --network-address`.
We'd also appreciate if you can verify whether the issue is reproducible with a bare lima.

**Comment by AkihiroSuda** [comment]
Likely to be a duplicate of:
- https://github.com/lima-vm/socket_vmnet/issues/18

But not 100% sure.

**Comment by AravindGopala** [comment]
@AkihiroSuda I am new to lima, I always use colima to start my VM, yes I can conform both `colima start` and `colima start --netowrk-address` has the same result, I do not see the ip assigned.

**Comment by AravindGopala** [comment]
I am closing this, it looks like this post helped me resolve my issue:
https://github.com/canonical/multipass/issues/2387#issuecomment-1573043587
