### ISSUE TITLE
CI: vz: enable `systemd-strict` and `port-fowards` tests

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/lima#1611]
The tests are currently disabled:
https://github.com/lima-vm/lima/blob/c0334c5adf5dbc065fae8e9f6e55775a00d27fa6/hack/test-example.sh#L68-L70

**Comment by balajiv113** [comment]
To elaborate on the issues,
1. Sytemd-strict - this is related to issue with rosetta script failure in amd64
2. port-forwards - default ip address not equal to 192.168.5.15 for vz. @jandubois already mentioned about this to keep in sync.

Will fix both of these.
