### ISSUE TITLE
Too many identity files specified ssh error

### ISSUE THREAD

**Issue by datajerk** [lima-vm/lima#1616]
### Description

I have many ssh identity files (for many different systems); lima/colima enumerates all of them and puts in `ssh.config` causing this `Waiting for the essential requirement 1 of 5: "ssh"` to never resolve.  The err log has: `{"level":"debug","msg":"stdout=\"\", stderr=\"command-line line 0: Too many identity files specified (max 100)`

I've tried to edit ssh.config, but it just gets overridden with `lima start`.

Is is really necessary to enumerate every private key I have?

Thanks.

**Comment by AkihiroSuda** [comment]
Workaround: `loadDotSSHPubKeys: false`
https://github.com/lima-vm/lima/blob/9d29da396c164fea261bc547b4537d470aa3a824/examples/default.yaml#L122

**Comment by datajerk** [comment]
Yeah just found it myself.  Thanks.  Works.  This should be the default IMHO.

**Comment by AkihiroSuda** [comment]
> This should be the default IMHO.

Yes, we can consider that.
- https://github.com/lima-vm/lima/issues/1617
