### ISSUE TITLE
Add armv7 (qemu-system-arm) emulation support

### ISSUE THREAD

**Issue by c-herz** [lima-vm/lima#1622]
### Description

I often need to debug and configure programs that run on embedded Linux systems based on the armv7 architecture (NXP i.MX, Broadcom, etc.). I use a MacBook Pro 14" 2021 model as my main machine, and I find Lima very useful for development that specifically requires a Linux system. However, I would love to be able to set "arch=armv7" or something along those lines and emulate an entirely 32-bit ARM system with a 32-bit kernel, since this is the native architecture that most of these embedded processors are built on. To do this all while benefiting from the convenient filesystem integration that Lima provides, without having to deal with the headache of spinning up and manually configuring a qemu VM, would greatly simplify my workflow and make it much easier for me to analyze and run embedded ARM binaries.

**Comment by afbjorklund** [comment]
Did this a lot for the older Raspberry Pi models, but I think that most are giving up on building arm32 images.

First the `armv6` binaries disappeared, and now the `armv7` seem to be slowly fading - for `armv8` and arm64...

Maybe support it as an architecture for limactl ?

But without the containers and without the images.

**Comment by XVilka** [comment]
@afbjorklund there are always Linux distributions tailored for older hardware, these could be used. Debian Ports also tend to carry architecture support for a looong time, e.g. HPPA and Alpha are still supported unofficially:
- https://www.alpinelinux.org/downloads/
- https://www.debian.org/ports/
- https://www.ports.debian.org/

**Comment by afbjorklund** [comment]
Here are the test results, of the PR.

$ limactl --debug start ./examples/experimental/armv7l.yaml
$ limactl shell armv7l

anders@lima-armv7l:~$ arch
armv7l

Running the "Raspberry Pi 2" CPU:

```console
anders@lima-armv7l:~$ grep PRETTY /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.2 LTS"
anders@lima-armv7l:~$ uname -a
Linux lima-armv7l 5.15.0-75-generic-lpae #82-Ubuntu SMP Wed Jun 7 00:16:35 UTC 2023 armv7l armv7l armv7l GNU/Linux
anders@lima-armv7l:~$ lscpu 
Architecture:           armv7l
  Byte Order:           Little Endian
CPU(s):                 4
  On-line CPU(s) list:  0-3
Vendor ID:              ARM
  Model name:           Cortex-A7
    Model:              5
    Thread(s) per core: 1
    Core(s) per socket: 4
    Socket(s):          1
    Stepping:           r0p5
    BogoMIPS:           125.00
    Flags:              half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
...
```

Need to install nerdctl et al manually, from the github Releases.

```console
$ sudo apt update
$ sudo apt install containerd rootlesskit

8.3M    nerdctl-1.4.0-linux-arm-v7.tar.gz
$ containerd-rootless-setuptool.sh install

61M     buildkit-v0.11.6.linux-arm-v7.tar.gz
$ containerd-rootless-setuptool.sh install-buildkit

anders@lima-armv7l:~$ nerdctl version
Client:
 Version:	v1.4.0
 OS/Arch:	linux/arm
 Git commit:	7e8114a82da342cdbec9a518c5c6a1cce58105e9
 buildctl:
  Version:	v0.11.6
  GitCommit:	2951a28cd7085eb18979b1f710678623d94ed578

Server:
 containerd:
  Version:	1.6.12-0ubuntu1~22.04.1
  GitCommit:	
 runc:
  Version:	1.1.4-0ubuntu1~22.04.3
```

Eventually there might some .deb, from the nerdctl-full distribution.

**Comment by afbjorklund** [comment]
### docker

`$ sudo apt install docker.io`

```
The following additional packages will be installed:
  bridge-utils containerd dns-root-data dnsmasq-base pigz runc ubuntu-fan
Suggested packages:
  ifupdown aufs-tools cgroupfs-mount | cgroup-lite debootstrap docker-doc rinse zfs-fuse | zfsutils
The following NEW packages will be installed:
  bridge-utils containerd dns-root-data dnsmasq-base docker.io pigz runc ubuntu-fan
0 upgraded, 8 newly installed, 0 to remove and 0 not upgraded.
Need to get 51.4 MB/55.3 MB of archives.
After this operation, 225 MB of additional disk space will be used.
```

```
Client:
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.1
 Git commit:        20.10.21-0ubuntu1~22.04.3
 Built:             Thu Apr 27 05:58:10 2023
 OS/Arch:           linux/arm
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.1
  Git commit:       20.10.21-0ubuntu1~22.04.3
  Built:            Thu Apr 27 05:37:25 2023
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.6.12-0ubuntu1~22.04.1
  GitCommit:        
 runc:
  Version:          1.1.4-0ubuntu1~22.04.3
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        
```

```
anders@lima-armv7l:~$ sudo docker run busybox true
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
afac622c5a1d: Pull complete 
Digest: sha256:6e494387c901caf429c1bf77bd92fb82b33a68c0e19f6d1aa6a3ac8d27a7049d
Status: Downloaded newer image for busybox:latest
```

### podman

`$ sudo apt install podman`

```
The following additional packages will be installed:
  buildah catatonit conmon containernetworking-plugins dconf-gsettings-backend dconf-service fuse-overlayfs glib-networking glib-networking-common
  glib-networking-services golang-github-containernetworking-plugin-dnsname golang-github-containers-common golang-github-containers-image
  gsettings-desktop-schemas libavahi-client3 libavahi-common-data libavahi-common3 libavahi-glib1 libdconf1 libostree-1-1 libproxy1v5 libslirp0 libsoup2.4-1
  libsoup2.4-common session-migration slirp4netns uidmap
Suggested packages:
  containers-storage docker-compose
The following NEW packages will be installed:
  buildah catatonit conmon containernetworking-plugins dconf-gsettings-backend dconf-service fuse-overlayfs glib-networking glib-networking-common
  glib-networking-services golang-github-containernetworking-plugin-dnsname golang-github-containers-common golang-github-containers-image
  gsettings-desktop-schemas libavahi-client3 libavahi-common-data libavahi-common3 libavahi-glib1 libdconf1 libostree-1-1 libproxy1v5 libslirp0 libsoup2.4-1
  libsoup2.4-common podman session-migration slirp4netns uidmap
0 upgraded, 28 newly installed, 0 to remove and 0 not upgraded.
Need to get 22.9 MB of archives.
After this operation, 99.9 MB of additional disk space will be used.
```

```
Client:
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.17.3
Built:        Thu Jan  1 00:00:00 1970
OS/Arch:      linux/arm

Server:
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.17.3
Built:        Thu Jan  1 00:00:00 1970
OS/Arch:      linux/arm

# DOCKER_HOST=unix://$XDG_RUNTIME_DIR/podman/podman.sock docker version

Server: linux/arm/ubuntu-22.04
 Podman Engine:
  Version:          3.4.4
  APIVersion:       3.4.4
  Arch:             arm
  BuildTime:        1970-01-01T00:00:00Z
  Experimental:     false
  GitCommit:        
  GoVersion:        go1.17.3
  KernelVersion:    5.15.0-75-generic-lpae
  MinAPIVersion:    3.1.0
  Os:               linux
 Conmon:
  Version:          conmon version 2.0.25, commit: unknown
  Package:          conmon: /usr/bin/conmon
 OCI Runtime (crun):
  Version:          crun version 0.17
commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
spec: 1.0.0
+SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  Package:          crun: /usr/bin/crun
 Engine:
  Version:          3.4.4
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.17.3
  Git commit:       
  Built:            Thu Jan  1 00:00:00 1970
  OS/Arch:          linux/arm
  Experimental:     false
```

```
anders@lima-armv7l:~$ podman run busybox true
Resolved "busybox" as an alias (/etc/containers/registries.conf.d/shortnames.conf)
Trying to pull docker.io/library/busybox:latest...
Getting image source signatures
Copying blob afac622c5a1d done  
Copying config bd795ada44 done  
Writing manifest to image destination
Storing signatures
```

**Comment by afbjorklund** [comment]
@c-herz if you get a chance to try out `master` branch, it would be interesting to see how it works for you...

For embedded development it _might_ be interesting to expand `legacyBIOS` with custom firmware, perhaps?
But it seems to be working well enough (no `-bios`) for the default distribution, so maybe it is not necessary

Currently it is running Ubuntu 20.04 LTS, which still supports arm32. There is no such alpine-lima yet, however.

**Comment by c-herz** [comment]
I haven't had time to yet, but I definitely will try out the updated version with the changes. This isn't for professional embedded development, just hobbyist tinkering, so I think it will be sufficient for what I was looking for. Your idea regarding custom firmware is intriguing though. Getting U-boot or another embedded bootloader working on Lima would be pretty cool, but I don't know if the effort required to get everything to work together would be worth it given how niche of an application this is. If I'm not mistaken, without BIOS you would also need to somehow create a device tree blob for the emulated system to be used during boot, since there's obviously no ACPI or PnP in that case. It's definitely worth considering, but might be a bit of a headache to set up. This isn't my area of expertise though, so please correct me if I'm wrong.

**Comment by afbjorklund** [comment]
You would still have to do all the tinkering, but today the "legacyBIOS" is a boolean (the default is UEFI). It could get an optional "path" variable, since we need that anyway to support old QEMU versions...

I think kernel and cmdline is already available ?
