### ISSUE TITLE
stat /Users/cheimu/.ssh/jumpserver: no such file or directory

### ISSUE THREAD

**Issue by cheimu** [lima-vm/lima#164]
Hi I'm trying install lima on my mac `brew install lima`, and when I try `limactl start`, I got the following error:
```
INFO[0000] Using the existing instance "default"
INFO[0000] Downloading "https://github.com/containerd/nerdctl/releases/download/v0.11.0/nerdctl-full-0.11.0-linux-amd64.tar.gz" (sha256:a491a3129beddf2feb41a8ea9dcd0d3e4c9cb36c3a21046675e425f4b3daa5a9)
INFO[0000] Using cache "/Users/cheimu/Library/Caches/lima/download/by-url-sha256/fdbae42d5655d51afaedd0563a278bc93ea15d4f90aa8722164682cb77fff619/data"
INFO[0001] [hostagent] time="2021-08-20T21:18:46+08:00" level=fatal msg="stat /Users/cheimu/.ssh/jumpserver: no such file or directory"
```
The installed lima version is 0.6.0

I don't know why it requires this jumpserver file, and could anyone help me know what contents should be in this file? Thank you in advance!

**Comment by cheimu** [comment]
Solved by set `loadDotSSHPubKeys: false`

**Comment by jandubois** [comment]
Just FYI: You probably have a public key `/Users/cheimu/.ssh/jumpserver.pub` on your system, but for some reason the corresponding private key is missing.

Lima adds all public keys to the instance, so you can authenticate with any of the private keys; it throws an error when it can't find the corresponding private keys.

So unless you have a copy of the private key somewhere else, you could probably also delete the public key, as it isn't very useful by itself.

Also, if there is a reason for having a public key without the private key in your `~/.ssh`, I would like to understand how this happens, as we have seen other users with the same issue before, and I have no idea why.
