### ISSUE TITLE
console messages not logged to hvc0

### ISSUE THREAD

**Issue by ryancurrah** [lima-vm/lima#1659]
### Description

We are trying to troubleshoot an issue with the VZ virtual machine not starting correctly and the console messages are not being logged to `~/.lima/<vm_name>/serial.log`. This is making it hard to troubleshoot because we cannot SSH into the VM to look at the logs.

We are using Colima which uses a fork of https://github.com/lima-vm/alpine-lima. So I think we need to modify the Alpine bootloader to tell the kernel to also log to `hvc0`.

If you want to test this out you can run the below command on a Lima Alpine VM and look at the serial log (`~/.lima/<vm_name>/serial.log`).

```
sudo sh -c 'echo "Test message" > /dev/hvc0'
```

```
cat ~/.lima/default/serial.log
```

**Comment by AkihiroSuda** [comment]
> how

Needs to be done on Apple's side.

**Comment by ryancurrah** [comment]
So I was wrong looks like it is supported see https://github.com/lima-vm/lima/blob/d9f0c51db0e84576692da4dde242ea150e3c16ee/pkg/vz/vm_darwin.go#L236-L247.

This adds the device `hcv0` to the Operating System. The `hcv0` device in Linux is a hypervisor virtual console device, which is often used in virtualized environments. This device is often present on systems running under hypervisors like Xen or KVM, or cloud environments like Amazon EC2 instances or IBM's PowerVM.

Hypervisors usually provide a para-virtualized console device for guests, which is different from emulated devices like ttyS0 (the first serial port). Para-virtualized devices can provide better performance than emulated devices because they are specifically designed to work in a virtualized environment.

When you specify `console=hvc0` in the kernel boot parameters, you're telling the kernel to output its console messages to this virtual console device. 

So I created a Ubuntu VM using Lima and modified the file `/etc/default/grub.d/50-cloudimg-settings.cfg` to log kernel messages to this device by prepending `console=hvc0` to `GRUB_CMDLINE_LINUX_DEFAULT`.

```
GRUB_CMDLINE_LINUX_DEFAULT="console=hvc0 console=tty1 console=ttyS0"
```

Ran `sudo update-grub` rebooted the VM and voila kernel logs started appearing in `~/.lima/testvz/serial.log`.

But I would like these logs in the Lima Alpine image and started looking at it but I'm not sure where to modify the boot loader settings.

**Comment by ryancurrah** [comment]
Ok, another update. I cloned [alpine-lima](https://github.com/lima-vm/alpine-lima) and modified `alpine-lima-std-3.18.0-x86_64.iso` to also write console messages to `hvc0` and it worked with the `vz` example! 

I have attached the [serial.log](https://github.com/lima-vm/lima/files/11994184/serial.log) file with the console log output.

Below is my diff to [alpine-lima](https://github.com/lima-vm/alpine-lima).

 > Note: I removed `--repository "/home/build/packages/lima"` because it was logging warnings and it is not used anywhere, even in the GitHub actions logs I can see `WARNING: opening /home/build/packages/lima: No such file or directory`. Again this does not seem to be used so seems like it was kept around as a mistake.

```diff
diff --git a/build.sh b/build.sh
index d866949..a3316bc 100755
--- a/build.sh
+++ b/build.sh
@@ -31,7 +31,6 @@ ${DOCKER} run --rm \
     --tag "${TAG}" \
     --outdir /iso \
     --arch "${ARCH}" \
-    --repository "/home/build/packages/lima" \
     --repository "http://dl-cdn.alpinelinux.org/alpine/${REPO_VERSION}/main" \
     --repository "http://dl-cdn.alpinelinux.org/alpine/${REPO_VERSION}/community" \
     --profile lima
diff --git a/mkimg.lima.sh b/mkimg.lima.sh
index 47bbd83..5411d81 100755
--- a/mkimg.lima.sh
+++ b/mkimg.lima.sh
@@ -10,7 +10,7 @@ profile_lima() {
        initfs_cmdline="modules=loop,squashfs,sd-mod,usb-storage"
        kernel_addons=
        kernel_flavors="virt"
-       kernel_cmdline="console=tty0 console=ttyS0,115200"
+       kernel_cmdline="console=hvc0 console=tty0 console=ttyS0,115200"
        syslinux_serial="0 115200"
        apkovl="genapkovl-lima.sh"
        apks="$apks openssh-server-pam"
```

**Comment by ryancurrah** [comment]
Ok so I just tried it with Qemu and it did not error out. I shelled into the VM and checked in the device `/dev/hvc0` exist in Qemu, but it does not. I checked the serial.log and it still works. I grepped `/var/log` and did not see any errors related to `hvc0`. So it seems this change should work for VZ and not affect Qemu.

```
lima-testvz:/Users/ryancurrah/git/github.com/ryancurrah/lima$ sudo grep -R hvc0 /var/log/
/var/log/messages:Jul  9 02:23:48 alpine authpriv.notice sudo: ryancurrah : TTY=pts/0 ; PWD=/Users/ryancurrah/git/github.com/ryancurrah/lima ; USER=root ; COMMAND=/bin/grep -R hvc0 /var/log/
/var/log/dmesg:[    0.000000] Kernel command line: BOOT_IMAGE=/boot/vmlinuz-virt modules=loop,squashfs,sd-mod,usb-storage console=hvc0 console=tty0 console=ttyS0,115200
```

**Comment by jandubois** [comment]
> Note: I removed `--repository "/home/build/packages/lima"` because it was logging warnings and it is not used anywhere

That is correct. It should have been removed as part of https://github.com/lima-vm/alpine-lima/commit/e29465f. It is just a build-time warning though.

**Comment by jandubois** [comment]
> Should I open a PR to this repo?

I've verified that the change also works on M1 Macs, so please do open a PR!

If you don't mind, include this change as well:

```diff
--- lima.sh
+++ lima.sh
@@ -17,8 +17,6 @@ mounts:
   writable: true
 ssh:
   localPort: 40022
-firmware:
-  legacyBIOS: true
 video:
   display: $display
 containerd:
```

The `legacyBIOS` setting is no longer needed on `x86_64` and causes a failure on `aarch64`.

**Comment by ryancurrah** [comment]
I will have a PR up later today.

**Comment by ryancurrah** [comment]
Opened: https://github.com/lima-vm/alpine-lima/pull/109

**Comment by ryancurrah** [comment]
One problem with this is that the last `console` will be the one to receive console messages after boot. So once the VM is booted it will no longer receive console messages. We could put it last but then Qemu would no longer receive console logs after boot. I'm looking into this more.

**Comment by ryancurrah** [comment]
I tried a few things they did not pan out. The only thing I can think of is if you create a separate iso image for VZ and Qemu.

**Comment by AkihiroSuda** [comment]
> I tried a few things they did not pan out. The only thing I can think of is if you create a separate iso image for VZ and Qemu.

Can we just support hvc0 in qemu too?

**Comment by ryancurrah** [comment]
After a quick look it seems possible. Will investigate tomorrow.

**Comment by ryancurrah** [comment]
Got it working. That was easier to do than I thought. Spun up a Qemu VM and got serial logs on `hvc0`. And it's even better than the `tty` logs because it does not contain all the console formatting. Great suggestion @AkihiroSuda. Attached is the [serial.log](https://github.com/lima-vm/lima/files/12002523/serial.log). We got kernel logs from start AND shutdown which is great.

> The hvc0 console, which is a type of virtio console, is a relatively simple console interface and does not support all the features that a more fully-featured console like tty0 or ttyS0 might support.
> 
> One of these missing features is support for VT100 or ANSI escape sequences, which are used to control things like color, cursor position, and other formatting on the console. When you're using hvc0, you're interacting with the console at a very low level, and a lot of the "niceties" you might be used to from a full terminal emulator are not present.
> 
> This simplicity, however, is also one of the strengths of hvc0 and other virtio consoles: they're very lightweight and efficient, and they're well-suited for high-speed, low-latency communication between the host and the guest. They're ideal for tasks like logging kernel messages, where the ability to handle large amounts of data quickly is more important than having advanced formatting capabilities.

```diff
diff --git a/pkg/qemu/qemu.go b/pkg/qemu/qemu.go
index 3e2214d..a27c3eb 100644
--- a/pkg/qemu/qemu.go
+++ b/pkg/qemu/qemu.go
@@ -816,7 +816,8 @@ func Cmdline(cfg Config) (string, []string, error) {
        }
        const serialChardev = "char-serial"
        args = append(args, "-chardev", fmt.Sprintf("socket,id=%s,path=%s,server=on,wait=off,logfile=%s", serialChardev, serialSock, serialLog))
-       args = append(args, "-serial", "chardev:"+serialChardev)
+       args = append(args, "-device", "virtio-serial")
+       args = append(args, "-device", fmt.Sprintf("virtconsole,chardev=%s,id=console1,name=console", serialChardev))

        // We also want to enable vsock here, but QEMU does not support vsock for macOS hosts
```

```diff
diff --git a/mkimg.lima.sh b/mkimg.lima.sh
index 5411d81..c5cb831 100755
--- a/mkimg.lima.sh
+++ b/mkimg.lima.sh
@@ -10,7 +10,7 @@ profile_lima() {
        initfs_cmdline="modules=loop,squashfs,sd-mod,usb-storage"
        kernel_addons=
        kernel_flavors="virt"
-       kernel_cmdline="console=hvc0 console=tty0 console=ttyS0,115200"
+       kernel_cmdline="console=hvc0"
        syslinux_serial="0 115200"
        apkovl="genapkovl-lima.sh"
        apks="$apks openssh-server-pam"
```

Should I create a PR in lima and update alpine-lima to only use hvc0?

**Comment by ryancurrah** [comment]
Any thoughts on the above? @jandubois or @AkihiroSuda

**Comment by jandubois** [comment]
> Any thoughts on the above? @jandubois or @AkihiroSuda

Seems fine to me, but please wait for feedback from @AkihiroSuda 

I don't have the ISO running here anymore, but I hope things like backspace and tab-completion still work. But even if they don't, getting clean logs everywhere is probably worth it.

Anyways, create the PRs; that makes it easier to do a final round of testing!

**Comment by ryancurrah** [comment]
I could test it with the gui to ensure console access still works there.

**Comment by AkihiroSuda** [comment]
QEMU driver should continue to print the RS-232C to serial.log for compatibility sake.
Virtio serial log can be printed to something like “serial-virtio.log”.
The VZ driver should use the same file name.

**Comment by ryancurrah** [comment]
What would be reading the serial.log that needs all the a extra terminal characters?

**Comment by AkihiroSuda** [comment]
> What would be reading the serial.log that needs all the extra terminal characters?

Humans, for debugging purpose

**Comment by AkihiroSuda** [comment]
- https://github.com/lima-vm/lima/pull/1674

**Comment by ryancurrah** [comment]
I took a look at the change. You have to choose one or the other. Both won't receive a stream of console messages after boot. While they both will receive initial boot messages. Also need to enable hvc0 in the bootloader for it to work.

**Comment by AkihiroSuda** [comment]
The guest OS has to choose one, but QEMU can provide both

**Comment by ryancurrah** [comment]
Ok that's good. So now we need to exit the Alpine Lima image. What were you thoughts on that change?

**Comment by AkihiroSuda** [comment]
The alpine-lima image has to be updated.

Ideally the kernel should be able to automatically detect the best one, though.

**Comment by jandubois** [comment]
I agree that having a single `serial.log` would be better.

@AkihiroSuda do the ANSI sequences in the old style really provide so much value to you to justify the extra complexity? Or am I missing something, and are there other differences? I haven't retested using `socat` with the `hvc0` console; is it less usable than the old one?

**Comment by ryancurrah** [comment]
Not having serial logs is a pretty big issue for vz users it leaves us Iva me to troubleshoot issues with the vm. Hoping for a reply soon.

**Comment by AkihiroSuda** [comment]
hvc0 is now supported by both QEMU driver and VZ driver, so alpine-lima may just enable hvc0.

The video display is also now available for both QEMU and  VZ, so it should be useful too. (`limactl start --video`)

**Comment by afbjorklund** [comment]
I recently synched some changes for alpine-lima, it was missing the latest changes from upstream:

https://github.com/alpinelinux/aports/commit/4ad0b08bfa38cf664469c28a0e35492e0de56e86

https://github.com/alpinelinux/aports/commit/f81ba92e56993a63a92a5f4de83da79734ed2540

I think it's something of a problem when there are paravirt changes needed to the emulated OS?

**Comment by ryancurrah** [comment]
@AkihiroSuda I understand that you're quite busy, especially with you're open-source commitments, but I noticed that you made a code change without addressing your co-workers' concerns. In an open-source environment where collaboration is key, it would have been more professional to at least acknowledge their input. I'm not trying to be overly critical, but I believe a courteous response would have been in line with our community values.

I did test this solution and it is now working. I ran `cat ~/.lima/colima/serialv.log` and it is empty. I believe the solution is to add hvc0 to the bootloader console options. The below diff would be the optimal solution for ensuring kernel messages are logged at boot time and during runtime.  

```diff
diff --git a/mkimg.lima.sh b/mkimg.lima.sh
index 47bbd83..5411d81 100755
--- a/mkimg.lima.sh
+++ b/mkimg.lima.sh
@@ -10,7 +10,7 @@ profile_lima() {
        initfs_cmdline="modules=loop,squashfs,sd-mod,usb-storage"
        kernel_addons=
        kernel_flavors="virt"
-       kernel_cmdline="console=tty0 console=ttyS0,115200"
+       kernel_cmdline="console=hvc0"
        syslinux_serial="0 115200"
        apkovl="genapkovl-lima.sh"
        apks="$apks openssh-server-pam"
```

**Comment by AkihiroSuda** [comment]
> I understand that you're quite busy, especially with you're open-source commitments, but I noticed that you made a code change without addressing your co-workers' concerns. 

Sorry, which concern?

**Comment by AkihiroSuda** [comment]
https://github.com/lima-vm/lima/issues/1659#issuecomment-1646028479

> I agree that having a single `serial.log` would be better.

Ideally we should only have a single `serial.log` (with a single serial port), but unification isn't realistic, as some image uses `ttyS0`, some uses `hvc0`, and some uses `ttyAMA0`. 

> @AkihiroSuda do the ANSI sequences in the old style really provide so much value to you to justify the extra complexity? Or am I missing something, and are there other differences? I haven't retested using `socat` with the `hvc0` console; is it less usable than the old one?

The ANSI colors are sometimes useful, although not necessary.

**Comment by ryancurrah** [comment]
Thanks @AkihiroSuda!

**Comment by ryancurrah** [comment]
@AkihiroSuda to make your changes work we need to merge this change and create a new Alpine Lima image.

https://github.com/lima-vm/alpine-lima/pull/112
