### ISSUE TITLE
usernet: socket name is too long

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/lima#1678]
`len("/Users/<USER>/.lima/<INSTANCE>/usernet_<NETWORK>_endpoint.sock")` may hit the 104 limit

https://github.com/lima-vm/lima/blob/5a3504432866ecc3f93e459bc1f9a97f846e1f5c/pkg/networks/usernet/config.go#L27-L30

**Comment by jandubois** [comment]
We need to update the logic in https://github.com/lima-vm/lima/blob/4761cf5e803b941c81028e623c28e03743fbc30c/cmd/limactl/start.go#L279-L284 but maybe we should also shorten the substrings `usernet` and `endpoint` a bit to make it less likely to hit the limit?

**Comment by AkihiroSuda** [comment]
@balajiv113 WDYT? Maybe we can use a hash to shorten the socket name?

**Comment by jandubois** [comment]
> Maybe we can use a hash to shorten the socket name?

I think keeping the `NETWORK` name is useful to identify the socket, and the user can shorten the name as needed. It should also be unique by itself (together with the suffix).

So I would suggest dropping `usernet_` prefix and shortening the suffix to e.g. `_ep`, so

```
/Users/<USER>/.lima/<INSTANCE>/usernet_<NETWORK>_endpoint.sock
```

becomes

```
/Users/<USER>/.lima/<INSTANCE>/<NETWORK>_ep.sock
```

The "maxSockName" test will have to take the longest NETWORK name used into account.

**Comment by balajiv113** [comment]
> WDYT? Maybe we can use a hash to shorten the socket name?
@AkihiroSuda I like the suggestion of jandubois. Mainly for the user visibility.

I can take care of this with a PR today if this model looks good for you as well

**Comment by AkihiroSuda** [comment]
> > WDYT? Maybe we can use a hash to shorten the socket name?
> 
> @AkihiroSuda I like the suggestion of jandubois. Mainly for the user visibility. I can take care of this with a PR today if this model looks good for you as well

Yes, thanks.
After merging your PR, I think we can release v0 17
