### ISSUE TITLE
user-v2: make IP addresses deterministic

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/lima#1785]
https://github.com/lima-vm/lima/discussions/1181#discussioncomment-6961729

**Comment by AkihiroSuda** [comment]
This seems needed to keep the VM sshable after running `sudo reboot` in the VM

cc @balajiv113

**Comment by balajiv113** [comment]
@AkihiroSuda With a normal reboot from vm it still works without issues. 

Are you talking about any race condition ??

**Comment by AkihiroSuda** [comment]
> @AkihiroSuda With a normal reboot from vm it still works without issues.
> 
> Are you talking about any race condition ??

Yes, seems a race. Just observed an unsshable reboot once.
Maybe not an issue of user-v2.

(Deterministic IP is still desired for multi-node Kube though)

**Comment by kullervo610** [comment]
Just question, are you considering Deterministic IPs also for `Shared`network, or only `user-v2`network?

**Comment by AkihiroSuda** [comment]
> Just question, are you considering Deterministic IPs also for `Shared`network, or only `user-v2`network?

For `shared` network the IP is decided by Apple's vmnet.framework, not by Lima.
See here for deterministic IP with vmnet.framework: https://github.com/lima-vm/socket_vmnet/tree/v1.1.2#how-to-use-static-ip-addresses

**Comment by kullervo610** [comment]
Understood, thanks for clarification. Now I understand why you focus `user-v2`network. Even Host-VM communication will not be possible with `user-v2`network, getting support deterministic IP will be a big improvement so big thanks to considering to adding it.

With `Shared` network i will try out method proposed by above link and if needed will follow-up that topic under discussions

**Comment by balajiv113** [comment]
An approach for implementing this, i was thinking of serializing the leases to a json file on stop of user-v2 and on startup of user-v2 daemon we could pass through the same for static leases.

This way we will get deterministic ip as long as mac address stays the same. This requires zero changes from gvisor-tap-vsock as well

**Comment by AkihiroSuda** [comment]
> An approach for implementing this, i was thinking of serializing the leases to a json file on stop of user-v2 and on startup of user-v2 daemon we could pass through the same for static leases.
> 
> This way we will get deterministic ip as long as mac address stays the same. This requires zero changes from gvisor-tap-vsock as well

SGTM 👍
