### ISSUE TITLE
Add ulimit setting for sftp-server

### ISSUE THREAD

**Issue by lkeller-synaptics** [lima-vm/lima#1789]
### Description

As far as I can tell the sftp server for the sshfs mount type is currently started with the ulimit for file descriptors of the process starting lima (I was able to confirm this via colima only). On MacOSX 12 this is set by default to 256. When the guest host tries to open more than 256 file descriptors on a mounted volume the operation fails with an "Operation not permitted" error which is very confusing as the limits of the host are not attained.

It would be nice to have some explicit setting or a very high default setting of the ulimit of the sftp-server so that the ulimit of the guest applies and not the one of the host.

**Comment by vasileknik76** [comment]
Perhaps this was fixed in [#2015](https://github.com/lima-vm/lima/pull/2015)
