### ISSUE TITLE
/tmp/XXXX No such file or directory

### ISSUE THREAD

**Issue by utam0k** [lima-vm/lima#183]
Thanks for the great software! 
I ran into a strange phenomenon. When I ran lima in the `tmp` directory as shown below, it did not work. However, it works fine in the home directory. I will provide the necessary information if there is any.

```sh
$ cd $(mktemp -d /tmp/XXXXX)
$ lima nerdctl run fedora:34 /bin/true
bash: line 1: cd: /tmp/C3Yus: No such file or directory
$ cd
$ pwd
/Users/utam0k
$ lima nerdctl run fedora:34 /bin/true
$ lima --version
limactl version 0.6.1
```

**Comment by AkihiroSuda** [comment]
Expected behavior, with the default configuration

https://github.com/lima-vm/lima/tree/v0.6.1#configuration

> Mounts: ~ (read-only), /tmp/lima (writable)

**Comment by utam0k** [comment]
@AkihiroSuda Thanks for your reply.
This was done by creating a tmp directory on the Mac side, moving it to that directory, and simply trying to start it. In other words, I wasn't going to use file-sharing, but would this still not work?
I'm still in the process of trying out lima and don't understand much about it, so I apologize if I misunderstood something.

**Comment by AkihiroSuda** [comment]
Lima tries to let the guest chdir to the cwd of the host, but does not result in an error if the host cwd path does not exist on the guest.

The guest cwd can be also explicitly specified with `limactl shell --workdir=/foo default`

**Comment by utam0k** [comment]
@AkihiroSuda 
Oh, I see! I understand now. I moved it to `/tmp/lima` and ran it, and it worked.
One more question, is it possible to bind-mount `/tmp/lima`? I'm having trouble getting a response from this command.
````
$ pwd
/tmp/lima
$ lima sh -c 'ls /tmp/lima'
another-file
$ lima nerdctl run -v /tmp/lima:/tmp/lima fedora:34
```

**Comment by AkihiroSuda** [comment]
Seems hitting https://github.com/containerd/nerdctl/issues/338

I'll try to analyze this tomorrow

**Comment by utam0k** [comment]
I am looking forward to the results of the survey. BTW, I installed podman on qemu and tried bind-mount, but it didn't work.
