### ISSUE TITLE
Adopt a license scanning tool

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/lima#1831]
> Adopt a license scanning tool, like [FOSSA](https://fossa.com/) or [Snyk](https://snyk.io/)

- https://github.com/cncf/toc/issues/924

**Comment by AkihiroSuda** [comment]
Maybe we can use github.com/google/go-licenses

**Comment by balajiv113** [comment]
Snyk looks interesting. 
Offers good set of features including license scanning for open-source projects.

**Comment by afbjorklund** [comment]
> Maybe we can use https://github.com/google/go-licenses

Yes, seems to be working:
