### ISSUE TITLE
website: "Install Lima" icon should be clickable

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/lima#1838]
The icons on https://lima-vm.io/ should be clickable

![image](https://github.com/lima-vm/lima/assets/9248427/b8ac019f-1f68-454e-b680-16ae8502f3b5)

**Comment by Nik-09** [comment]
Hi, @AkihiroSuda can you please assign to this issue to me?
Thanks

**Comment by Victor-Chris** [comment]
Hey @AkihiroSuda, would you mind if I took a peek at it as well?

**Comment by AkihiroSuda** [comment]
Fixed in
- https://github.com/lima-vm/lima/pull/1876
