### ISSUE TITLE
Hitting <Ctrl>+C on the `limactl start` interactive prompt does not cancel the operation

### ISSUE THREAD

**Issue by cwegener** [lima-vm/lima#1887]
### Steps to reproduce:

1. Create a new lima VM with `limactl start --name=nameofVMthatdoesntexistyet`
2. Wait for prompt to appear and then press `<Ctrl>+C`

### Expected result:

- The user is returned back to the shell prompt and the lima VM creation process does NOT initiate

### Actual result:

- The lima VM creation process continues as if `<Enter>` was pressed, accepting the `Proceed with current configuration` prompt

Details:
- OS: Archlinux
- lima version: 0.17.2

**Comment by pmalek** [comment]
I've just tried this on lima `limactl version HEAD-c4986e7` and it works:

```
$ limactl list
NAME    STATUS     SSH            ARCH       CPUS    MEMORY    DISK     DIR
$ limactl start lima
INFO[0000] Using the existing instance "lima"
INFO[0000] [hostagent] hostagent socket created at /Users/USER/.lima/lima/ha.sock
INFO[0000] [hostagent] Starting VZ (hint: to watch the boot progress, see "/Users/USER/.lima/lima/serial*.log")
INFO[0000] [hostagent] new connection from  to
INFO[0000] SSH Local Port: 53151
INFO[0000] [hostagent] [VZ] - vm state change: running
INFO[0000] [hostagent] Waiting for the essential requirement 1 of 3: "ssh"
^C
$ limactl list
NAME    STATUS     SSH                ARCH       CPUS    MEMORY    DISK     DIR
lima    Stopped    127.0.0.1:53151    aarch64    6       10GiB     60GiB    ~/.lima/lima
```

**Comment by afbjorklund** [comment]
I think the issue is when hitting Ctrl+C during the prompt itself:

```console
$ limactl start foo
INFO[0000] Creating an instance "foo" from template://default (Not from template://foo) 
WARN[0000] This form is deprecated. Use `limactl create --name=foo template://default` instead 
? Creating an instance "foo"  [Use arrows to move, type to filter]
> Proceed with the current configuration
  Open an editor to review or modify the current configuration
  Choose another template (docker, podman, archlinux, fedora, ...)
  Exit
WARN[0001] Failed to open TUI                            error=interrupt
INFO[0001] Attempting to download the image              arch=x86_64 digest="sha256:f6529be56da3429a56e4f5ef202bf4958201bc63f8541e478caa6e8eb712e635" location="https://cloud-images.ubuntu.com/releases/23.10/release-20231011/ubuntu-23.10-server-cloudimg-amd64.img"

```

**Comment by cwegener** [comment]
> I think the issue is when hitting Ctrl+C during the prompt itself:

Yes. That's what I was referring to. I have edited the reproduction steps to make it clear that the problem occurs when creating a new VM (and not when starting an existing VM)

**Comment by afbjorklund** [comment]
https://github.com/AlecAivazis/survey#why-isnt-ctrl-c-working

**Comment by cwegener** [comment]
> https://github.com/AlecAivazis/survey#why-isnt-ctrl-c-working

Yup. That works. Not sure how much unit testing is required for this change ...
