### ISSUE TITLE
RFC: Remove the color prompt overrides from default instance and shell environment for v1.0?

### ISSUE THREAD

**Issue by afbjorklund** [lima-vm/lima#1892]
### Description

We had an old issue, to make the `lima` prompt distinguishable from the host prompt.

The color was playing on the "lime" word game, and used a bright yellow-green ([Lime](https://en.wikipedia.org/wiki/Lime_(color))) 

<details>
Here the color(s) shown in Ubuntu terminal:

![lima-shell-color-prompt](https://user-images.githubusercontent.com/10364051/142941057-6ef7fdae-32da-4242-a298-c857e2e62c11.png)
</details>

----

But it requires 24-bit color support to look best, as an addition to 256 (or 16) colors support:

* https://github.com/lima-vm/lima/pull/433

* https://github.com/lima-vm/lima/pull/435

* `COLORTERM=truecolor`

And it doesn't really _work_ on light backgrounds, so requires support for the terminal "theme":

* https://github.com/lima-vm/lima/issues/485

* https://github.com/lima-vm/lima/pull/486

* `TERMTHEME=Dark`

----

So I think the best would be to remove those changes, and go back to the original issue:

* https://github.com/lima-vm/lima/issues/427

Go back to the original Ubuntu prompt:

```diff
-if [ "$color_prompt" = yes ]; then
-    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
+# Lima PS1: set color to lime
+if [ "$color_prompt" = true ]; then
+    PS1='${debian_chroot:+($debian_chroot)}\[\033[38;2;192;255;0m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
+elif [ "$color_prompt" = 256 ]; then
+    PS1='${debian_chroot:+($debian_chroot)}\[\033[38;5;154m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
+elif [ "$color_prompt" = yes ]; then
+    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;92m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
 else
     PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
 fi
```

Note that the default prompt **does** have the host name in it, which does include "lima":

```console
anders@lima-default:/home/anders$ uname
Linux
```

But it could be desired to change the prompt?

`[ "$PS1" ] && PS1="[LIMA] $PS1"`

**Comment by afbjorklund** [comment]
A compromise, if wanting to keep the color override, would be to go for "lime green"

* `#32CD32`

**Comment by afbjorklund** [comment]
Two issues:

- Remove the export of the COLORTERM variable ? It is available on the host, but not (normally) over ssh connections.
  It complicates the ssh setup a bit, have to send it from the client and also accept it on the host. But it is "generic".

- Remove the change of color in the "default" instance. Note that "ubuntu" (without nerdctl) does **not** get patched...
  After the latest change, it will only change the default green prompt to a slightly more lime green on color terminals.

After that:

- Should the `limactl shell` change the PS1, similar to what Singularity/Apptainer does ? (Docker/Podman does not)

- Or should we rely on the user shell configuration to pick up the presence of `SSH_CLIENT`, like Powerline does?

**Comment by AkihiroSuda** [comment]
I guess we can just remove the custom PS1

**Comment by afbjorklund** [comment]
I'm seeing lime green color everywhere, so think I will just keep it as it is now.

<img src="https://github.com/lima-vm/lima/assets/10364051/70507c3a-fc3c-44f8-b776-ddca6340bab3" alt="lime" width="512" />
