### ISSUE TITLE
Feature request: ability to edit an instance

### ISSUE THREAD

**Issue by mkopinsky** [lima-vm/lima#190]
As far as I can tell, the only time I can edit the configuration of an instance is the first time I run `limactl start`. It would be nice if I could do something like:

* `limactl stop default`
* `limactl edit default` (opens editor just like the first time it's created)
* `limactl start default`

Maybe this is already possible somehow? If so, I can't find the documentation in either the repo or in CLI help.

**Comment by AkihiroSuda** [comment]
This is already (unofficially) possible with `vi ~/.lima/default/lima.yaml`.

https://github.com/lima-vm/lima/blob/master/docs/internal.md#instance-directory-lima_homeinstance

I agree we should have the proper CLI command for this.

**Comment by afbjorklund** [comment]
Do you need a command `limactl restart default`, as well ?

**Comment by afbjorklund** [comment]
Would it be possible to do this in two steps too, so that we can use an external editor - like for instance a GUI ?

One command to output the current YAML for an instance, one command (or edit param) to update from a file.

**Comment by jandubois** [comment]
> Would it be possible to do this in two steps too, so that we can use an external editor - like for instance a GUI ?
> 
> One command to output the current YAML for an instance, one command (or edit param) to update from a file.

I think that is too much scaffolding. You can already get the name of the config with our API:

```console
$ limactl ls -f '{{.LimaHome}}/{{.Name}}/lima.yaml' default
/Users/jan/.lima/default/lima.yaml
```

So from a GUI you get the filename, edit the content, and restart the instance (using `stop` and `start`). So all the building blocks already exist.

Or maybe I misunderstand what you are trying to do.

**Comment by afbjorklund** [comment]
Sure, that would work too.

**Comment by jandubois** [comment]
> Sure, that would work too.

I'm just trying to keep our API as small as possible, to avoid overwhelming new users with complexity. Tools like `qemu` or `git ` create a lot of anxiety when people try to wrap their heads around them for the first time, and some simply give up.

So having a small set of basic building blocks that people can use to create their own integrations is preferable to me. Every new API needs to justify why it is necessary! 😄

**Comment by afbjorklund** [comment]
I think the `{{.LimaHome}}/{{.Name}}` dir was already being provided by `limactl list --json`, so easy enough.
