### ISSUE TITLE
Username with '@' causes fatal error in `limactl start`

### ISSUE THREAD

**Issue by xonstone** [lima-vm/lima#191]
Executing `limactl start` with a username containing an "@" will trigger following error

```
DEBU[0000] interpreting argument "default" as an instance name "default" 
INFO[0000] Using the existing instance "default"        
FATA[0000] identifier "xxx@xxxx.com" must match ^[A-Za-z0-9]+(?:[._-](?:[A-Za-z0-9]+))*$: invalid argument 
```

**Comment by jandubois** [comment]
The error comes from Lima requiring the user name to be a valid identifier: https://github.com/lima-vm/lima/blob/be68278/pkg/cidata/template.go#L48

According to `man useradd` the `@` character is not valid in usernames:

> Usernames may contain only lower and upper case letters, digits, underscores, or dashes. They can end with a dollar sign. Dashes are not allowed at the beginning of the username. Fully numeric usernames and usernames . or .. are also disallowed. It is not recommended to use usernames beginning with . character as their home directories will be hidden in the ls output.

@AkihiroSuda What do you suggest should we do?

* I think allowing "invalid" user names could work for most functionality, so we could relax the authentication requirements.
* Or we could simply truncate the username at the `@` character to support email addresses as username on the host; the name will just be different inside the VM. We just have to make sure we perform the same modification when we pass the username to `ssh`.

I think I prefer the second option; even though it may have some issues when the user passes `$USER` to the `lima` command, like:

```
lima sudo chown $USER /usr/local/bin
```

But I would just document that as a limitation for users that use email addresses as user names on the host. I think this is a rather uncommon practice.

**Comment by jandubois** [comment]
Maybe instead of heuristics inside Lima to modify non-conforming user names, we should support a `LIMA_USER` environment variable that will be used to override the `u.Username` result returned by `current.User()`?

**Comment by AkihiroSuda** [comment]
I didn’t know that macOS allows having “@“ in user names.

Would it be too harsh to ask users to just change their user names on the host?

How many people have “@“ in user names, and why? Is this related to corporate directory services like LDAP and Active Directory?

**Comment by AkihiroSuda** [comment]
Relabeling the issue from “bug” to “enhancement”, as “@“ seems officially invalid in the Linux ecosystem according to the man page above.

**Comment by jandubois** [comment]
> I didn’t know that macOS allows having “@“ in user names.

It doesn't allow me to create a local user with an `@` in the name. It just beeps when I press it.

> How many people have “@“ in user names, and why? Is this related to corporate directory services like LDAP and Active Directory?

I suspect it comes from a directory service. Just like the 7 digit uids. @xonstone can you confirm?

> Would it be too harsh to ask users to just change their user names on the host?

If it comes from corporate directory services, then the user may have no choice. That's why I suggested allowing `USER_LIMA` as an escape hatch. In the spirit of the Larry Wall quote: "The Golden Gate wasn't our fault either, but we still built a bridge across it."

**Comment by xonstone** [comment]
> How many people have “@“ in user names, and why? Is this related to corporate directory services like LDAP and Active Directory?

> I suspect it comes from a directory service. Just like the 7 digit uids. @xonstone can you confirm?

Yeah, this user was provisioned by the directory service of my employer and is coupled to my company email.

> Would it be too harsh to ask users to just change their user names on the host?

> If it comes from corporate directory services, then the user may have no choice. That's why I suggested allowing USER_LIMA as an escape hatch. In the spirit of the Larry Wall quote: "The Golden Gate wasn't our fault either, but we still built a bridge across it."

We have no say in this.

**Comment by jandubois** [comment]
I realized that there is no benefit to making the fallback username configurable, but actually a drawback that the `LIMA_USER` environment variable would have to be defined in every context where `limactl` is to be called.

In #214 I have instead hardcoded the username inside the VM to be `lima` when the local username is not a valid Linux username, which should make everything work automatically without any extra configuration.
