### ISSUE TITLE
User mode provisioning doesn't seem to be running?

### ISSUE THREAD

**Issue by rayterrill** [lima-vm/lima#192]
System mode provisioning works great. User mode provisioning doesn't seem to be working? Is there a way to troubleshoot this? No indication of any attempts to run or errors in cloud-init-output.log.

```
provision:
  - mode: system # `system` is executed with the root privilege
    script: |
      #!/bin/bash
      #install k3s
      curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.18.20+k3s1 K3S_KUBECONFIG_MODE="644" sh -s - --disable=traefik
      #install helmfile
      wget https://github.com/roboll/helmfile/releases/download/v0.140.0/helmfile_linux_amd64 -O /usr/local/bin/helmfile && chmod +x /usr/local/bin/helmfile
      #install helm
      curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
      #update apt cache
      apt update
      #install aws cli
      apt install awscli -y
      #install saml2aws
      wget -c https://github.com/Versent/saml2aws/releases/download/v2.32.0/saml2aws_2.32.0_linux_amd64.tar.gz -O - | tar -xzv -C /usr/local/bin && chmod +x /usr/local/bin/saml2aws
      #install sops
      TEMP_DEB="$(mktemp)" && wget -O "$TEMP_DEB" ''https://github.com/mozilla/sops/releases/download/v3.7.1/sops_3.7.1_amd64.deb'' && sudo dpkg -i "$TEMP_DEB" && rm -f "$TEMP_DEB"
  - mode: user # `user` is executed without the root privilege
    script: |
      #!/bin/bash
      #install helm-secrets
      helm plugin install https://github.com/jkroepke/helm-secrets --version v3.8.2
      #install helm-diff
      helm plugin install https://github.com/databus23/helm-diff
```

**Comment by jandubois** [comment]
This was broken by https://github.com/lima-vm/lima/commit/933eda.

The scripts used to be extracted to `/var/lib/lima-guestagent/...` with `755` file permissions. Now they are part of the readonly `/mnt/lima-cidata`, are owned by `root`, and have `700` permissions, so are no longer executable by the regular user.

I have no idea why there is no warning/error in `/var/lib/cloud-init-output.log`.

@AkihiroSuda What is the best fix, copying the scripts to the users home before executing them? I assume we don't want to make the `cidata` user readable.

**Comment by AkihiroSuda** [comment]
> What is the best fix, copying the scripts to the user's home before executing them? 

SGTM

**Comment by rayterrill** [comment]
@jandubois @AkihiroSuda ETA for this to hit a release? Thank you so much for the quick response!

**Comment by AkihiroSuda** [comment]
Probably right af

**Comment by rayterrill** [comment]
THANK YOU! 🎉 🎉 🎉

**Comment by rayterrill** [comment]
@jandubois @AkihiroSuda Grabbed 0.6.2 this AM and user mode provisioning is working great! Thank you!
