### ISSUE TITLE
Docer container wont start. M1

### ISSUE THREAD

**Issue by pretendent0** [lima-vm/lima#201]
After successfully launched lima on ARM64
host: 
`Darwin user-m1.local 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:27 PDT 2021; root:xnu-7195.141.2~5/RELEASE_ARM64_T8101 arm64`

linux: 
`Linux lima-default 5.11.0-31-generic #33-Ubuntu SMP Wed Aug 11 13:19:32 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux`

while launching command 

`lima nerdctl compose -f /Users/user/dev/project/docker-compose.yml up` i'm getting error: 

```
FATA[0001] no match for platform in manifest: not found
exit status 1
```

or docker-compose up directly from VM, getting this error when specified Platform tag in docker-compose file:

`standard_init_linux.go:228: exec user process caused: exec format error`

Same docker-compose file works directly from host, downloads and creates containers fine, just everything works incredibly slowly

**Comment by AkihiroSuda** [comment]
Probably your image does not support ARM

**Comment by AkihiroSuda** [comment]
Supporting running foreign arch images is discussed in https://github.com/containerd/nerdctl/issues/103 , so let me close this one

**Comment by pretendent0** [comment]
@AkihiroSuda Can't i use docker-compose inside lima and start containers in that way? Or lima doesn't allow this? Because in host  mac i can create same containers even image arch is different

**Comment by AkihiroSuda** [comment]
It's not an issue of lima nor `nerdctl compose up`.

Simply we don't have multi-arch `nerdctl pull` yet.
