### ISSUE TITLE
Question: network with predictible hostnames

### ISSUE THREAD

**Issue by vsoch** [lima-vm/lima#2017]
I'm bringing up multiple VMs, and adding them to the same user network:

```
limactl start --network=lima:user-v2 --name=flux-0 ./flux-usernetes.yaml
limactl start --network=lima:user-v2 --name=flux-1 ./flux-usernetes.yaml
```

Looking at the instructions here https://lima-vm.io/docs/config/network/#lima-user-v2-network that seems to be the last option. What I'm able to do is get the actual ip address from `ip a` and then update /etc/hosts of each, adding the hostnames:

```
192.168.104.6  lima-flux-0
192.168.104.7  lima-flux-1
```
And then my application can query for lima-flux-0 or lima-flux-1 and it's associated with an address. I'm wondering if there is a way to automate this, so I could ping lima-flux-0 and get that address without needing to modify /etc/hosts? Note that the hostname command returns the correct name in the VM, but I can't use that to ping another one (without the addition. Thank you!

**Comment by AkihiroSuda** [comment]
We should enhance the built-in DNS to support looking up hostnames.

A workaround would be to use mDNS, but I couldn't get it to work.
