### ISSUE TITLE
test-port-forwarding.pl: `Bad arg length for Socket::inet_ntoa, length is 0, should be 4`

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/lima#204]
test-port-forwarding.pl works on CI but does not work on my local environment (macOS 11.5)

```console
$ ./hack/test-example.sh examples/default.yaml 
TEST| [INFO] Validating "examples/default.yaml"
INFO[0000] "examples/default.yaml": OK                  
TEST| [INFO] Setup port forwarding rules for testing in "/Users/suda/lima-config-tmp/default.yaml"
Use of uninitialized value in subroutine entry at /Users/suda/gopath/src/github.com/lima-vm/lima/hack/test-port-forwarding.pl line 25.
Bad arg length for Socket::inet_ntoa, length is 0, should be 4 at /Users/suda/gopath/src/github.com/lima-vm/lima/hack/test-port-forwarding.pl line 25.

$ hostname
suda-mbp.local

$ which perl
/usr/local/bin/perl

$ perl --version

This is perl 5, version 34, subversion 0 (v5.34.0) built for darwin-thread-multi-2level

Copyright 1987-2021, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.
```

Lima v0.6.2

**Comment by AkihiroSuda** [comment]
@jandubois PTAL

**Comment by jandubois** [comment]
This means `gethostbyname` does not recognize the hostname.

First check the name returned by `hostname` iself:

```console
$ /usr/bin/perl -MSys::Hostname -e 'print hostname()'
mactop
```

This works for `gethostbyname()`:

```console
$ /usr/bin/perl -e 'print length gethostbyname("mactop")'
4
```

Now if I use the name `mactop.local` I get `undef` from `gethostbyname()` because the actual mDNS name for this machine is `mactop-2.local`:

```console
$ /usr/bin/perl -e 'print length gethostbyname("mactop.local")'
$ /usr/bin/perl -e 'print length gethostbyname("mactop-2.local")'
4
```

(`length(undef)` returns `undef` which prints as the empty string)

So maybe check with Preferences.app on the "Sharing" pane if your computer name matches you mDNS name. If it doesn't, then you shouldn't use the `.local` suffix on the name.

**Comment by AkihiroSuda** [comment]
> ```
> /usr/bin/perl -MSys::Hostname -e 'print hostname()'
> ```

```console
$ hostname
suda-mbp.local

$ /usr/bin/perl -MSys::Hostname -e 'print hostname()'
suda-mbp.local
```

> So maybe check with Preferences.app on the "Sharing" pane if your computer name matches you mDNS name. If it doesn't, then you shouldn't use the .local suffix on the name.

How to do so? Looks like I can't remove `.local` suffix

<img width="780" alt="image" src="https://user-images.githubusercontent.com/9248427/156721711-378ce376-23d3-4134-a110-a1ef8c1fce4a.png">

**Comment by jandubois** [comment]
> ... if your computer name matches you mDNS name

It seems to match, so I don't understand why `gethostbyname()` cannot lookup the address. It looks like mDNS is not working properly.

I've created #696 as a workaround; it should fall back to using `system_profiler` to determine the default address. This is already needed on the Github runners, which self-identify as `localhost` and are not using a proper hostname.
