### ISSUE TITLE
README graphic with transparent background isn't clear for GitHub's dark theme

### ISSUE THREAD

**Issue by bkane-msft** [lima-vm/lima#2041]
### Description

Hello! This is DEFINITELY a nitpick, but I noticed that the README has a couple of graphics containing black letters + transparent backgrounds.

These don't show well when I browse the README using GItHub's dark theme.

Example screenshot:

![image](https://github.com/lima-vm/lima/assets/92759008/09561f22-570b-45a8-bfc4-477d853753c0)

Consider adding a letter borders, or non-transparent backgrounds, or something else (I'm not great at graphic design...). Or if ya'll don't care, simply close this issue :D

**Comment by afbjorklund** [comment]
For the dark mode in Podman Desktop, I think they simply inverted the logo

**Comment by afbjorklund** [comment]
But it seems like GitHub have different dark modes ? Or at least different gray backgrounds...

![github-lima](https://github.com/lima-vm/lima/assets/10364051/f7b9288b-a085-4b5b-bcf8-74c021e4fe12)
