### ISSUE TITLE
limactl shell k3s kubectl command failed

### ISSUE THREAD

**Issue by zhaojizhuang** [lima-vm/lima#2094]
## Problem
Failed when use limaclt shell k3s kubectl get ns 

```shell
zjz:~$ limactl shell k3s kubectl get ns
WARN[0000] Unable to read /etc/rancher/k3s/k3s.yaml, please start server with --write-kubeconfig-mode to modify kube config permissions
error: error loading config file "/etc/rancher/k3s/k3s.yaml": open /etc/rancher/k3s/k3s.yaml: permission denied
```

For the mod in vm `lima-k3s` is `600`,while the user in mac is not `root`

```shell
zjz:~$ limactl shell k3s ls -al /etc/rancher/k3s/k3s.yaml
-rw------- 1 root root 2969 Dec 21 08:35 /etc/rancher/k3s/k3s.yaml
```

## Solution

I think we should change  `/etc/rancher/k3s/k3s.yaml`'s mod to `644`

with k3s install command

```shell
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --write-kubeconfig-mode 644" sh -
```

**Comment by afbjorklund** [comment]
You should use `sudo`

**Comment by jandubois** [comment]
> You should use `sudo kubectl`

That obviously works, but in e.g. the `docker-rootful` template we give the regular user access to the docker socket as well and don't require the user to use `sudo`. So one could make an argument for consistency here.

Are there reasons why we don't want to do this? Given that the user has already access to password-less `sudo`, this isn't a security boundary.

**Comment by jandubois** [comment]
> We can give the user the config instead of root like now, and change the templates... (k3s and k8s)

That's what #2095 is doing (well, it gives it to every user via `644` mode, but practically speaking it has the same effect). I'm just trying to understand if there are reasons why we wouldn't/shouldn't do that.

> Just that "sudo kubectl" is what is currently written and in the `kubectl.lima` wrapper

This would continue to work, so we should probably leave it unchanged for backwards compatibility with instances created by earlier Lima versions/templates.

**Comment by afbjorklund** [comment]
Just that we used `sudo nerdctl`, seemed logical to do the same for kubernetes

**Comment by jandubois** [comment]
> Just that we used `sudo nerdctl`, seemed logical to do the same for kubernetes

Yeah, but we don't do it for `docker`, even in rootful mode, which seems inconsistent.

I don't have any strong feelings either way; what do other @lima-vm/maintainers think?

**Comment by afbjorklund** [comment]
Dropping the sudo is an improvement, as long as we do it across the board (all three places).

cmd/kubectl.lima
examples/experimental/rke2.yaml
examples/k3s.yaml
examples/k8s.yaml
