### ISSUE TITLE
Remove  the support for `vde_vmnet` (Deprecated since Sep 2022, in favor of `socket_vmnet`)

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/lima#2096]
`vde_vmnet` has been deprecated since Lima v0.12.0 (Sep 2022), in favor of `socket_vmnet`:
- https://github.com/lima-vm/lima/pull/851

We can remove the support for `vde_vmnet` as soon as Rancher Desktop stops using it:
- https://github.com/rancher-sandbox/rancher-desktop/issues/6248

**Comment by AkihiroSuda** [comment]
@jandubois Are we ready for this?

**Comment by AkihiroSuda** [comment]
The CI job is being removed in:
- https://github.com/lima-vm/lima/pull/2310


For sake of deflaking the CI.

**Comment by jandubois** [comment]
I'm fine with removing `vde_vmnet` support completely.

It will still be accessible in Rancher Desktop 1.14, but that will be based on Lima 0.21.0.
Not sure if we get around to dropping the `vde_vmnet` code in time for that, but since we are not upgrading Lima beyond 0.21.0, it doesn't matter.
