### ISSUE TITLE
Allow to update the packages at boot

### ISSUE THREAD

**Issue by afbjorklund** [lima-vm/lima#2129]
### Description

It would be nice (as an option) if the VM started out fully updated, before it opened for logins.

That would allow you to start with for an instance an updated kernel, on systems like Fedora*.

\* that only make a new ISO every release, but have a lot of package updates inbetween those

The preferred solution would be to use an updated image for the template, if one is available.

----

https://cloudinit.readthedocs.io/en/stable/reference/examples.html#update-apt-database-on-first-boot

```yaml
#cloud-config

# Upgrade the instance on first boot
#
# Default: false
package_upgrade: true
```

EDIT: In Lima, every boot is the first boot

**Comment by jandubois** [comment]
> The next step would be to have an option to keep the packages updated after initial creation.

As I mentioned in https://github.com/lima-vm/lima/pull/2119#discussion_r1449220500 we are changing the instance id on each boot, so from cloud-init's point of view, each boot is a first boot.

I've just confirmed this with your PR and the default instance. Even on a reboot you get the package update output in `/var/log/cloud-init-output.log`:

```
Cloud-init v. 23.3.1-0ubuntu2 running 'modules:config' at Mon, 15 Jan 2024 18:57:33 +0000. Up 14.94 seconds.
Get:1 http://security.ubuntu.com/ubuntu mantic-security InRelease [109 kB]
[...]
Get:50 http://archive.ubuntu.com/ubuntu mantic-backports/multiverse amd64 c-n-f Metadata [116 B]
Fetched 29.8 MB in 6s (5109 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 70 not upgraded.
Cloud-init v. 23.3.1-0ubuntu2 running 'modules:final' at Mon, 15 Jan 2024 18:57:45 +0000. Up 27.06 seconds.
```

So enabling `upgrade_packages` will add another 15s or so to every boot, not just the first one. I think this is fine; but let's discuss if you disagree!

**Comment by afbjorklund** [comment]
I think that is OK, most of the index files should be cached since last run ?

**Comment by jandubois** [comment]
> I think that is OK, most of the index files should be cached since last run ?

They should, but it still took 15s. I did create and start the VM, stop it, and start it again, and the log extract above is from this second start, where everything should be cached. It still took almost 15s.

But that's why it is an option: so users can opt-in to always run with the latest updates, if they want to.
