### ISSUE TITLE
Add CLI command to generate launchd units for macOS hosts (systemd units for Linux hosts)

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/lima#2142]
It looks like launching `limactl start` via launchd is difficult and we have to let launchd start `limactl hostagent` directly.

The `limactl hostagent` command is still internal to Lima and has to be wrapped by a "public" CLI command.

The public command for generating the unit files can be like `limactl (create|edit|start) --autostart=<BOOL>`  .

- - -

ref:

> The method of invoking `limactl start docker` with `launchd` does not work.
> If `limactl start` starts `limactl hostagent` and terminates itself, `launchd` will detect the termination and terminate `limactl hostagent` and other processes in the same process group.
> Using `<key>AbandonProcessGroup</key><true/>` will prevent `limactl hostagent` from terminating by `launchd`, but will also prevent it from terminating on user logout.
> Therefore, I submitted this change because I thought it would be better to allow `launchd` to start and stop `limactl hostagent` directly.
>
>_Originally posted by @norio-nomura in https://github.com/lima-vm/lima/issues/2140#issuecomment-1892909533_

**Comment by roman-kiselenko** [comment]
I would like to work on this feature @AkihiroSuda 🙏

**Comment by jandubois** [comment]
> The public command for generating the unit files can be like `limactl (create|edit|start) --autostart=<BOOL>` .

We need to agree on a naming scheme for the launch agent filenames. I would suggest:

```
~/Library/LaunchAgents/io.lima-vm.autostart.$INSTANCE.plist
```

We also need to update `limactl delete` to make sure it removes the plist file (if it exists).

Also, I assume this will be initially just for macOS? The autostart mechanisms on Windows and Linux are completely different. We do have them implemented in Rancher Desktop though, so you can look up there what needs to be done, if you want to support this on all platforms.

**Comment by roman-kiselenko** [comment]
Thanks, fellas!

> if you want to support this on all platforms.

It's better to have the support of all platforms 🤔 
I understand the implementation for `macos` and `linux` and have a way to test it, but I'm not sure about `windows`. 

I've checked the implementation of [autostart](https://github.com/rancher-sandbox/rancher-desktop/tree/main/src/go/rdctl/pkg/autostart) in the Rancher Desktop, thanks for the tip @jandubois :pray: 

Should we support `sudo` and operate on `user/system` level?

Here is how I see it:

On `create/edit` command (this options wont stop instance creation if any errors occur):

1. By running `limactl create/edit --autostart=true` 
1. We render a template of `*.plist` file from go code and put to `$HOME/Library/LaunchAgents`
1. Load them (i.e. tell them to start at login) with `launchctl load $PATH_TO_LIST`

On `delete` command:

1. By running `limactl delete --autostart=true` (does `--autostart=true` needed here? AFAIU we can just cleanup without respecting the `--autostart` flag)
1. Unload them (i.e. tell them to not start at login) with `launchctl unload $PATH_TO_LIST`
1. Delete `*.plist` file `$HOME/Library/LaunchAgents`

The same routine works for `linux` and `$XDG_CONFIG_HOME/.config/systemd/user/lima.service`

In both cases to control the autostart items the `launchctl` and `systemctl --user` must be used.

BTW There is also a [`brew services`](https://docs.brew.sh/Manpage#services-subcommand) subcommand, but will work only if `lima` installed with `brew`.

cc @AkihiroSuda @norio-nomura @jandubois

**Comment by AkihiroSuda** [comment]
Thanks, SGTM

> Should we support sudo and operate on user/system level?

No, Lima currently only supports non-root users.

> By running limactl delete --autostart=true (does --autostart=true needed here? AFAIU we can just clean up without respecting the --autostart flag)

`--autostart` shouldn't be needed for `limactl delete`

**Comment by AkihiroSuda** [comment]
> ~/Library/LaunchAgents/io.lima-vm.autostart.$INSTANCE.plist

What should we do when `$INSTANCE` contains a dot (`.`) ?

**Comment by roman-kiselenko** [comment]
> > ~/Library/LaunchAgents/io.lima-vm.autostart.$INSTANCE.plist
> 
> What should we do when `$INSTANCE` contains a dot (`.`) ?


1. The `*.plist` filename match the `Label` key and [uniquely identifies the job to `launchd`](https://www.manpagez.com/man/5/launchd.plist/).
1. The `Label` key follows ["reverse domain" naming convention](https://en.wikipedia.org/wiki/Reverse_domain_name_notation)

Hence a dot `.` in filename is valid.
The `$INSTANCE` name doesn't have any kind of validation at least I don't find any. Maybe we should introduce minimal name instance validation at least to follow `"reverse domain" naming convention`

On the `linux` platform the name of [unit files also has requirements](https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html).

> The "unit name prefix" must consist of one or more valid characters (ASCII letters, digits, ":", "-", "_", ".", and "\"). The total length of the unit name including the suffix must not exceed 255 characters.

**Comment by jandubois** [comment]
> Maybe we should introduce minimal name instance validation at least to follow "reverse domain" naming convention

I would be fine with that, but it should only be enforced by `limactl create` for new instances. Existing instances need to continue to work. You just emit an error when the user tries to start them with the `--autostart=true` option.

Idle thought: should we have a feature to rename an instance?
