### ISSUE TITLE
nested virtualisation?

### ISSUE THREAD

**Issue by fire-ant** [lima-vm/lima#22]
QEMU supports nested virtualisation, any reason LIMA wouldn't also support that use case?

I know Multipass doesnt  (https://discourse.ubuntu.com/t/nested-virtualization-on-macos/19345) but -cpu host and -enable-kvm  should get us there and I would really love something that gives me Linux host with the capabilities to spin guests for Infrastructure-as-code type affairs.

**Comment by AkihiroSuda** [comment]
Lima totally depends on QEMU for CPU emulation, so it should work with Lima as well. (Feel free to open a PR if some additional configuration is needed for qemu)

**Comment by fire-ant** [comment]
Prompt response highly appreciated. Maybe I'm not interpreting the docs correctly but I don't see how to pass QEMU arcs/flags through on either command line or the yaml. Is there any example of this, or would replacing/concatenating flags to the the binary location be valid?

**Comment by AkihiroSuda** [comment]
QEMU doesn't seem to support enable nesting on macOS hosts.

We can revisit this issue later when QEMU supports it.

**Comment by fire-ant** [comment]
hmmm leaving this as the issue to resolve on the QEMU side. I assume it covers how it 'should' work, even if it doesnt - https://www.linux-kvm.org/page/Nested_Guests

**Comment by msgilligan** [comment]
Looks like macOS 15+ will support it on M3 and later:
https://developer.apple.com/documentation/virtualization/vzgenericplatformconfiguration/4360553-isnestedvirtualizationsupported?changes=latest_minor
