### ISSUE TITLE
Add support for forwarding UNIX sockets from the guest to the host

### ISSUE THREAD

**Issue by jandubois** [lima-vm/lima#221]
For example the docker port forwarding in #210 would be more robust if it would just forward the socket instead of letting docker connect via ssh. The latter is brittle because user names and keys all must resolve correctly for this to work.

See https://github.com/abiosoft/colima/blob/9adcf3c/colima#L151 for a mechanism that should be built into the host agent.

**Comment by abiosoft** [comment]
I suspect this should be relatively straightforward to implement. Is this in progress already? 
If no then I can give it a shot. Any pointers?

**Comment by AkihiroSuda** [comment]
- Do we want to scan `/proc/net/unix?` (No, in my opinion)
- Do we just want to add new fields like `guestUnix` and `hostUnix` to the existing top-level `portForwards` list? Or do we need a new top-level yaml field like `unixForwards?` (I prefer the former, but not a strong opinion)

https://github.com/lima-vm/lima/blob/df25c45939cebacb1a479f1d4ac4f44491e86871/pkg/limayaml/default.yaml#L144

**Comment by abiosoft** [comment]
> * Do we want to scan `/proc/net/unix` to automatically forward every socket? (No, in my opinion)

No for me as well.

> * Do we just want to add new fields like `guestUnix` and `hostUnix` to the existing top-level `portForwards` list? Or do we need a new top-level yaml field like `unixForwards?` (I prefer the former, but not a strong opinion)

I think it should be included in `portForwards`. 

1. In unix environments, ports and sockets are handled similarly. e.g. even `curl` can make requests to sockets.
2. Sockets can be forwarded to ports and vice versa. Having it under `portForwards` will accommodate such config.

**Comment by jandubois** [comment]
> I suspect this should be relatively straightforward to implement. Is this in progress already?
> If no then I can give it a shot. Any pointers?

Not in progress, and I personally wouldn't get around to it anytime soon either. So it would be awesome if you could implement this!

I'm agreeing with everybody else above (add it to `portForwarding`).

One thing I'm wondering though: can you forward a socket before it exist? If not, then we may still need some kind of polling. Still, we should only forward sockets explicitly configured in `lima.yaml` and nothing by default.

Oh, and one other question: do we need to `mkdir -p` the directory of the hostsocket?

PS: @abiosoft Nice work on `colima`!  I always enjoy a nicely written shell script.

**Comment by abiosoft** [comment]
> Not in progress, and I personally wouldn't get around to it anytime soon either. So it would be awesome if you could implement this!

Okay, cool. I should give this a shot before the end of the week.


> One thing I'm wondering though: can you forward a socket before it exist? If not, then we may still need some kind of polling. Still, we should only forward sockets explicitly configured in `lima.yaml` and nothing by default.

I am not sure in general but as for ssh forwarding, the file does not need to exist. Connections will fail obviously but it is fine. 
It's like a reverse-proxy returning a 502 for a failed backend, and things go back to normal when the server is back up (or file exists and responding to requests in this case).


> Oh, and one other question: do we need to `mkdir -p` the directory of the hostsocket?

Yes. The directory needs to exist. However, the file must not exist and would be created by ssh.


> PS: @abiosoft Nice work on `colima`! I always enjoy a nicely written shell script.

Thanks :)

**Comment by mmornati** [comment]
> * Do we want to scan `/proc/net/unix` to automatically forward every socket? (No, in my opinion)
> * Do we just want to add new fields like `guestUnix` and `hostUnix` to the existing top-level `portForwards` list? Or do we need a new top-level yaml field like `unixForwards?` (I prefer the former, but not a strong opinion)
> 
> https://github.com/lima-vm/lima/blob/df25c45939cebacb1a479f1d4ac4f44491e86871/pkg/limayaml/default.yaml#L144

Completely agreed. I was looking for this and I think a `unixForward` configuration can let much more latitude and it should event prevent custom configuration for all host machine applications already configured to use the "standard socket" (example with Docker apps looking for `/var/run/docker.sock`).

**Comment by jandubois** [comment]
> Okay, cool. I should give this a shot before the end of the week.

@abiosoft Did you get a chance to start work on this already? If not, then I may work on it next week.

But if you already have something, could you push a draft-PR so we can collaborate?

**Comment by abiosoft** [comment]
> @abiosoft Did you get a chance to start work on this already? If not, then I may work on it next week.
> 
> But if you already have something, could you push a draft-PR so we can collaborate?

@jandubois I have not started yet, still busy with other things at the moment.

**Comment by jandubois** [comment]
Thanks for the update @abiosoft; I'll look into it next week then.

**Comment by abiosoft** [comment]
@jandubois were you able to start working on this?

**Comment by jandubois** [comment]
@abiosoft Please let me know if you have started on this; otherwise I plan to work on it starting Wednesday.
