### ISSUE TITLE
Getting some warnings when shutting down an instance using grpc

### ISSUE THREAD

**Issue by afbjorklund** [lima-vm/lima#2216]
### Description

Sometimes there is a warning issued:

```
INFO[0000] [hostagent] Received SIGINT, shutting down the host agent 
INFO[0000] [hostagent] Shutting down the host agent     
INFO[0000] [hostagent] Stopping forwarding "/run/lima-guestagent.sock" (guest) to "/home/anders/.lima/default/ga.sock" (host) 
WARN[0000] [hostagent] connection to the guest agent was closed unexpectedlyrpc error: code = Canceled desc = context canceled 
```

Maybe it now needs to stop the guest agent watch, before killing the hostagent ?

**Comment by afbjorklund** [comment]
I'm still seeing some "weird" warnings, when running against an instance with the old lima-guestagent (without rpc)

`WARN[0006] [hostagent] guest agent events closed unexpectedlyrpc error: code = Unavailable desc = connection error: desc = "error reading server preface: http2: frame too large" `

But upgrading the lima-guestagent and restarting it makes them go away, so it should not be an issue for new installs...

**Comment by balajiv113** [comment]
@afbjorklund is this also happening on the latest master ??

**Comment by balajiv113** [comment]
> when running against an instance with the old lima-guestagent

Shouldn't guestagent get auto upgraded when running against new lima instance ??

**Comment by afbjorklund** [comment]
> Shouldn't guestagent get auto upgraded when running against new lima instance ??

Yes, doing a `stop` and `start` fixes it. Just that those error messages are a bit scary.
