### ISSUE TITLE
Generated `user-data` is failing cloud-config schema validation

### ISSUE THREAD

**Issue by afbjorklund** [lima-vm/lima#2265]
### Description

There are some reports in the log, about the user-data failing validation.

`[WARNING]: Invalid cloud-config provided: Please run 'sudo cloud-init schema --system' to see the schema errors.`

We should probably run yaml and jsonschema validation, on the `user-data`?

But at least fix the syntax errors, and try to conform to the cloud-init schema...

**Comment by afbjorklund** [comment]
Note that changing to "ssh_authorized_keys" will actually **fail** some alternative cloud-init implementations...

Such as lima-init, or tinycloudinit. They have "ssh-authorized-keys" hardcoded, in their alternate parsers (awk)

**Comment by jandubois** [comment]
> Such as lima-init

We can easily fix `lima-init`, but don't know about `tinycloudinit`. I did the same already for `ca-certs` and `ca_certs`: https://github.com/lima-vm/alpine-lima/blob/5a09f68c35124ba6049ec15fd972991c445856f7/lima-init.sh#L129-L130

```
awk -f- "${LIMA_CIDATA_MNT}"/user-data <<'EOF' > ${LIMA_CA_CERTS}
# Lima currently uses "ca-certs", which is deprecated and should be "ca_certs"
/^ca.certs:/ {
…
```

**Comment by afbjorklund** [comment]
The tinycloudinit was just a hack that I made when playing with tinycorelinux, it is a similar awk script (with similar fix)

**Comment by afbjorklund** [comment]
https://raw.githubusercontent.com/canonical/cloud-init/main/cloudinit/config/schemas/schema-cloud-config-v1.json

Example validation with `jv`

```
$ jv https://raw.githubusercontent.com/canonical/cloud-init/main/cloudinit/config/schemas/schema-cloud-config-v1.json cloud-config.yaml 
[I#] [S#] doesn't validate with https://raw.githubusercontent.com/canonical/cloud-init/main/cloudinit/config/schemas/schema-cloud-config-v1.json#
  [I#] [S#/allOf/8] allOf failed
    [I#] [S#/allOf/8/$ref] doesn't validate with '/$defs/cc_ca_certs'
      [I#/ca_certs] [S#/$defs/cc_ca_certs/properties/ca_certs/$ref] doesn't validate with '/$defs/ca_certs.properties'
        [I#/ca_certs/trusted] [S#/$defs/ca_certs.properties/properties/trusted/type] expected array, but got null
  [I#] [S#/allOf/49] allOf failed
    [I#] [S#/allOf/49/$ref] doesn't validate with '/$defs/cc_users_groups'
      [I#/users/0] [S#/$defs/cc_users_groups/properties/users/items/oneOf] oneOf failed
        [I#/users/0] [S#/$defs/cc_users_groups/properties/users/items/oneOf/0/type] expected string, but got object
        [I#/users/0] [S#/$defs/cc_users_groups/properties/users/items/oneOf/1/type] expected array, but got object
        [I#/users/0] [S#/$defs/cc_users_groups/properties/users/items/oneOf/2/$ref] doesn't validate with '/$defs/users_groups.user'
          [I#/users/0] [S#/$defs/users_groups.user/additionalProperties] additionalProperties 'ssh-authorized-keys' not allowed
```

**Comment by afbjorklund** [comment]
Checking for deprecated and changed fields actually requires both enabling "annotations" and patching jsonschema...

**Comment by afbjorklund** [comment]
As mentioned in the PRs, the revision v1 (or `main`) of this jsonschema is actually quite a lot of versions.

And there are even more variants of cloud-config, if you count the years before the jsonschema existed...

So we should **not** change the type of these, just because they are deprecated (or outright missing):

`users.uid`, `users.ssh-authorized-keys` - since it _breaks_ stuff, and some lima distributions stop working

**Comment by afbjorklund** [comment]
Related issue:

* #2128

**Comment by afbjorklund** [comment]
The lima generated cloud-config.yaml now passes validation with `cloud-init schema`,
after the ssh-authorized keys was deprecated in schema  (24.2~1g370e680c-0ubuntu1)
