### ISSUE TITLE
Lima (0.21.0) Alma9 Linux VM Locking Up/Freezing on Max OS 14.4.1

### ISSUE THREAD

**Issue by shefmarkh** [lima-vm/lima#2307]
### Description

Hello,

For many weeks I have been experiencing seemingly random freezing up of a Linux Alma9 VM on an M1 MacBook Air.

For example I can see it is listed as running:

limactl list       
NAME     STATUS     SSH                VMTYPE    ARCH       CPUS    MEMORY    DISK      DIR
Alma9    Running    127.0.0.1:52860    qemu      aarch64    4       4GiB      100GiB    ~/.lima/Alma9

whilst open terminals have frozen, "limactl shell Alma9" does nothing and just returns me to the command line outside the VM with no errors and ssh connections are refused:

 ssh lima-Alma9
ssh: connect to host 127.0.0.1 port 61967: Connection refused

Stopping and starting the VM solves the issue, but I hope there would be a better solution that would prevent this.

The host is running Mac OS 14.4.1. I have Lima version 0.21.0.

I tried looking in some of the log files in my .lima area and the only thing I think appeared roughly the last time but one the freeze happened is this:

{"error":"exit status 255","level":"warning","msg":"Failed to set up forward from \"/run/lima-guestagent.sock\" (guest) to \"/Users/markhodgkinson/.lima/Alma9/ga.sock\" (host)","time":"2024-04-30T10:27:10+01:00"}
{"error":"rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial unix /Users/markhodgkinson/.lima/Alma9/ga.sock: connect: no such file or directory\"","level":"warning","msg":"guest agent events closed unexpectedly","time":"2024-04-30T10:27:10+01:00"}

which is repeated over and over in the log. Then I a restarted VM freeze again and don't see the above. The last errors are:

{"level":"debug","msg":"stdout=\"\", stderr=\"+ timeout 30s bash -c 'until sudo diff -q /run/lima-boot-done /mnt/lima-cidata/meta-data 2\u003e/dev/null; do sleep 3; done'\\n\", err=\u003cnil\u003e","time":"2024-04-30T11:07:06+01:00"}
{"level":"info","msg":"The final requirement 1 of 1 is satisfied","time":"2024-04-30T11:07:06+01:00"}
{"error":"lookup lima-Alma9.: no such host","level":"debug","msg":"handleQuery lookup IP failed","time":"2024-04-30T11:10:13+01:00"}

 Though there might be other things to look for, any advice on how to diagnose what the problem is would be very welcome.

Please let me know any other diagnostic information that I should provide to help.

Thanks,

Mark

**Comment by AkihiroSuda** [comment]
Please check `serial*.log` to see if there is any error.
`limactl start --video` may show some error too.

**Comment by AkihiroSuda** [comment]
`limactl create --vm-type=vz` may change the situation

**Comment by shefmarkh** [comment]
thanks, am trying a new VM with vz. If I don't see the problem after a few weeks I will close this report.

**Comment by shefmarkh** [comment]
Seems stable with vz.
