### ISSUE TITLE
 Waiting for the essential requirement 1 of 4: "ssh"

### ISSUE THREAD

**Issue by asdfghjkl403622** [lima-vm/lima#235]
tried to run lima, got this error. spammed the same text over and over again. saw the issue for the last time this happened and decided to post this. 
[serial.log](https://github.com/lima-vm/lima/files/7146093/serial.log)

**Comment by jandubois** [comment]
Your log looks like you have an SSL public key in your `~/.ssh` directory (like https://github.com/lima-vm/lima/issues/104#issuecomment-913943944). This should be fixed by #219.

**Comment by asdfghjkl403622** [comment]
just tried again, didn't work. same error on new computer with fresh install

**Comment by jandubois** [comment]
You seem to have a fully numeric username on the Mac. That does not work properly on Linux, so we are going to map it to a `lima` fallback username in the next release: https://github.com/lima-vm/lima/pull/243
