### ISSUE TITLE
v1.0 roadmap: alpine: switch away from ISO to qcow2

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/lima#2366]
- https://github.com/lima-vm/lima/pull/2360

In Lima v1.0, the current ISO-based `alpine` template should be ditched away, and the `alpine-image` (qcow2) template should take over the name of `alpine`

**Comment by jandubois** [comment]
I don't know what you mean by "ditched away", but I thought we had agreement that we would continue to support booting Lima instances from ISO/ramdisk[^1]. So we would simply rename templates:

[^1]: I can't find the discussion right now; may have been on Slack. I remember that @afbjorklund also argued for keeping the ISO support.

1. `alpine` → `alpine-iso`
2. `alpine-image` → `alpine`

Are you planning anything else?

**Comment by AkihiroSuda** [comment]
I was thinking that we may remove, or at least deprecate, the ISO variant for sake of simplification

**Comment by jandubois** [comment]
> I was thinking that we may remove, or at least deprecate, the ISO variant for sake of simplification

We already did: #2236.

I somewhat strongly oppose the removal of the ISO support. And several of the "stability" issues in the past have been caused by improper "fixes" for the benefit of colima, so that should no longer be an issue now that colima no longer uses Alpine.

**Comment by afbjorklund** [comment]
I think that the ISO/"LiveCD" support is a feature, and something that was also used by Docker Machine

**Comment by AkihiroSuda** [comment]
> I somewhat strongly oppose the removal of the ISO support. 


Is deprecation fine?

**Comment by afbjorklund** [comment]
> Is deprecation fine?

I think switching the default would be enough, unless you want to drop lima-alpine from "upstream" (lima org)?

Originally my suggestion was to provide multiple "editions", but I also don't know who would maintain them...

But don't think it's deprecated?

Possibly downstream-only
