### ISSUE TITLE
Allow running start directly from an URL

### ISSUE THREAD

**Issue by afbjorklund** [lima-vm/lima#237]
It would be neat if you could start from an URL directly:

`limactl start https://raw.githubusercontent.com/lima-vm/lima/master/examples/podman.yaml`

USAGE:
   limactl start [command options] NAME|FILE.yaml

It's just a `curl` command away, but still an extra step to do.

For the paranoid, might want to look at embedding signing ?

**Comment by afbjorklund** [comment]
Here is an example of signing of XML, can probably be adopted for YAML ?

https://docs.0install.net/specifications/feed/#digital-signatures

Basically adding the extra signature as an extra document or something...

So that it is still a regular text file just can be verified automatically

**Comment by jandubois** [comment]
> It would be neat if you could start from an URL directly:

👍 
 
> For the paranoid, might want to look at embedding signing ?

I think this should be strictly optional; the signing support can be added later by contribution from those extra-paranoids... 😄 

Most people publishing config files will not have a proper signing certificate for cost reasons. And implementation gets tricky when you have to deal with certificate revocation etc.

IMO, using GPG signing has marginal utility unless the config is published by somebody in your web of trust.

Anyways, my point is: Lacking signing functionality should not block accepting URL support.

**Comment by afbjorklund** [comment]
Just thought I would mention it, since the comment is likely to come - like with all [curlpipesh](https://curlpipesh.tumblr.com/)

**Comment by afbjorklund** [comment]
Some kind of "shortnames" would also be neat, but it's currently a mess for container images.

It always comes back to the "who owns the app store", which is why using domains is "better"

**Comment by jandubois** [comment]
> Just thought I would mention it, since the comment is likely to come - like with all [curlpipesh](https://curlpipesh.tumblr.com/)

Yes, it does, but if you are willing to download and run binaries from Github release page, you already accept the same risks (which is what you do when you use `brew tap`, or `brew cask`).

**Comment by afbjorklund** [comment]
For some reason, we went from signed, checksummed and compressed packages over to random files on GitHub.

**Comment by jandubois** [comment]
> Some kind of "shortnames" would also be neat, but it's currently a mess for container images.

I was thinking about using "shortnames" as a shortcut to use the bundled configurations installed under /usr/local/share/doc/lima/examples.

This could be extended to include e.g. `~/.lima/_templates` or similar.

> It always comes back to the "who owns the app store", which is why using domains is "better"

I agree. That's why I think shortnames should be reserved for configurations that are either bundled with lima itself, or created/installed by the user locally. There should be no privileged "app store" (like docker hub).

**Comment by afbjorklund** [comment]
Will try to add my own distribution as well, just need to add some support for cloud-init first.

**Comment by afbjorklund** [comment]
WSL has an App Store, though ?

**Comment by jandubois** [comment]
> WSL has an App Store, though ?

IDK, but Windows has one, and you can install WSL distros with it.

Not sure how this relates to Lima though. I think everyone is free to create their own "app store" of Lima configurations (who could stop them).

IMO Lima should just not have special internal logic that prefers one external store over any others (except potentially the bundled example files, if you want to call that an "app store"). But again, everyone is free to copy their own examples to `/usr/local/share/doc/lima/examples` to get the same benefit (once/if we provide shortname access to it).

**Comment by afbjorklund** [comment]
I think running from an URL would be quite enough for this issue.

If you want an enhancement to the YAML format itself, I would suggest adding an icon and description text.
That would allow the aforementioned external store to be able to present the links more nicely, if provided...

My reference here is Zero Install, and the https://apps.0install.net

**Comment by jandubois** [comment]
> I think running from an URL would be quite enough for this issue.

👍 I think that is all that Lima needs.

> If you want an enhancement to the YAML format itself, I would suggest adding an icon and description text.
> That would allow the aforementioned external store to be able to present the links more nicely, if provided...

I think it is up to the external store how to represent the links, and how to manage the metadata. It could add some custom keys to the `lima.yaml` file (as long as they don't conflict), or keep metadata in a separate file. We shouldn't have to worry or care about that at all on the Lima side.

**Comment by afbjorklund** [comment]
Yes, adding signing and metadata are each separate suggestions I guess...
