### ISSUE TITLE
Unable to use x86_64 emulation with rosetta

### ISSUE THREAD

**Issue by ppelisset** [lima-vm/lima#2371]
First of all, I would like to thank the developers for this amazing tool.

As explained in the documentation here (https://lima-vm.io/docs/config/multi-arch/#fast-mode-2-rosetta-intel-containers-on-arm-vm-on-arm-hostfast-mode-2), I am trying to run a Debian 11 x86_64 machine on a Mac M3. I correctly launch limactl with the vm-type option set to vz and the rosetta option, but I get a fatal error because the architecture is supposed to be aarch64.

```
$ limactl start --name=debian template://debian-11 --vm-type=vz --rosetta --arch=x86_64
WARN[0000] `--rosetta` is experimental                  
? Creating an instance "debian" Open an editor to review or modify the current configuration
FATA[0007] the YAML is invalid, saved the buffer as "lima.REJECTED.yaml": field `arch` must be "aarch64" for VZ; got "x86_64" 
```

I am not sure if this is a bug or if the documentation is not up to date.

Thank you in advance for any help you can provide.

**Comment by jandubois** [comment]
You should not specify the `--arch=x86_64` option (and the documentation doesn't specify this).

The `--rosetta` option tells Lima to enable Rosetta inside the VM, which allows it to run `x86_64` containers inside the `aarch64` VM.

If you want to run the VM itself in `x86_64` mode, then you need to follow the `slow mode` documentation. It will only work with QEMU and not VZ emulation/Rosetta, and will be very slow.

**Comment by ppelisset** [comment]
Okay, thank you very much for your response. I had misunderstood the documentation. Sorry for the inconvenience

**Comment by george-pippos** [comment]
Sorry, I realise this is closed but are there any plans to support running a lima VM with vz as the backend so that rosetta can be used to run the x86 binaries at a system level? This would be much better performance-wise on Apple silicon macs

**Comment by afbjorklund** [comment]
What do you mean with "system level"? Rosetta can run your legacy x86 containers, it just cannot emulate the OS.
