### ISSUE TITLE
Old versions of cloud-init might end up with invalid sudoers

### ISSUE THREAD

**Issue by afbjorklund** [lima-vm/lima#2397]
### Description

The instance won't come up, due to inserting duplicate entries and NUL bytes into sudoers...

This is not lima's fault, but maybe there could be some cleanup in the boot scripts to recover?

Since part of start requires `sudo`.

**Comment by afbjorklund** [comment]
* https://github.com/canonical/cloud-init/issues/4048

Race condition corrupting the file is not mentioned separately, but seen with Ubuntu 16.04

**Comment by jandubois** [comment]
What do you suggest, something like this:

```bash
# cloud-init may end up writing an invalid sudoer file?
if [ -f /usr/local/etc/sudoers.d/90-cloud-init-users ]; then
    echo "(ALL) NOPASSWD: ALL" >/usr/local/etc/sudoers.d/90-cloud-init-users
fi
```

And then have a comment in `user-data` that explains that the setting there is essentially ignored, and any changes must be duplicated in the boot script?

Personally I'm not too keen to put hacks like this into Lima unless it affects more recent OS releases as well. Not sure where to draw the line, but 16.04 seems very obsolete; I would think even 18.04 is borderline.

**Comment by jandubois** [comment]
Couldn't this just be done in a system provisioning script in a template for the `16.04` instance? If it can't, then isn't it too late to do it in the boot scripts too, which run immediately before the provisioning scripts?

**Comment by afbjorklund** [comment]
I think it was more of reports of various things that happened when we tried to install Kubernetes and friends from 8-10 years ago

Most of it has been fixed in newer releases... The workaround for this corruption was to use `docker` (since `sudo` was broken)
