### ISSUE TITLE
Cross-compiler for building "darwin" target

### ISSUE THREAD

**Issue by afbjorklund** [lima-vm/lima#2468]
### Description

It would be nice to be able to build _all_ targets, before having it fail in CI on a VM

Something like https://github.com/neilotoole/xcgo and use a container builder?

Main issue is that `github.com/Code-Hex/vz/v3` doesn't build (cgo).

Not sure if darwin is still open enough, or if it would need a mock?

----

i.e. trying to build with `GOOS=darwin`, from a Linux host

```
# github.com/Code-Hex/vz/v3
../go/pkg/mod/github.com/!code-!hex/vz/v3@v3.1.0/virtualmachinestate_string.go:11:8: undefined: VirtualMachineStateStopped
../go/pkg/mod/github.com/!code-!hex/vz/v3@v3.1.0/virtualmachinestate_string.go:12:8: undefined: VirtualMachineStateRunning
../go/pkg/mod/github.com/!code-!hex/vz/v3@v3.1.0/virtualmachinestate_string.go:13:8: undefined: VirtualMachineStatePaused
../go/pkg/mod/github.com/!code-!hex/vz/v3@v3.1.0/virtualmachinestate_string.go:14:8: undefined: VirtualMachineStateError
../go/pkg/mod/github.com/!code-!hex/vz/v3@v3.1.0/virtualmachinestate_string.go:15:8: undefined: VirtualMachineStateStarting
../go/pkg/mod/github.com/!code-!hex/vz/v3@v3.1.0/virtualmachinestate_string.go:16:8: undefined: VirtualMachineStatePausing
../go/pkg/mod/github.com/!code-!hex/vz/v3@v3.1.0/virtualmachinestate_string.go:17:8: undefined: VirtualMachineStateResuming
../go/pkg/mod/github.com/!code-!hex/vz/v3@v3.1.0/virtualmachinestate_string.go:18:8: undefined: VirtualMachineStateStopping
../go/pkg/mod/github.com/!code-!hex/vz/v3@v3.1.0/virtualmachinestate_string.go:19:8: undefined: VirtualMachineStateSaving
../go/pkg/mod/github.com/!code-!hex/vz/v3@v3.1.0/virtualmachinestate_string.go:27:9: undefined: VirtualMachineState
../go/pkg/mod/github.com/!code-!hex/vz/v3@v3.1.0/virtualmachinestate_string.go:19:8: too many errors
```

Being able to run unit tests  (with [binfmt_misc](https://en.wikipedia.org/wiki/Binfmt_misc)) would be nice.

i.e. similar to current `GOOS=windows` support (as in 8028e500719d746f38712e4cf5e63144ab2f7bec)

Integration and release tests still need hardware, of course.

**Comment by afbjorklund** [comment]
https://github.com/tpoechtrager/osxcross

**Comment by afbjorklund** [comment]
This seems to be what I want, for running the unit tests (similar to `wine` for windows):

https://www.darlinghq.org/

```console
~ $ uname
Linux
~ $ darling shell
Darling [~]$ uname
Darwin
```

It doesn't have to be perfect.

**Comment by AkihiroSuda** [comment]
This seems challenging in both technological and legal aspects.
It is unlikely that we can work on this.😢

**Comment by afbjorklund** [comment]
The legal was _supposed_ to be covered, if not it should be avoided for sure.

> We only directly use those parts of Darwin that are released as fully free software.

But, like Wine, I don't think it is something that is needed upstream.
If the user have such an environment already, they can "just use it"...
If not, they would have to remote to a real Windows or Darwin machine.

Also, for testing purposes the `no_vz` flag avoided most of the build issues.

**Comment by afbjorklund** [comment]
The cgo compilation failed, when trying to run `cc -E -dM` to get some macro definitions:

clang: error: argument unused during compilation: '-arch x86_64' [-Werror,-Wunused-command-line-argument]

That is, there was no actual code being compiled but it wanted to get a enum value...

```go
	FSEventsInodeMetaMod          = 0x00400
```
