### ISSUE TITLE
Shell freezes when df -h is issued

### ISSUE THREAD

**Issue by tewarid** [lima-vm/lima#250]
A `lima` shell on an Intel macOS 11.5.2 freezes when I run `df -h`. Trying to `kill -9` df on another shell doesn't work.

**Comment by AkihiroSuda** [comment]
This was a regression in v0.6.1, and should have been fixed in v0.6.3.

Please try Lima v0.6.3 or newer.

**Comment by tewarid** [comment]
I upgraded to 0.6.4 via `brew upgrade lima`, restarted the instance, and was able to issue `df -h` successfully. Thanks.
