### ISSUE TITLE
I wrote a xbar plugin for limactl

### ISSUE THREAD

**Issue by unixorn** [lima-vm/lima#253]
I wrote an [xbar](https://xbarapp.com/) plugin script for `limactl` - it shows your lima VMs in a dropdown menu from xbar and lets you start or stop the individual lima VMs.

I don't see a section in the readme for extra tooling around lima, is it ok if I add one and include a link to [lima-xbar-plugin](https://github.com/unixorn/lima-xbar-plugin)?

**Comment by AkihiroSuda** [comment]
Thanks, PR is welcome around here https://github.com/lima-vm/lima/tree/v0.6.4#adopters (Maybe s/Adopters/Relevant projects/)
