### ISSUE TITLE
Figure out why archlinux CI is broken

### ISSUE THREAD

**Issue by jandubois** [lima-vm/lima#2538]
Running the tests against `archlinux` has always been brittle, but recently they stopped working completely.

They always fail with something like this:

```
++ cat /home/runner/lima-container-engine-test-tmp/random
+ expected=random-content-17742
++ limactl shell archlinux nerdctl run --rm -v /home/runner/lima-container-engine-test-tmp/random:/mnt/foo ghcr.io/containerd/alpine:3.14.0 cat /mnt/foo
time="2024-08-06T05:38:05Z" level=warning msg="treating lima version \"7831a10\" from \"/home/runner/.lima/archlinux/lima-version\" as very latest release"
time="2024-08-06T05:38:05Z" level=fatal msg="failed to get unprivileged mount flags for \"/home/runner/lima-container-engine-test-tmp/random\": stat /home/runner/lima-container-engine-test-tmp/random: no such file or directory"
+ got=
```

The error is reported from `nerdctl`: https://github.com/containerd/nerdctl/blob/1d9d22c4ce9fd9ada1c4e3fcd3143fd7caeb794e/pkg/mountutil/mountutil.go#L152-L158

I first thought that maybe the newly created file on the host was not yet visible inside the guest, but that didn't turn out to be the case. Even retrying every 5 seconds for almost a minute didn't change things.

Then I found that I can `stat` the file, but not `cat` it:

```
+ limactl shell archlinux stat /home/runner/lima-container-engine-test-tmp/random
  File: /home/runner/lima-container-engine-test-tmp/random
  Size: 21        	Blocks: 8          IO Block: 131072 regular file
Device: 0,68	Inode: 621037      Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1001/  runner)   Gid: (  127/ UNKNOWN)
Access: 2024-08-06 21:52:43.642758269 +0000
Modify: 2024-08-06 21:52:43.642758269 +0000
Change: 2024-08-06 21:52:43.642758269 +0000
 Birth: -
+ limactl shell archlinux cat /home/runner/lima-container-engine-test-tmp/random
cat: /home/runner/lima-container-engine-test-tmp/random: No such file or directory
```

I have no idea how this can happen.

I cannot reproduce any of this locally on macOS. I have not tried yet to reproduce it on a Linux host.

Until somebody figures it out we are going to disable `archlinux` CI.

**Comment by AkihiroSuda** [comment]
Seems a regression on archlinux side
- https://github.com/lima-vm/lima/pull/2524

**Comment by AkihiroSuda** [comment]
The issue seems reproducible on Ubuntu 24.04 amd64 with QEMU emulator version 8.2.2 (Debian 1:8.2.2+ds-0ubuntu1).
Not reproducible on macOS 14 with QEMU 9.0.2.
