### ISSUE TITLE
Replace al.essio.dev/pkg/shellescape

### ISSUE THREAD

**Issue by jandubois** [lima-vm/lima#2564]
We may consider removing this dependency in a follow-up PR

_Originally posted by @AkihiroSuda in https://github.com/lima-vm/lima/issues/2546#issuecomment-2283919801_

**Comment by afbjorklund** [comment]
There was not actually anything _wrong_ with it, we were just annoyed with the vanity domain...

```
go: downloading github.com/alessio/shellescape v1.5.0
go: github.com/alessio/shellescape@v1.5.0 requires github.com/alessio/shellescape@v1.5.0: parsing go.mod:
	module declares its path as: al.essio.dev/pkg/shellescape
	        but was required as: github.com/alessio/shellescape
```

The only changes were in the CLI and the tests, there was actionally **no** code changes to the module.

github.com/alessio/shellescape v1.4.2 -> al.essio.dev/pkg/shellescape v1.5.0

Previously it was called "gopkg.in/alessio/shellescape.v1", that was annoying too.

**Comment by afbjorklund** [comment]
There are several other vanity domains, so I'm not sure this one needs any special treatment?

```
	al.essio.dev/pkg/shellescape v1.5.0
	gopkg.in/evanphx/json-patch.v4 v4.12.0 // indirect
	gopkg.in/inf.v0 v0.9.1 // indirect
	gopkg.in/op/go-logging.v1 v1.0.0-20160211212156-b2cb9fa56473
	gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7 // indirect
	gopkg.in/yaml.v2 v2.4.0 // indirect
	gopkg.in/yaml.v3 v3.0.1
	gotest.tools/v3 v3.5.1
	go.uber.org/atomic v1.7.0 // indirect
	go.uber.org/multierr v1.7.0 // indirect
	gvisor.dev/gvisor v0.0.0-20231023213702-2691a8f9b1cf // indirect
	inet.af/tcpproxy v0.0.0-20221017015627-91f861402626
	k8s.io/apimachinery v0.31.0
	k8s.io/api v0.31.0
	k8s.io/client-go v0.31.0
	k8s.io/klog/v2 v2.130.1 // indirect
	k8s.io/kube-openapi v0.0.0-20240228011516-70dd3763d340 // indirect
	k8s.io/utils v0.0.0-20240711033017-18e509b52bc8 // indirect
	sigs.k8s.io/json v0.0.0-20221116044647-bc3834ca7abd // indirect
	sigs.k8s.io/structured-merge-diff/v4 v4.4.1 // indirect
	sigs.k8s.io/yaml v1.4.0 // indirect
```

**Comment by jandubois** [comment]
> There are several other vanity domains, so I'm not sure this one needs any special treatment?

I'm fine with closing this. I only created the issue when I came across the comment in an already closed PR while working through my email backlog after my travels, and wanted to make sure it didn't get lost.

**Comment by afbjorklund** [comment]
Well it did break the upgrade script when it happened, but hopefully that won't happen again soon...

* https://github.com/lima-vm/lima/issues/2545
