### ISSUE TITLE
Update the openSUSE distributions

### ISSUE THREAD

**Issue by afbjorklund** [lima-vm/lima#2611]
### Description

I noticed as I was watching an openSUSE presentations, that the distributions have been updated...

* https://events.opensuse.org/conferences/oSC24/program/proposals/4411

* https://media.ccc.de/v/4411-we-re-all-grown-up-opensuse-is-not-suse

So made some updates, to fix the "Leap" and the "Tumbleweed" distributions to their current state.

1. Renamed "opensuse" (symlink) to "opensuse-leap"

2. Added aarch64 version of "opensuse-tumbleweed"

**Comment by afbjorklund** [comment]
Added the new logos to the Lima GUI, as well:

https://github.com/afbjorklund/lima-gui/commit/33ff5ba758da48b9ed8f9d02340cee97aa7484ce

https://en.opensuse.org/Logocontest

**Comment by jandubois** [comment]
Unrelated to this issue, just FYI: Lima does not currently work on openSUSE as a host because qemu-ovmf has been broken: https://bugzilla.suse.com/show_bug.cgi?id=1230291
