### ISSUE TITLE
go.mod has broken references

### ISSUE THREAD

**Issue by moenodedev** [lima-vm/lima#2631]
### Description

replace inet.af/tcpproxy with github.com/inetaf/tcpproxy
https://github.com/inetaf/tcpproxy/issues/39

replace github.com/containers/gvisor-tap-vsock 2691a8f9b1cf with latest release
https://github.com/containers/gvisor-tap-vsock/pull/397

**Comment by afbjorklund** [comment]
Sounds like two different issues? But the first one is exactly _why_ we dislike vanity domains...

* https://github.com/lima-vm/lima/issues/2564

**Comment by AkihiroSuda** [comment]
- https://github.com/lima-vm/lima/pull/2634
