### ISSUE TITLE
limactl sudoers needs to verify the network config before writing the sudoers file

### ISSUE THREAD

**Issue by jandubois** [lima-vm/lima#2663]
Right now the check for secure paths only happens at runtime.

But if the user generated a sudoers file to insecure binaries, then these commands could still be run by any other process that doesn't validate the binary location.

We need to protect the user from accidentally creating a sudoers file that would allow password-less sudo access to e.g. world-writable file.

**Comment by avoidik** [comment]
in my opinion, this verification should be relaxed and left as a recommendation for advanced use-cases, assuming that a user knows what they're doing and has awareness regarding security implications (messing with sudoers mechanis implies that you already have enough trust to do so)
