### ISSUE TITLE
`macos-12` runner in GitHub Actions is deprecated

### ISSUE THREAD

**Issue by norio-nomura** [lima-vm/lima#2695]
It seems that the `macos-12` runner in GitHub Actions has been deprecated. https://github.com/actions/runner-images/issues/10721. 

What is necessary to address this? Besides updating the workflows, is there anything else that needs to be done?

**Comment by AkihiroSuda** [comment]
We have to migrate them to `macos-13`, but I feel `macos-13` has been quite flaky (for vz, at least)
