### ISSUE TITLE
Diff disk reset after update reboot

### ISSUE THREAD

**Issue by ttc0419** [lima-vm/lima#2698]
### Description

After upgrading all packages and reboot the system, the system seems reset to its initial state, 100% reproducible.  Is it a disk corruption?
```shell
apk update && apk upgrade
reboot
```

**Comment by afbjorklund** [comment]
If you are using the Alpine image (the ISO, not Disk) it is running in RAM and doesn't persist changes (unless told to).

* https://github.com/lima-vm/lima/issues/2366

The scripts that Lima are using, are using a known setup that recreates a known set of packages on reboot.

**Comment by ttc0419** [comment]
@afbjorklund Thanks for the clarification, but it seems new packages like htop will persists across reboots. Does it only apply to packages in the base ISO?

**Comment by afbjorklund** [comment]
The other template (alpine-image.yaml), should behave more like a normal cloud image with a persistent OS disk.

For the alpine-iso, it comes in different "editions" with different packages and it does have a `/mnt/data` partition.

**Comment by ttc0419** [comment]
Yep, package upgrade in alpine-image can persist across reboots.

**Comment by afbjorklund** [comment]
It is _possible_ to make things persist in alpine-iso too, but different.

**Comment by jandubois** [comment]
> It is _possible_ to make things persist in alpine-iso too, but different.

They should persist automatically: We keep the package cache on the `diffdisk` so it persists across reboots and remains available even when offline: https://github.com/lima-vm/lima/blob/a26c031e31d6f3c16e3ec56c0de0333db999e756/pkg/cidata/cidata.TEMPLATE.d/boot/04-persistent-data-volume.sh#L101

`/etc` is also persisted on the `diffdisk`, so we have `/etc/apk/world` and know which packages are supposed to be installed.

And then we reinstall all packages on each reboot: https://github.com/lima-vm/lima/blob/a26c031e31d6f3c16e3ec56c0de0333db999e756/pkg/cidata/cidata.TEMPLATE.d/boot/04-persistent-data-volume.sh#L122-L123

**Comment by jandubois** [comment]
Looks like the automatic reinstall is available since Lima 0.20.0: https://github.com/lima-vm/lima/commit/b58f083b760190604e5ae8c4089eb5f2ca3d9a0b
