### ISSUE TITLE
`update-template-ubuntu.sh` should detect the distro version from the template

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/lima#2756]
`update-template-ubuntu.sh ubuntu-24.04.yaml ubuntu-24.10.yaml` should automatically detect the distro version for the each of the templates.

**Comment by norio-nomura** [comment]
The current implementation is designed to retrieve the latest image for 24.04 if the image in the template is 24.04, and the latest for 24.10 if the image is 24.10.

**Comment by norio-nomura** [comment]
> The current implementation is designed to retrieve the latest image for 24.04 if the image in the template is 24.04, and the latest for 24.10 if the image is 24.10.

Ah, sorry about that! I had intended to implement it that way, but I forgot that I fixed it in #2731.
