### ISSUE TITLE
Builtin functions to the provisioning scripts, for common template tasks?

### ISSUE THREAD

**Issue by afbjorklund** [lima-vm/lima#2765]
### Description

Should there be some built-in functionality, for instance to install a program and check that it is installed?

Some of my lima.yaml has duplicate code, when doing basic things like adding a program from an external URL.

```yaml
provision:
...
- mode: system
  script: |
    #!/bin/bash
    set -eux -o pipefail
    command -v kind >/dev/null 2>&1 && exit 0
    kind_version=latest
    case $(uname -m) in
      x86_64)
        curl -sSL -o kind https://kind.sigs.k8s.io/dl/${kind_version}/kind-linux-amd64
        ;;
      aarch64)
        curl -sSL -o kind https://kind.sigs.k8s.io/dl/${kind_version}/kind-linux-arm64
        ;;
    esac
    chmod +x ./kind
    mv ./kind /usr/local/bin/kind
    kind completion bash >/etc/bash_completion.d/kind
```

```yaml
probes:
...
- description: "kind to be installed"
  script: |
    #!/bin/bash
    set -eux -o pipefail
    if ! timeout 30s bash -c "until command -v kind >/dev/null 2>&1; do sleep 3; done"; then
      echo >&2 "kind is not installed yet"
      exit 1
    fi
```

Preferrably each of these scripts should be a _single_ line, with most of the basic things default.

Or would that be too much "magic", and better left to some other external system like Ansible?

---

It seems like every tool has their own variant, on how to spell basic things like version and arch.

And then come with all kinds of complicated scripts (and sed, and jq), just to install a simple binary.

https://kind.sigs.k8s.io/docs/user/quick-start/#installing-from-release-binaries

https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-kubectl-binary-with-curl-on-linux

And a lot of the same bugs are duplicated between them, like failing to use the `--fail` flag* to `curl`.

Or not using checksums to verify that the download succeeded (signatures are a bit more complicated)

**Comment by afbjorklund** [comment]
Nobody is perfect*, so this problem is bigger than just the provisioning and probes.

\* https://lima-vm.io/docs/installation/

But maybe some shell functions could help with the basic setup? That was my thought here.

**Comment by afbjorklund** [comment]
Here is one such external program
* https://github.com/zyedidia/eget

**Comment by jandubois** [comment]
There is also https://github.com/alexellis/arkade, which is mostly targeting k8s, but `ark get …` supports [a lot of CLI tools](https://github.com/alexellis/arkade?tab=readme-ov-file#catalog-of-clis).

I'm not sure if we should hardcode any of these package installers in Lima, but we can certainly show how to use them in some example templates.

Of course there is still the bootstrap question of how you install the installer. 😄 

```
curl -sLS https://get.arkade.dev | sudo sh
```

**Comment by afbjorklund** [comment]
The "sudo" part is probably another anti-pattern here. Especially when coupled with curl (with the wrong flags)

But I should have opened this as a discussion instead, maybe come back with some more examples later on...

**Comment by jandubois** [comment]
> The "sudo" part is probably another anti-pattern here.

Oh, the `sudo` is actually not necessary in a `system` provisioning script. 🤣

**Comment by afbjorklund** [comment]
I think this book from my xmas list will have some good advice on how to install software: https://xkcd.com/how-to/
