### ISSUE TITLE
release: avoid setting `__MAC_OS_X_VERSION_MAX_ALLOWED`?

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/lima#2767]
> It seems like a bug to me, that the binaries are setting the **max** versions - and that it would be better to fix it?
> 
> I can see how it would at runtime require a **min** version, but that can probably be handled inside the application.
> 
> i.e. when I build I get `/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk` and `-target-sdk-version=15.0`
> 
> The documentation is a bit outdated, it stops at 18 (10.14) while the latest is 24 (15.0): https://go.dev/wiki/Darwin

_Originally posted by @afbjorklund in https://github.com/lima-vm/lima/issues/2753#issuecomment-2423677851_

**Comment by afbjorklund** [comment]
Availability.h says:

>    For these macros to function properly, a program must specify the OS version range
>    it is targeting.  The min OS version is specified as an option to the compiler:
>    -mmacosx-version-min=10.x when building for Mac OS X, and -miphoneos-version-min=y.z
>    when building for the iPhone.  The upper bound for the OS version is rarely needed,
>    but it can be set on the command line via: -D__MAC_OS_X_VERSION_MAX_ALLOWED=10x0 for
>    Mac OS X and __IPHONE_OS_VERSION_MAX_ALLOWED = y0z00 for iOS. 

But I don't know who is setting 13

**Comment by afbjorklund** [comment]
This should have been the release job: "Merge pull request #2566 from AkihiroSuda/dev #3207":

https://github.com/lima-vm/lima/actions/runs/10610486369/job/29408056766

It sets up the runner like:
```
 # Xcode version
  xcodebuild -version
  # macOS SDK version
  xcrun --show-sdk-version

Xcode 14.2
Build version 14C18
13.1
```

Is the problem here that the Lima rosetta cache needs to be invalidated when macOS/Xcode is updated?

Or that Vz is somehow hard-coding the version it was built with as the max, when setting up the sharing?

**Comment by afbjorklund** [comment]
So we are supposed to get some reasonable default like: `-mmacosx-version-min=11`

But for some reason, the build sets the **max** version to the same as the current sdk.

**Comment by afbjorklund** [comment]
The end goal here is to be able to use the _same_ binary, for all the macOS versions.

Revert:

* https://github.com/lima-vm/lima/pull/2762

Note: Virtualization.framework requires macOS 11, Rosetta(Linux) requires macOS 13
