### ISSUE TITLE
jsonschema should have tests

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/lima#2768]
> Can we have a test? What happens when this is out of the sync with the YAML struct definition?

_Originally posted by @AkihiroSuda in https://github.com/lima-vm/lima/pull/2306#discussion_r1807391382_

**Comment by afbjorklund** [comment]
Now the generation of the schema will fail, if the result doesn't match the default yaml

e.g.

```
- at '/mountTypesUnsupported': got null, want array 
```

(if removing the "nullable", like when it was added)
