### ISSUE TITLE
git repo: rename `examples` to `templates` (will break existing hyperlinks)

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/lima#2808]
https://github.com/lima-vm/lima/tree/master/examples

This will break existing hyperlinks, but probably acceptable in v1.0

**Comment by afbjorklund** [comment]
Some of the examples are broken anyway, so any users of older releases will need to use older versions.

https://github.com/lima-vm/lima/tree/v0.23.2/examples
