### ISSUE TITLE
`limactl start template://ubuntu-24.10` creates an instance named `ubuntu-24.10`, while `limactl start ./ubuntu-24.10.yaml` creates `ubuntu-24-10`

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/lima#2813]
Probably `ubuntu-24-10` is the expected result?

**Comment by jandubois** [comment]
> while `limactl start ./ubuntu-24.10.yaml` creates `ubuntu-24-10`

I wasn't aware if this, and consider it a bug (or at least a misfeature). I commented further in https://github.com/lima-vm/lima/pull/2815#pullrequestreview-2399468657 and below.

**Comment by jandubois** [comment]
I don't understand why we would rename `.` to `-`, but allow `_` in instance names, which is also invalid in host names.
