### ISSUE TITLE
`limactl create template://ubuntu-24.04` prints `WARN[0001] vmType vz: ignoring [MinimumLimaVersion]`

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/lima#2816]
We always forget updating the allow list 😞 

It should be probably replaced with a deny list

**Comment by jandubois** [comment]
And I usually link back to https://github.com/lima-vm/lima/issues/2105#issuecomment-1872685576 for these kind of issues...

Let's also consider https://github.com/lima-vm/lima/issues/2512 if we are going to make changes.

**Comment by afbjorklund** [comment]
It is especially hard to "remember" since it is not being tested on Linux.
