### ISSUE TITLE
Cannot boot to a VM after changing shell to `fish` on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by sigasigasiga** [lima-vm/lima#2897]
### Description

1. `limactl start template://experimental/opensuse-tumbleweed`
2. `limactl shell opensuse-tumbleweed`
3. `sudo zypper in fish`
4. `sudo chsh --shell /usr/bin/fish $USER`
5. `limactl stop opensuse-tumbleweed`
6. `limactl start opensuse-tumbleweed`
7. BUG: Infinite `Waiting for the essential requirement 1 of 2: "ssh"`

Macbook Air M1 (2020)
```
$ sw_vers
ProductName:            macOS
ProductVersion:         15.0.1
BuildVersion:           24A348

$ limactl --version
limactl version 1.0.1

$ cat .lima/opensuse-tumbleweed/serial*.log

Welcome to openSUSE Tumbleweed 20241105 - Kernel 6.11.6-2-default (hvc0).

eth0: 192.168.5.15 fe80::5055:55ff:feea:74c3


lima-opensuse-tumbleweed login: ⏎
```

**Comment by jandubois** [comment]
This is fixed in #2874 and will be in Lima 1.0.2.

```console
$ limactl shell opensuse-tumbleweed
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
jan@lima-opensuse-tumbleweed /U/jan>
```
