### ISSUE TITLE
Can we install lima-guestagent to /usr instead of /usr/local ?

### ISSUE THREAD

**Issue by afbjorklund** [lima-vm/lima#290]
Just in case there **is** no `/usr/local/bin`, seemed much to add one...

Also the files from the other services are already installed in `/usr/bin`

```
command=/usr/local/bin/lima-guestagent
command_args="daemon"
command_background=true
pidfile="/run/lima-guestagent.pid"
```

I could of course add it to the PATH, just wondered if it was OK to change ?

**Comment by jandubois** [comment]
> Just in case there **is** no `/usr/local/bin`, seemed much to add one...

idk, what is the problem with adding `mkdir -p /usr/local/bin`?

I think it is the correct place to install additional software; we put nerdctl and containerd binaries there as well.

Also on Alpine-Lima `/usr/bin` is on a tmpfs eating up memory, whereas `/usr/local` is backed by a real volume.

**Comment by afbjorklund** [comment]
No worries, let's add it then!

I dropped the tmpfs support (it was added on top of previous rootfs, using a single ext4 image now instead).

Had the impression that lima _only_ supported img, for some reason it seemed to be called iso in alpine-lima ?

Now, to modify the PATH...

**Comment by afbjorklund** [comment]
> I think it is the correct place to install additional software; we put nerdctl and containerd binaries there as well.

Those were installed from system packages, so they ended up under /usr/bin. Which should also be OK, I guess.

**Comment by jandubois** [comment]
> Had the impression that lima _only_ supported img, for some reason it seemed to be called iso in alpine-lima ?

Lima does support running from an ISO, which is what Alpine-Lima does. In that case `baseDisk` is the ISO, and `diffDisk` is just a plain data volume. The `05-persistent-data-volume.sh` boot script sets this up, but probably has some Alpine assumptions baked in that need to be generalized before it works for other distros.

**Comment by jandubois** [comment]
> Those were installed from system packages, so they ended up under /usr/bin. Which should also be OK, I guess.

Yes, I think that should be the boundary: System packages install into the base system, but anything added by Lima itself goes into `/usr/local` because it does not come from the distro.

**Comment by afbjorklund** [comment]
It was straight-forward to add:

```diff
-BR2_SYSTEM_DEFAULT_PATH="/bin:/sbin:/usr/bin:/usr/sbin"
+BR2_SYSTEM_DEFAULT_PATH="/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin"
```

Not sure why it is "backwards"

---

Debian has it the other way around:
```
# *REQUIRED*  The default PATH settings, for superuser and normal users.
ENV_SUPATH	PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV_PATH	PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
```

I think BSD also had local at the end ?

At least that _used_ to cause the Homebrew users to be disappointed, when replacing Apple.

**Comment by jandubois** [comment]
idk, `/usr/local/bin` is first by default on macOS:

```console
$ cat /etc/paths
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
```

It doesn't make sense to me to put it at the end, at least not for the user environment.

I could see not including `/usr/local/bin` in the system environment at all because you don't want to accidentally provide a user-writable mechanism to override programs invoked from setuid binaries. Of course I think invoking programs without a full path from a program running as `root` is a bug; you should **never** rely on the environment to locate dependent executables.

**Comment by afbjorklund** [comment]
They must have changed it along the way, like how the shell changed from zsh to bash and back to zsh again.
