### ISSUE TITLE
Think I am misunderstand something about the guestagent

### ISSUE THREAD

**Issue by afbjorklund** [lima-vm/lima#291]
I have installed the lima-useragent service, but it fails to start (exit 1)

`rc-service lima-guestagent start`

`lima-guestagent is not installed yet`

`Child command line:`...`exited with return code 1`

Tried to run it manually (`lima-guestagent daemon`), to get a better error:

```
level=warning msg="$XDG_RUNTIME_DIR is not set, cannot determine the socket name"
level=fatal msg="must not run as the root"
```

Should it be executed as the lima user instead (of root), somehow ?

I see that systemd has both system and user, but not how openrc works.

**Comment by jandubois** [comment]
I think you are on an older source level. The guest agent daemon used to run under the user account, but has been changed recently to run as `root` to get access to `iptables`. The current version also has a hard-coded socket path, so I think you need to rebase your code on latest `master`.

**Comment by afbjorklund** [comment]
Thought I was, unless you changed to `main` or something ? (so many stale old "master" branches around...)

commit 7aa84989017bfbe008a72a70959075b2069ba3b6

But maybe there is a stale "lima-guestagent" hanging around in the cidata.iso, will try rebuilding it from scratch.

**Comment by jandubois** [comment]
This repo is still using `master`; it has no `main` branch.

And `cidata.iso` should be rebuilt on every `limactl start` command.

The most likely explanation to me would be that you ran `make all` instead of `make all install`, and the guest agent is copied from `/usr/local/share/lima/lima-guestagent.Linux-x86_64` because you are running the local `limactl`.

**Comment by afbjorklund** [comment]
Ah right, I think I only installed the binaries (bin) and not the data (share).

**Comment by afbjorklund** [comment]
Some other bashist bug with `make install`, will open separate PR.

`/bin/sh: 1: [[: not found`

**Comment by afbjorklund** [comment]
Now it is moving again, but this time some new `cloud-info` issue.

`Calling 'http://169.254.169.254/2009-04-04/meta-data/instance-id' failed`

`Calling 'http://192.168.5.2/latest/meta-data/instance-id' failed`

Oh well, thanks for answering the question about `lima-useragent`

**Comment by jandubois** [comment]
I had the same issue with the alpine image and "fixed" it by disabling the network data sources:

https://github.com/lima-vm/alpine-lima/blob/1a5cc69/genapkovl-lima.sh#L112-L115

**Comment by afbjorklund** [comment]
Yeah, it seems I lost the CD-ROM. I was trying to move it from /dev/vdb back to oldskool /dev/sr0

But can open a separate question about where to use virtio or not. Or if you have a chat somewhere ?

**Comment by jandubois** [comment]
> Or if you have a chat somewhere ?

We don't, but we just talked yesterday about maybe setting up a dedicated Slack instance. Currently we just chat in a direct messages on the rancher-user Slack, but can also use the Kubernetes Slack for now...

**Comment by afbjorklund** [comment]
> but can also use the Kubernetes Slack for now

Works for me, otherwise Matrix/Element is nice...
