### ISSUE TITLE
GRPC port forwarding hangs when using mysql connection

### ISSUE THREAD

**Issue by balajiv113** [lima-vm/lima#2968]
### Description

**Steps to reproduce**
- Run `limactl start --name=lima-vz --vm-type=vz --mount-type=virtiofs template://docker`
- Run `docker run --detach --name mariadb -p 127.0.0.1:10099:3606 --env MARIADB_DATABASE=db --env MARIADB_ROOT_PASSWORD=root mariadb:latest --port 3606`
- Run `mysql -uroot -proot --database=db --host=127.0.0.1 --port=10099 -e "SHOW TABLES;" ` from host and notice it hangs
- Same running from guest works

Note: Identified this issue by running ddev tests

**Comment by nirs** [comment]
@balajiv113 can this be related to #2970?

**Comment by balajiv113** [comment]
I don't think so, as its TCP connection in our case

What's happening with mysql is, 
As soon connection is established, 
- Host accepts a TCP connection
- Starts a tunnel
- Sends empty data via tunnel (Implemented now, to start tunnel on guest as well)
- Once tunnel msg is received on guest, it does a dial
- Start io.copy in guest. For some reason this immediately fails with no error but just says 0 read and error is nil

I have done a change to support retry in these cases
https://github.com/lima-vm/lima/compare/master...balajiv113:lima:grpc-hangs 

This works but need to see why it's failing in first place
