### ISSUE TITLE
`limactl start template://podman` installs an outdated version

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/lima#2978]
`limactl start template://podman` installs Podman 5.2.5-1.fc41

It is upgraded to 5.3.1-1.fc41 after running `sudo dnf upgrade` though.

**Comment by AkihiroSuda** [comment]
(Probably this is an intended behavior though, as upgrading all the packages may take a long time)

**Comment by afbjorklund** [comment]
There is a configuration for it (upgrade packages)

**Comment by afbjorklund** [comment]
It seems like "dnf install" will **not** install the latest package:

```console
[anders@lima-podman lima]$ sudo dnf install podman
Updating and loading repositories:
Repositories loaded.
Package "podman-5:5.2.5-1.fc41.x86_64" is already installed.

Nothing to do.
```

Only "dnf upgrade" (with a name) will also upgrade it... (?)

```console
[anders@lima-podman lima]$ sudo dnf upgrade podman
Updating and loading repositories:
Repositories loaded.
Package                                                   Arch        Version                                                    Repository                                      Size
Upgrading:
 podman                                                   x86_64      5:5.3.1-1.fc41                                             updates                                     48.6 MiB
   replacing podman                                       x86_64      5:5.2.5-1.fc41                                             90a8770483864183975e67de58bc6f37            48.0 MiB

Transaction Summary:
 Upgrading:          1 package
 Replacing:          1 package

Total size of inbound packages is 15 MiB. Need to download 15 MiB.
After this operation, 560 KiB extra will be used (install 49 MiB, remove 48 MiB).
Is this ok [y/N]: 
```

So it did have an up-to-date cache, just chose to ignore it?

It also defaults to "no", which has always been annoying.

**Comment by afbjorklund** [comment]
Apparently it is a bug/feature in dnf, as compared with yum...

https://unix.stackexchange.com/questions/539341/dnf-install-or-update-upgrade-in-one-command

**Comment by jandubois** [comment]
There is one thing that is bugging me: I may want to upgrade packages when I create the instance, but I don't want to do it every time I boot it. So I have to remember to disable the `.upgradePackages` setting after the first boot manually.

I know we discussed this before at https://github.com/lima-vm/lima/pull/2119#pullrequestreview-1816180396. So cloud-init would normally only upgrade on first-boot, but we modify the instance id on each boot, so to cloud-init every boot looks like a first-boot.

**Comment by afbjorklund** [comment]
Fixing the dnf install doesn't really help, since unlike the cloud-init it **only** installs once:

```bash
    command -v podman >/dev/null 2>&1 && exit 0
    dnf -y install --best podman
```

Since `podman` is already installed, it will just exit. Changing this would apply to all provisioning?

**Comment by afbjorklund** [comment]
Preferrably I would like to install podman to the normal "default" OS, but alas it is not available...

And I don't really _want_ to build it myself, even if I can: https://github.com/afbjorklund/podman-full

**Comment by afbjorklund** [comment]
`apt-get install --only-upgrade docker-ce docker-ce-cli docker-ce-rootless-extras`

`dnf upgrade --cacheonly podman`

**Comment by afbjorklund** [comment]
In theory this could happen also with template://docker, if Ubuntu decided to install `docker.io` with the base OS.

**Comment by afbjorklund** [comment]
Next time the Fedora image is updated, then the Podman package will be updated as well.

https://download.fedoraproject.org/pub/fedora/linux/releases/41/Cloud

So it is only as "outdated" as the release image, and is nowhere near the age of Ubuntu's.

https://packages.ubuntu.com/noble/podman (featuring podman 4.9.3)

**Comment by afbjorklund** [comment]
The template could "touch" some file when the package is installed/updated, and check for it in the start:

```bash
    command -v podman >/dev/null 2>&1 && test -e /var/tmp/lima-podman && exit 0
    dnf -y install --best podman && touch /var/tmp/lima-podman
```

This way it won't settle for the version bundled in the image, but install the latest/greatest at install time?
