### ISSUE TITLE
limactl info displays default home directory instead of the modified one

### ISSUE THREAD

**Issue by dharsanb** [lima-vm/lima#2993]
### Description

In the template, I've changed the `user.home` `/home/{{.User}}`. When using the `limactl info` command, the default home directory `/home/{{.User}}.linux` is displayed instead of the new one. Inside the VM, home directory is allocated as per the template.

**Comment by jandubois** [comment]
The `limactl info` command shows the default template, not information about a running instance. Use the `limactl list $INSTANCE` command instead:

```console
$ limactl info | jq -r .defaultTemplate.user.home
/home/jan.linux
$ limactl list default --json | jq -r .config.user.home
/home/jan
```

**Comment by jandubois** [comment]
When I edit the template file itself, the `limactl info` command shows the updated value:

```console
$ yq .user.home /usr/local/share/lima/templates/default.yaml
/home/{{.User}}
$ limactl info | jq -r .defaultTemplate.user.home
/home/jan
```

**Comment by dharsanb** [comment]
Sorry about that. Thanks for the clarification.
