### ISSUE TITLE
Host hostname

### ISSUE THREAD

**Issue by ianschmitz** [lima-vm/lima#388]
I realize the title is confusing 😛 . Sorry if there's a better forum for questions. I didn't see GitHub discussions enabled on this repo.

Coming from docker desktop, the recommended pattern when wanting to refer to HTTP URLs on the macOS host was to use `host.docker.internal`. I'm wondering if there's something similar in the Lima world?

A concrete example is running a Postgres instance using [Postgres.app](https://postgresapp.com/) and wanting to connect to it from a container running in Lima.

**Comment by jandubois** [comment]
> Coming from docker desktop, the recommended pattern when wanting to refer to HTTP URLs on the macOS host was to use `host.docker.internal`. I'm wondering if there's something similar in the Lima world?

We define `host.lima.internal` to point to the host from inside the VM.

**Comment by jandubois** [comment]
> I didn't see GitHub discussions enabled on this repo.

@AkihiroSuda Should we enable discussions, so we can move questions out of Issue, which should only have actionable items?

**Comment by ianschmitz** [comment]
> We define `host.lima.internal` to point to the host from inside the VM.

Wonderful. I'll give that a try. I had looked through the docs and didn't find this (sorry if I missed!) - so may be good to document it? 

Cheers

**Comment by jandubois** [comment]
> I had looked through the docs

It is documented here:

https://github.com/lima-vm/lima/blob/5237bfe/docs/network.md#host-ip-19216852
