### ISSUE TITLE
wrong exec format after stop/start

### ISSUE THREAD

**Issue by LATBauerdick** [lima-vm/lima#401]
I am using the alpine example yaml, and the initial `limactl start examples/alpine.yaml` works fine. 

However, after a `stop` command it cannot restart, and the `serial.log` shows that something went wrong starting `sshd`, see below -- any ideas? Somehow it seems to pick up the wrong exec format?

```
...
udhcpc: sending discover
udhcpc: sending select for 192.168.5.15
udhcpc: lease of 192.168.5.15 obtained, lease time 86400
 [ ok ]
 [ ok ]
 * Registering QEMU binaries in binfmt misc ... [ ok ]
unable to exec `/etc/init.d/sshd': Exec format error
unable to exec `/etc/init.d/udev-postmount': Exec format error

Welcome to Alpine Linux 3.13
Kernel 5.10.61-0-virt on an x86_64 (/dev/ttyS0)

lima-alpine login: 
```

**Comment by jandubois** [comment]
You need to provide more information about exactly what you are doing, and about your environment. I do this all the time (stopping and starting instances, including Alpine ones), and it (almost) always works for me:

```
$ tail ~/.lima/alpine/serial.log
udhcpc: lease of 192.168.5.15 obtained, lease time 86400
 [ ok ]
 [ ok ]
 * Registering QEMU binaries in binfmt misc ... [ ok ]
 * Starting sshd ... [ ok ]

Welcome to Alpine Linux 3.13
Kernel 5.10.61-0-virt on an x86_64 (/dev/ttyS0)

lima-alpine login:
```

**Comment by LATBauerdick** [comment]
yeah, I’m puzzled. Here is what I did (several times and even with a couple of `limactl rm alpine` in between):

```
❯ limactl --version
limactl version 0.7.3
❯ limactl start examples/alpine.yaml
❯ limactl stop alpine
❯ limactl start alpine
…
``` 
and it never starts with the error given above.

However, I did a limactl prune and it all works again. No idea what had gone wrong.

Thanks for your immediate response! I am closing the issue.
