### ISSUE TITLE
Lima + KinD + MetalLB

### ISSUE THREAD

**Issue by bcollard** [lima-vm/lima#404]
Hi! I'm using Lima with the [docker](https://github.com/lima-vm/lima/blob/master/examples/docker.yaml) flavor so that I can spawn [KinD](https://kind.sigs.k8s.io/) clusters. That is already awesome!! 🎉 

In Kubernetes, when I create some services type LoadBalancer, I get an external IP, thanks to MetalLB.
I can access these external IPs from the Lima VM. Like: 
```bash
limactl shell
curl 172.18.1.1
```
Plus, the connection to the docker daemon from my laptop is working fine: `export DOCKER_HOST=unix://$HOME/docker.sock`
Super awesome! 🤩 

Now, I would like to access these Kubernetes services from the host, my MacBook. 

**My question**: what would be the next steps to have, let's say the subnet `172.18.0.0/16` (the one configured in MetalLB), routed to the guest VM? so that my curl requests work from my machine up to Kubernetes?

I've been quickly looking at https://github.com/lima-vm/lima/blob/master/docs/network.md and https://github.com/lima-vm/vde_vmnet but I'm lost! :-)

**Comment by rupesh-papneja** [comment]
@bcollard Check this out. this may help https://github.com/lima-vm/vde_vmnet/issues/19#issuecomment-950109235
