### ISSUE TITLE
Run golangci-lint in the "lint" target ? 

### ISSUE THREAD

**Issue by afbjorklund** [lima-vm/lima#416]
```console
$ make lint
golangci-lint run ./...
yamllint .
$
```

Just in case you would forget to run `gofmt` after a last minute change or something \<ehrm>

----

Experimented with running these linters in containers too, but the sizes of those varied greatly...

`8,0M	golangci-lint-1.42.1-linux-amd64.deb`

```
REPOSITORY               TAG       IMAGE ID       CREATED        SIZE
golangci/golangci-lint   v1.42.1   87e9f778b25e   2 months ago   963MB
```

Something similar for yamllint.

`60K	yamllint-1.26.3-py2.py3-none-any.whl`

```
REPOSITORY   TAG       IMAGE ID       CREATED       SIZE
python       latest    4246fb19839f   3 weeks ago   917MB
```

**Comment by jandubois** [comment]
Adding `golangci-lint` to `make lint` is fine with me.

I would not want to run it in a container, but directly on the host. There may not always be a running container runtime when you run `make lint`.

**Comment by afbjorklund** [comment]
The alpine images were more like 50 MB than 1000 MB ;-)

**Comment by jandubois** [comment]
> The alpine images were more like 50 MB than 1000 MB ;-)

I know. 😄 My objection is to depending on a working container runtime, not to the size of the images.

**Comment by afbjorklund** [comment]
I was more surprised, actually. For minikube we made it optional (`IN_DOCKER=true`), it can be useful to make sure everyone uses the same version etc.

**Comment by jandubois** [comment]
> make sure everyone uses the same version

We all get the same version when it runs during CI; so this is just a convenience for developers.

Also I typically keep all tools at the very latest version locally, so it provides an early notification that something may need changing in the future (this can be both good and bad, depending on what you are trying to do at that moment 😄 ).

**Comment by jandubois** [comment]
> I was more surprised,

It's the reason I picked Alpine for Rancher Desktop. Unfortunately adding docker engine to the image almost tripples it in size.

Well, one of the reasons. The other big one being that you can reduce the number of packages you include: you don't have to worry about CVEs in packages you don't ship because you don't need them.

**Comment by afbjorklund** [comment]
Yeah, as you know I built my own distro - for mostly the same reasons.
