### ISSUE TITLE
Support for MacPorts

### ISSUE THREAD

**Issue by ain** [lima-vm/lima#425]
It'd be cool if one could install `lima` with MacPorts as well so it'd not be as reliant on HomeBrew.

**Comment by afbjorklund** [comment]
@ain : I think you can just go right ahead and add it: https://guide.macports.org/#development

**Comment by afbjorklund** [comment]
There is a "golang" group, that should make it easier :
https://guide.macports.org/#reference.portgroup.golang

```tcl
PortGroup           golang 1.0
go.setup            github.com/lima-vm/lima 0.7.3 v
```

**Comment by mikluko** [comment]
https://github.com/macports/macports-ports/pull/13395

**Comment by mikluko** [comment]
Lima is in MacPorts now: https://github.com/macports/macports-ports/commit/92725ac7f3704d90ba17b9ab183a57b58edd8b0b

**Comment by ain** [comment]
Thanks @mikluko !
