### ISSUE TITLE
Make the shell prompt `$PS1` distinguishable from the host shell

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/lima#427]
Maybe we should change the color of `$PS1` by default

**Comment by afbjorklund** [comment]
I themed my login shell, so when I get default one I know it is another server 🙃

**Comment by afbjorklund** [comment]
Currently it is up to the Linux distribution, right ?

**Comment by AkihiroSuda** [comment]
>  but maybe a color clue could help

Yes, the color should be probably lime 💚 (https://github.com/lima-vm/lima/issues/268)

> Currently it is up to the Linux distribution, right ?

Yes

**Comment by afbjorklund** [comment]
For reference, the ubuntu prompt is:

```
if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
```

It doesn't have any special 256-color prompt.


For lima, that is the difference between "cyan" and "lime".

https://en.wikipedia.org/wiki/Lime_(color) says `#BFFF00`

**Comment by afbjorklund** [comment]
Here is one to try:

### GNOME (24-bit)
`#BFFF00` "lime"

```
PS1='\[\033[38;2;192;255;0m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
```

### xterm-256color
`#AFFF00` "154"

```
PS1='\[\033[38;5;154m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
```

### xterm (16 colors)
`#00FF00` "bright green"

```
PS1='\[\033[01;92m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
```

### monochrome

```
PS1='\u@\h:\w\$ '
```

**Comment by afbjorklund** [comment]
Apparently, one needs to change both ssh_config and sshd_config to send COLORTERM:

`SendEnv LANG LC_*`

`AcceptEnv LANG LC_*`

And in the default setting, the lima vm will switch to monochrome for root (possibly a feature?)

![lima-root](https://user-images.githubusercontent.com/10364051/142942736-fe7abe64-68b1-42f0-8c2d-eac1a2888026.png)

**Comment by jandubois** [comment]
I feel like this is an issue best left to the users themselves. It is no different than configuring a shell prompt on any of your other physical or virtual machines you connect to via `ssh`.

And there are myriad ways to do this, including:

* setting `COLORTERM` via `env` in your `lima.yaml`
* set up something with a provisioning script
* creating a symlink to a `.profile` etc. on your host
* terminal profile switching

So any hardcoded mechanism is bound to not satisfy lots of users. I think it would be best to show some examples of setting this up in the FAQ, or in the sample config files, but leave the default prompt(s) to whatever the distro does.

**Comment by afbjorklund** [comment]
The suggestion was just to change from Ubuntu "green" to Lima "lime", for the default distribution.

The feature to add `COLORTERM` to `limactl shell` parameters is separate, but still a good idea ?

```diff
--- .bashrc.orig	2020-02-25 13:03:22.000000000 +0100
+++ .bashrc	2021-11-22 23:13:37.543709419 +0100
@@ -37,7 +37,11 @@
 
 # set a fancy prompt (non-color, unless we know we "want" color)
 case "$TERM" in
-    xterm-color|*-256color) color_prompt=yes;;
+    xterm-color) color_prompt=yes;;
+    *-256color)  color_prompt=256;;
+esac
+case "$COLORTERM" in
+    truecolor) color_prompt=true;;
 esac
 
 # uncomment for a colored prompt, if the terminal has the capability; turned
@@ -56,8 +60,12 @@
     fi
 fi
 
-if [ "$color_prompt" = yes ]; then
-    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
+if [ "$color_prompt" = true ]; then
+    PS1='${debian_chroot:+($debian_chroot)}\[\033[38;2;192;255;0m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
+elif [ "$color_prompt" = 256 ]; then
+    PS1='${debian_chroot:+($debian_chroot)}\[\033[38;5;154m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
+elif [ "$color_prompt" = yes ]; then
+    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;92m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
 else
     PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
 fi
```

Other distros (including ubuntu.yaml) would keep their default colors ? See systemd's `ANSI_COLOR`

https://www.freedesktop.org/software/systemd/man/os-release.html#ANSI_COLOR= (and their PS1)

**Comment by jandubois** [comment]
Replacing the default green with a lime shade is fine with me. But otherwise I'm going to stay out of this; I worry that this can turn into endless bike-shedding.

**Comment by afbjorklund** [comment]
BTW: For alpine, you need to source `/etc/profile.d/color_prompt.sh.disabled`

**Comment by jandubois** [comment]
> Looks like for alpine-lima, it had been renamed to `/etc/profile.d/color_prompt`. Still means disabled, though...

I guess it is a bug in Alpine 3.13. In 3.14 it is called `color_prompt.sh.disabled`. I can rename it in `lima-init`, if we want to, or we could do the renaming in a provisioning script in `examples/alpine.yaml`.

I have a slight preference to do it in `lima-init`, but don't really care too much.

**Comment by afbjorklund** [comment]
You can probably leave it as-is, it's just a version difference: https://gitlab.alpinelinux.org/alpine/aports/-/issues/6933

It's rather ugly, so I don't think you want to enable it by default ?

**Comment by afbjorklund** [comment]
Feedback on the PR wonders if something should be done for monochrome terminals ?

![lima-monochrome](https://user-images.githubusercontent.com/10364051/143493262-fbd7d518-1451-42bd-bd7e-83a07da7efe5.png)

Like adding something to the beginning of the prompt, or whatever. Otherwise, it "works"

![lima-truecolor](https://user-images.githubusercontent.com/10364051/143493626-3df6b7ad-a5de-43d3-af32-710dbb86a879.png)

**Comment by afbjorklund** [comment]
I added some code (48db8c7), to **only** set the background when running with a dark theme.

See [github.com/afbjorklund/go-termbg/pkg/termbg](https://github.com/afbjorklund/go-termbg/pkg/termbg) for the detection, ported from a rust lib...

**Comment by afbjorklund** [comment]
With the new lima color, this is not needed anymore. It looks OK enough in both modes:

![lima-color-tango-dark](https://user-images.githubusercontent.com/10364051/160272981-51909bcc-5c95-47bc-9b5a-aa781965c066.png)

![lima-color-tango-light](https://user-images.githubusercontent.com/10364051/160272984-fc397dbc-37af-418d-b817-1dcc25350246.png)

`PS1='\[\033[38;2;0;191;140m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '`
