### ISSUE TITLE
Add an example for faasd

### ISSUE THREAD

**Issue by alexellis** [lima-vm/lima#440]
For the faasd project, we tend to use Multipass which now has support for preloaded examples and cloud-init.

I'd like to see someone from the Lima or OpenFaaS community contribute an example for faasd:

https://github.com/lima-vm/lima/tree/master/examples

I'd probably suggest using Ubuntu as a base image.

Here's a 3 line installation script, so I think it'd look just like one of the existing examples, plus this in the `provision:` section of the YAML file.

https://github.com/openfaas/faasd#deploy-faasd

**Comment by afbjorklund** [comment]
I can try to add an example for this (faasd).

**Comment by afbjorklund** [comment]
Is it possible to run with the standard containerd and cni instead, it does it need a custom version ?

**Comment by alexellis** [comment]
@afbjorklund unfortunately not, because we test and build against specific versions.

**Comment by afbjorklund** [comment]
That's OK, I think k3s also uses a custom bundled version
