### ISSUE TITLE
Add feature to show resulting config

### ISSUE THREAD

**Issue by afbjorklund** [lima-vm/lima#443]
Currently the default template is included in `limactl info`, but in a different format (JSON instead of YAML)

It would be more useful if it was shown in the _same_ format, without the comments and with values replaced...

```
limactl config [FILE.yaml...]
```

Also add a small helper function, to compare a template against the default.

This is more handy than dumping two yaml files and running `diff` on them.

```
limactl config --diff FILE.yaml...
```

**Comment by jandubois** [comment]
> Currently the default template is included in `limactl info`, but in a different format (JSON instead of YAML)

And I have wondered what the use case was for that as well: https://github.com/lima-vm/lima/pull/280#discussion_r721628426

> It would be more useful if it was shown in the _same_ format, without the comments and with values replaced...

Useful **for what**? Just removing the comments?

```console
$ yq eval '... comments=""' /usr/local/share/doc/lima/examples/default.yaml
arch: "default"
images:
  - location: "~/Downloads/impish-server-cloudimg-amd64.img"
    arch: "x86_64"
  - location: "~/Downloads/impish-server-cloudimg-arm64.img"
    arch: "aarch64"
  - location: "https://cloud-images.ubuntu.com/impish/current/impish-server-cloudimg-amd64.img"
    arch: "x86_64"
  - location: "https://cloud-images.ubuntu.com/impish/current/impish-server-cloudimg-arm64.img"
    arch: "aarch64"
cpus: 4
memory: "4GiB"
disk: "100GiB"
mounts:
  - location: "~"
    writable: false
  - location: "/tmp/lima"
    writable: true
ssh:
  localPort: 0
  loadDotSSHPubKeys: true
  forwardAgent: false
containerd:
  system: false
  user: true
firmware:
  legacyBIOS: false
video:
  display: "none"
networks:
propagateProxyEnv: true
useHostResolver: true
```

I would find the `config` command more useful (after #436 is done) if it displayed the merged config, and not just the original YAML without comments.

> ```
> limactl config [FILE.yaml...]
> ```
> 
> Also add a small helper function, to compare a template against the default.
> 
> This is more handy than dumping two yaml files and running `diff` on them.

Maybe, but not really by a lot.

> ```
> limactl config --diff FILE.yaml...
> ```

This I find somewhat useful, except I would want to be able to compare any 2 config files, and not just one file against the default.

However, you can mostly already do this with `yq` as well; it just doesn't fill in the default values, so they show up in the diff if just one of the files specifies them.

```console
$ diff -u <(yq eval -P '... comments=""' examples/docker.yaml) <(yq eval -P '... comments=""' examples/podman.yaml)
```

But even then I see very little benefit over just running `diff -u` between the 2 files, at least for the config files I used for testing.

# My Main point

I'm concerned about "littering" `limactl` with too many subcommands that are most likely useless for the vast majority of users. They will present a cognitive barrier for new users to getting started with lima. If nothing else, it is more and more stuff to read through, just to find out it is not relevant to you.

Not sure what the right level of compromise is, but I feel like both `config` and `du` are not really important subcommands (and yes, I've mostly felt like that about `info` too, but I can see it being useful as we add more information to it).

To me the barrier to inclusion in `limactl` should be: "What end-user problem is this solving, and how?". There should be a compelling answer to this before we add anything.

Maybe the commands that don't clear the barrier can be moved to a separate utility/helper tool?

**Comment by AkihiroSuda** [comment]
Maybe we can have `config` and `du` as subcommands of `limactl debug`. `info` can be perhaps moved/aliased there too.

**Comment by afbjorklund** [comment]
I was looking at the similar config command for compose, that is why.

But it can be done in the shell instead, using `yq` and friends, so closing.

**Comment by afbjorklund** [comment]
> > It would be more useful if it was shown in the _same_ format, without the comments and with values replaced...
> 
> Useful **for what**?

I meant that it could be fed back into the tool, as config for another instance. Or diffed. Harder to do, with json vs yaml ?

**Comment by afbjorklund** [comment]
> I'm concerned about "littering" `limactl` with too many subcommands that are most likely useless for the vast majority of users.

Good thing I didn't include the "color diff" then, which was mostly left out due to adding dependencies (and thus some extra bloat)
