### ISSUE TITLE
Show disk usage of lima directories

### ISSUE THREAD

**Issue by afbjorklund** [lima-vm/lima#445]
Add a lima command similar to `du`, to show the disk usage of home and cache.

Use the standard output format, for tools like https://github.com/zz85/space-radar

`du -k ~/.lima`

Also show urls...

**Comment by jandubois** [comment]
What advantages does this provide over just using `du`?

**Comment by afbjorklund** [comment]
Mostly I was looking to translate the cache sha256 into url.

**Comment by afbjorklund** [comment]
But it can be done in the shell instead, with `du`, so closing.
