### ISSUE TITLE
Support host.docker.internal hostname

### ISSUE THREAD

**Issue by deviantintegral** [lima-vm/lima#456]
I've been using lima via https://github.com/abiosoft/colima for the past few weeks, and the experience has been great. However, there's one noticeable gap that stops it from being a drop-in Docker Desktop replacement: resolving the `host.docker.internal` host.

For example, ddev (as documented at https://github.com/drud/ddev/issues/3208) works really well with colima, except for xdebug connections back to the host. Out of the box, it assumes that an IDE is listening on `host.docker.internal` for debugging. I can work around this easily enough by adding `host.docker.internal` to `/etc/hosts`, but that certainly gets wiped when restarting lima and looks to be reset when macOS network configuration changes.

Three solutions I see:

1. Add `host.docker.internal` alongside the existing host. This would make sense if we anticipate lima to be a drop-in replacement for Docker Desktop for the future (and not just during a transition time for tooling like ddev to explicitly support it).
2. Make it a configuration option, so downstream tools like colima could enable or add additional hosts for internal resolution.
3. Do nothing, and require external tools to manage this (IMO the least attractive option).

See also: https://github.com/lima-vm/lima/pull/142

**Comment by jandubois** [comment]
> * Make it a configuration option, so downstream tools like colima could enable or add additional hosts for internal resolution.

It is already trivial to do with a provisioning script. I just created #457 to add it to `examples/docker.yaml`.

cc/ @abiosoft

**Comment by abiosoft** [comment]
I actually thought `host.lima.internal` would suffice as mentioned in this issue https://github.com/abiosoft/colima/issues/57.
I will add the docker hostname as well to conform with existing user experience.

@deviantintegral would you be willing to assist with testing this?

**Comment by deviantintegral** [comment]
@abiosoft yep, I can or I can ask one of our team to check. Just ping me in the PR when you get to filing it. Thank you!
