### ISSUE TITLE
Can't find docker.sock file after star limactl with docker.yaml

### ISSUE THREAD

**Issue by phuna** [lima-vm/lima#458]
Hi, 
I'm on macos 12.0.1 Intel.
I started lima with `docker.yaml` but can set `DOCKER_HOST` because I can't find `docker.sock` file. Below are details:

```
$ limactl start https://raw.githubusercontent.com/lima-vm/lima/master/examples/docker.yaml
```
Once it done, I run the below command (taking from `docker.yaml` file above) to determine path to `docker.sock` but it failed.
```
$ limactl list docker --format 'unix://{{.InstanceDir}}/sock/docker.sock'
unix://FATA[0000] template: format:1:9: executing "format" at <.InstanceDir>: can't evaluate field InstanceDir in type *store.Instance
```
Trying to look into docker sub directory of lima I can't find `docker.sock` file either:
```
$ ls -a ~/.lima/docker/sock
.		..		<no value>
```
So instead of `docker.sock`, there's a file with `<no value>` as name.
Please help. 
Thank you.

**Comment by jandubois** [comment]
Did you build and install lima from the latest `master` branch of the repo?

The errors you are getting sound like you are using an older lima version (maybe the last released version) with the config file from the HEAD of repository, which will not work, as the `InstanceDir` fields, both for `hostSocket` and for `limactl list --format` have only been implemented very recently.

**Comment by phuna** [comment]
@jandubois  oh, I use the Homebrew version, that could be the cause. I'll try with the `master` branch. Thank you for your quick answer.

**Comment by phuna** [comment]
Haven't got time to build `master` branch myself so I use the `docker.yaml` corresponding to the current binary version (0.7.4) and I can use `docker` CLI on host now.
