### ISSUE TITLE
Don't set the prompt color when running in light terminal theme

### ISSUE THREAD

**Issue by afbjorklund** [lima-vm/lima#485]
As noted in https://github.com/lima-vm/lima/issues/427#issuecomment-979440137, there are some usability issues with lime-on-white.

![lima-light](https://user-images.githubusercontent.com/10364051/143495860-038cde16-b613-429e-86b0-3a1591e2cfc2.png)

It should also be possible to opt out of it (color), even for the default instance.

Use a better library, than the proposed port:

https://github.com/muesli/termenv

----

* Issue #427

**Comment by afbjorklund** [comment]
With the new lima color, this is not needed anymore. It looks OK enough in both modes:

![lima-color-tango-dark](https://user-images.githubusercontent.com/10364051/160272981-51909bcc-5c95-47bc-9b5a-aa781965c066.png)

![lima-color-tango-light](https://user-images.githubusercontent.com/10364051/160272984-fc397dbc-37af-418d-b817-1dcc25350246.png)

`PS1='\[\033[38;2;0;191;140m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '`

**Comment by cwegener** [comment]
I haven't had any issues with colors from `limactl` output. And the colors for the interactive prompt look good to me too.

I am using base16-shell for terminal colors and most importantly all the lima colors honor the colors from base16-shell.

I spot checked a few of the base16-shell color themes on a couple of terminals on Linux and the all have readable text for both limactl output and the interactive prompts.

**Comment by afbjorklund** [comment]
Thank you for the feedback, and this was when running in a  "light" theme with a white or light yellow/gray background?

**Comment by cwegener** [comment]
I actually checked all the base16 themes and as expected, color text is always perfectly readable. Which is actually a property of base16-shell

I think a better measure would be to test with the default color settings of some major macOS and Linux desktop terminal emulators.

**Comment by afbjorklund** [comment]
> I actually checked all the base16 themes and as expected, color text is always perfectly readable.

I tried out a few themes, and I am not sure I agree...

![lima-base16-classic-dark](https://github.com/lima-vm/lima/assets/10364051/454a6939-7bd7-4dda-80cf-decb0f13da69)

![lima-base16-classic-light](https://github.com/lima-vm/lima/assets/10364051/c0110392-7e5e-4eba-8d3d-09ea1a90b7d9)

I would say that the default prompt has some issues?

So we should either change the color, or revert to the original. Perhaps just use something else...

![lima-prompt](https://github.com/lima-vm/lima/assets/10364051/6adedb3e-4e42-4b58-87bc-366276980931)   i.e. `PS1="[LIMA] $PS1"`

**Comment by cwegener** [comment]
> I tried out a few themes, and I am not sure I agree...

Oh! I was testing a different prompt! I tested the limactl interactive prompts (i.e. `limactl start`)

I didn't actually bother about the shell prompts inside the VM. (My personal use of lima shell is non-interactive. i..e I don't enter an interactive `lima shell` very often)

**Comment by cwegener** [comment]
> So we should either change the color, or revert to the original. Perhaps just use something else...

That's exactly what I'm thinking. `[LIMA]` as a prefix in front of the lima shell prompt string should make it clear for anyone who may not see the `lima-<name>` hostname in the prompt.

**Comment by cwegener** [comment]
Cycling through all the base16 color schemes. The light green  color is indeed bad. It's not visible against a light background. Something is wrong there with the username and hostname part of the shell prompt. I do remember this light green being a default Ubuntu shell prompt color in the past. I haven't used an Ubuntu desktop in a while. So I'm not sure what the default shell prompt colors are today.

I have also checked the Ubuntu `$LS_COLORS` and they're all fine

[ubuntushell.webm](https://github.com/lima-vm/lima/assets/2950544/19860ddf-3d8d-4cb5-8113-ccfd8f2cfa8b)

**Comment by cwegener** [comment]
#433

Ah. I see now. The change of the Ubuntu prompt was deliberate ... Hmm. Yeah. Not sure about that. Seems like opening up a can of worms.

**Comment by afbjorklund** [comment]
The new "dark cyan" color would have worked with the new color scheme, but I think I will drop the "bright green" color.

* https://github.com/lima-vm/lima/issues/268#issuecomment-1069351680

* `#00bf8c` "lima"

* `#BFFF00` "lime"

It required extra code to export the `COLORTERM` and `TERMTHEME` variables, and I am not sure if it was all worth it...

#486

`COLORTERM=truecolor`

`TERMTHEME=Dark`

----

Then it will fall back to using the usual `TERM=xterm-256color` (and [NO_COLOR](http://no-color.org/) if desired)  environment variables.

The Alpine image didn't use any color prompt (at all) anyway, unless you enable `/etc/profile.d/color_prompt.sh`

![lima-alpine-color-prompt](https://github.com/lima-vm/lima/assets/10364051/c6b0e23f-84d8-4fea-b178-c9830a2c4c15)

And otherwise it was only the "default" instance that got the override, if you started "ubuntu" it was still green.

**Comment by cwegener** [comment]
> The Alpine image didn't use any color prompt

Yeah. I was wondering about the original implementation of the color change.

The way I understand it, the change of the Ubuntu bash prompt color was specifically for one single use case:
- Running Ubuntu Lima VM on a Ubuntu Host OS

I'm not sure how widespread this particular Ubuntu-on-Ubuntu use case even is? Obviously you are using Ubuntu-on-Ubuntu yourself, so it's a pretty important use case.


The part that I still don't understand is why color is required as a concept at all.

If we take just the title of the of the original issue #427 

>  Make the shell prompt $PS1 distinguishable from the host shell

Then I think there is probably nothing that would need to be done, because in most cases, the hostname of the Lima VM will already be part of the PS1 shell prompt.

And if I understand it correctly, the hostname always begins with `lima-` ???

So, wouldn't the shell prompt already be distinguishable by default?

**Comment by afbjorklund** [comment]
> I'm not sure how widespread this particular Ubuntu-on-Ubuntu use case even is? Obviously you are using Ubuntu-on-Ubuntu yourself, so it's a pretty important use case.

I think it is a **good** thing that Lima allows running also on developer (Linux) machines, but in this case it is only relevant in the context of the default terminal colors on the host.

Other projects like Docker Machine or Podman Machine took years, before they "allow" running it on something other than Mac and Windows? Even if you actually wanted to, that is.

In the original implementation, I was not using the default theme on my Ubuntu machine anyway (mostly used that for screenshots), so it already looked different from the host terminal.

> The part that I still don't understand is why color is required as a concept at all.

It is not required, it was _one_ way of making the `lima` shell special:

"Maybe we should change the color of $PS1 by default" (https://github.com/lima-vm/lima/issues/427#issue-1060070781)

So that's what I did, and now "ubuntu-lima" (i.e. "default") is different.

It seemed like a good idea at the time, but as said there are other options...

----

The prompt is no longer "bright green", so I think _this_ issue is closed:

* #485

I opened a new issue for the discussion of the lima color prompt:

* #1892

**Comment by cwegener** [comment]
> I think it is a good thing that Lima allows running also on developer (Linux) machines, but in this case it is only relevant in the context of the default terminal colors on the host.

100% agreed.

What I was not sure about was the current "market share" of Ubuntu amongst developer desktops, compared to e.g. popOS, Fedora, Manjaro, etc...

From my highly anecdotal experience, Ubuntu actually DOES still hold the majority of the "market share" in the Linux Developer space.
