### ISSUE TITLE
Remove explicit localPort setting from docker, podman, and singularity examples

### ISSUE THREAD

**Issue by jandubois** [lima-vm/lima#511]
These are the only examples that still set a fixed port number instead of letting lima pick an available one:

```console
$ grep -r localPort examples
examples/default.yaml:  localPort: 0
examples/default.yaml:# Port forwarding rules. Forwarding between ports 22 and ssh.localPort cannot be overridden.
examples/docker.yaml:  localPort: 60006
examples/podman.yaml:  localPort: 60906
examples/singularity.yaml:  localPort: 62045
```

I believe this is a left-over from the time before we had unix socket forwarding (or the `limactl show-ssh` command), so access via a fixed port was simpler.

I think this is no longer necessary, and we should remove the port assignments.

In addition, I don't think `examples/docker.yaml` should set `loadDotSSHPubKeys: true` either anymore.

cc/ @afbjorklund

**Comment by AkihiroSuda** [comment]
SGTM

**Comment by afbjorklund** [comment]
Sounds good, I don't either docker or podman was working over ssh anyway (missing host keys, missing user keys, etc)

The current unix tunneling is much easier to use, and still uses ssh. So might as well remove the support for `ssh://` URLs.

**Comment by solarkraft** [comment]
Hmm, the alpine example now results in `FATA[0024] the YAML is invalid, saved the buffer as "lima.REJECTED.yaml": field `ssh.localPort` must be set` for me with 0.8.1 from homebrew. 

Re-adding the lines removed in #517 solves that issue.

**Comment by jandubois** [comment]
@solarkraft I don't understand how it is possible to get this error. The only place I see where this could be emitted is https://github.com/lima-vm/lima/blob/v0.8.1/pkg/limayaml/validate.go#L311-L312

However, that function is **not** called when `localPort` is `0`: https://github.com/lima-vm/lima/blob/v0.8.1/pkg/limayaml/validate.go#L98-L102

Are you using the `examples/alpine.yaml` file included in the release?

**Comment by jandubois** [comment]
@solarkraft Please double-check that your version is really 0.8.1 by running `limactl --version`.

**Comment by solarkraft** [comment]
Welp, never mind. I'm really running 0.8.1, but re-trying with Debian (actually ARM compatible) it just works now (maybe it was a purge I did in between?).
