### ISSUE TITLE
Add hints on where to download missing host clients

### ISSUE THREAD

**Issue by afbjorklund** [lima-vm/lima#515]
Currently we mention that they are to be installed on the host: (just "assumed")

examples/docker.yaml:  To run `docker` on the host (assumes docker-cli is installed):
examples/podman.yaml:  To run `podman` on the host (assumes podman-remote is installed):
examples/k3s.yaml:  To run `kubectl` on the host (assumes kubectl is installed):
examples/k8s.yaml:  To run `kubectl` on the host (assumes kubectl is installed):

We could do a LookPath, and show a URL on where to install it from (if it is missing) ?

https://docs.docker.com/engine/install/binaries/
https://podman.io/getting-started/installation
https://kubernetes.io/docs/tasks/tools/#kubectl
https://kubernetes.io/docs/tasks/tools/#kubectl

The cmd and url would be given in the YAML file.

~~Alternatively it could be downloaded automatically...~~

----

No host clients available for nerdctl, so run with lima:

* `lima nerdctl`

* `lima ctr`

* `lima buildctl`

Theoretically everyone uses Homebrew, makes it easy.

* `brew install docker`

* `brew install podman`

* `brew install kubectl`

**Comment by afbjorklund** [comment]
Should make sure to link to Docker Engine and Podman Remote, rather than to Docker Desktop and Podman Machine.

i.e. just need the client binary (a small statically linked go program), don't need the whole server and bundled VM solution.

**Comment by jandubois** [comment]
> Should make sure to link to Docker Engine

You mean "Docker CLI", not "Docker Engine", I think.

Also note that we don't need a host-client for `nerdctl`; it only runs inside the VM. We already have the `nerdctl.lima` wrapper script.

I'm somewhat opposed to extend lima with knowledge about particular client applications (but documentation is obviously fine). We should not try to replace platform package managers.

**Comment by afbjorklund** [comment]
> You mean "Docker CLI", not "Docker Engine", I think.

I actually meant the _product_ pages, since linking vendor:

~~https://docs.docker.com/desktop/~~

https://docs.docker.com/engine/

When it comes to deb packages, you are right. (`docker-cli`)
In brew it is only called `docker`, so I guess the names vary ?
The system package is called `docker.io` (a naming conflict)

Typically it looks something like this, throw away the `dockerd`:
https://download.docker.com/linux/static/stable/x86_64/docker-20.10.12.tgz

**Comment by afbjorklund** [comment]
> Also note that we don't need a host-client for `nerdctl`; it only runs inside the VM. We already have the `nerdctl.lima` wrapper script.

That is what I _tried_ to write. Then again, that also works for the other tools.

`lima docker`

`lima podman`

`lima sudo kubectl`

**Comment by afbjorklund** [comment]
> I'm somewhat opposed to extend lima with knowledge about particular client applications [...]}

Sometimes I forget that the main focus is on containerd/buildkitd, rather than providing some toolkit like Vagrant.

And maybe installing the clients is easy enough to not get involved in adding URLs, to the "example" YAML files.

For the Mac users it should be simple enough (`brew install`), so I will close this issue again.
