### ISSUE TITLE
lima start waiting (`grub>` prompt in `serial.log`)

### ISSUE THREAD

**Issue by stvgz** [lima-vm/lima#525]
limactl start default

shows

`[hostagent] Waiting for the essential requirement 1 of 5: "ssh"
`

Installed  lima with brew

$ brew --version
Homebrew 3.3.9
Homebrew/homebrew-core (git revision 5fc487f2abe; last commit 2022-01-05)

Mac version

10.15.7 (19H2)

Checked 
stuck on "Waiting for the essential requirement 1 of X: "ssh"
https://github.com/lima-vm/lima#stuck-on-waiting-for-the-essential-requirement-1-of-x-ssh

Confirmed I have  libslirp  v4.6.1 installed

Here is serial.log from 

.lima/default/serial.log

`BdsDxe: loading Boot0008 "ubuntu" from HD(15,GPT,0BA864C4-F213-400E-A981-345A828F1714,0x2800,0x35000)/\EFI\ubuntu\shimx64.efi
BdsDxe: starting Boot0008 "ubuntu" from HD(15,GPT,0BA864C4-F213-400E-A981-345A828F1714,0x2800,0x35000)/\EFI\ubuntu\shimx64.efi
error: no such device: 33671f2f-b332-4031-9ee3-1429517fd28b.

                             GNU GRUB  version 2.04

   Minimal BASH-like line editing is supported. For the first word, TAB
   lists possible command completions. Anywhere else TAB lists possible
   device or file completions.

grub> %`

Any idea why?

Thanks

**Comment by AkihiroSuda** [comment]
Could you retry downloading the image?
```
limactl rm -f default
limactl prune
limactl start
```

**Comment by stvgz** [comment]
> Could you retry downloading the image?
> 
> ```
> 
> limactl rm -f default
> 
> limactl prune
> 
> limactl start
> 
> ```

worked. Thanks！
