### ISSUE TITLE
sign lima binaries with cosign

### ISSUE THREAD

**Issue by developer-guy** [lima-vm/lima#530]
AFAIK, lima uses GitHub Actions to create releases, so, let's add cosign support to sign release binaries of lima.

> please feel free to assign it to me @AkihiroSuda

**Comment by afbjorklund** [comment]
Do you have an example of what these signatures look like, and how to use them ?
I guess it is related to https://www.sigstore.dev/, and an alternative to SHA256.asc ?

**Comment by afbjorklund** [comment]
Might need to document the existing PGP, as well...

https://github.com/lima-vm/lima/issues/488#issuecomment-997399202

**Comment by developer-guy** [comment]
ah sorry, yes, I refer to the project [cosign](https://github.com/sigstore/cosign). There is a sign-blob command in cosign which we use in the GoReleaser project to let people sign their blobs, for example, checksums.txt files, also, as you already might know that GitHub Actions support OIDC flow which is a perfect fit keyless approach of cosign.

**Comment by afbjorklund** [comment]
> as you already might know that GitHub Actions support OIDC flow

assume that I don't know anything :-) still live in curlpipesudosh world

**Comment by developer-guy** [comment]
For example, you can take a look at the signatures within the release page of cosign. 

👉 https://github.com/sigstore/cosign/releases/tag/v1.4.1

They are all generated by using the keyless approach.

**Comment by afbjorklund** [comment]
OK, so I browse through the wall of text and download a matching .sig file

**Comment by developer-guy** [comment]
yep, the whole signing/verifying chain will look the following:

1. We'll be using cosign with keyless approach which takes advantage of GitHub OIDC.
> cosign sign-blob <checksums.txt> or <binary>

2. We'll store the signature and certificate which we store in a transparency log server (Rekor) too.
3. We'll upload that signature and certificate to the releases of lima.
3. People now can be able to use that signature and certificate to verify lima binary or checksums.txt file has not been tampered with.

**Comment by afbjorklund** [comment]
It seems similar to the current workflow, so should be "straightforward"

```
wget https://github.com/AkihiroSuda.gpg
gpg --import AkihiroSuda.gpg 
gpg --verify SHA256SUMS.asc
sha256sum -c SHA256SUMS
```

Which of course is horribly complicated and "nobody" uses it, but anyway...

I was hoping for something like Zero Install, but maybe in the future ?

**Comment by developer-guy** [comment]
amazing! I didn't know about 0install until now 🤝

**Comment by afbjorklund** [comment]
There seemed to be mutual interests ? We're in the Dark Ages of packaging now

**Comment by developer-guy** [comment]
@AkihiroSuda do you have comments? Can we go ahead and implement it?

**Comment by AkihiroSuda** [comment]
My position is still same as https://github.com/containerd/nerdctl/issues/592#issuecomment-992413168
