### ISSUE TITLE
Cannot start default

### ISSUE THREAD

**Issue by fakiyer** [lima-vm/lima#554]
I'm encountering a problem after rebooting.
When I run `limactl start`, I get the following message:

```
❯ lima
FATA[0000] instance "default" does not exist, run `limactl start default` to create a new instance

❯ limactl start
FATA[0000] instance "default" does not exist, run `limactl start default` to create a new instance

❯ limactl start default
FATA[0000] instance "default" does not exist, run `limactl start default` to create a new instance

❯ limactl stop default
FATA[0000] instance "default" does not exist, run `limactl start default` to create a new instance
```

I tried deleting `~/.lima`, but it still doesn't work.
What else should I do?

Thanks for your help.

----

lima: 0.8.1
Mac（Intel）

**Comment by afbjorklund** [comment]
The syntax differs, between creating an instance (for the first time) and starting it (when it already exists)

1. `limactl start`
2. `limactl start default`

So the recommendation is wrong.

**Comment by afbjorklund** [comment]
I made some workarounds in the GUI, added a separate "create" and "start"

And used a temporary YAML file, for setting the name... Like `/tmp/foo.yaml`

**Comment by developer-guy** [comment]
Also, you should consider using the LIMA_INSTANCE environment variable to specify the instance name you want to work with. 🙋🏻‍♂️

**Comment by fakiyer** [comment]
@afbjorklund @developer-guy 
Thank you very much for your quick reply.

But I get the same message with every command.

```
❯ limactl start foo.yaml
FATA[0000] instance "default" does not exist, run `limactl start default` to create a new instance

❯ export LIMA_INSTANCE=test

❯ limactl start
FATA[0000] instance "test" does not exist, run `limactl start test` to create a new instance

❯ limactl start test
FATA[0000] instance "test" does not exist, run `limactl start test` to create a new instance

❯ limactl ls
FATA[0000] instance "test" does not exist, run `limactl start test` to create a new instance
```

**Comment by afbjorklund** [comment]
Yeah, I think it is something else actually. Try with `--debug` perhaps ?

**Comment by fakiyer** [comment]
same error..

```
❯ limactl --debug start default
FATA[0000] instance "default" does not exist, run `limactl start default` to create a new instance

```

Yes, I updated lima to 0.8.1 today.

**Comment by fakiyer** [comment]
I am so sorry. It's totally my mistake.

I added the following alias.

```
alias limactl="lima nerdctl"
```

I deleted the alias and it worked.

Thank you for your kind support.

**Comment by jandubois** [comment]
> ❯ export LIMA_INSTANCE=test
> 
> ❯ limactl start

Note the `LIMA_INSTANCE` only affects the `lima` command. It has no effect on `limactl`.
