### ISSUE TITLE
Slack or discord channel for community support

### ISSUE THREAD

**Issue by rfay** [lima-vm/lima#559]
This is such a great project and has a great community. It would be great to get easier community support going. [ddev](https://github.com/drud/ddev) has recently moved to Discord, which is working out well and doesn't require yet another slack instance. But slack is OK too. 

As mentioned elsewhere, some support is going on via DM in the "Rancher Users" slack. I imagine we could get them to create a lima channel.

So much discussion pertinent to lima shows up in the Rancher Desktop channel, but it would be good to get a more focused channel.

**Comment by jandubois** [comment]
> [ddev](https://github.com/drud/ddev) has recently moved to Discord, which is working out well and doesn't require yet another slack instance. But slack is OK too.

I was about to say that I feel the same way about "yet another Discord" instance too, and that it overlaps with our Github discussions, but then I realized that I once more mixed up Discord and Discourse... 😄 

I think I prefer Slack (my kids call it "Discord, but for old people").

I could ask about getting a #lima channel on the Rancher Users slack, which would be convenient for the overlap with the #rancher-desktop channel (about 600 members), so you cross-link messages. There are channels for #k3s and #longhorn CNCF projects too, but they still have strong ties to Rancher. So I don't know if we shouldn't create a vendor-neutral Slack instance instead?

@AkihiroSuda, what do you think?

**Comment by rfay** [comment]
I don't recommend creating a completely new slack, as slack makes it pretty painful to keep it free and when it's not free it's unsustainably expensive. Tried that with ddev.

**Comment by afbjorklund** [comment]
I normally lurk around in the #crio and #minikube Kubernetes channels on https://kubernetes.slack.com/

**Comment by AkihiroSuda** [comment]
> I could ask about getting a #lima channel on the Rancher Users slack, which would be convenient for the overlap with the #rancher-desktop channel (about 600 members), so you can cross-link messages. There are channels for #k3s and #longhorn CNCF projects too, but they still have strong ties to Rancher. So I don't know if we shouldn't create a vendor-neutral Slack instance instead?

It might be better if we could have a channel on CNCF slack (`cloud-native.slack.com`), but I'm not sure whether it is acceptable.
So having a channel on Rancher slack SGTM.

**Comment by jandubois** [comment]
> So having a channel on Rancher slack SGTM.

We do have a `#lima` channel on http://rancher-users.slack.com now.

**Comment by rfay** [comment]
Thanks!

**Comment by ddl-mmercer** [comment]
I'd like to point out that having a slack on rancher-users is at least 'somewhat' pointless.  They have it closed off so that just to sign up for access, you have to contact the workspace admin to get permission.  Otherwise, you have to have an address with either `@suse.com` or `@rancher.com`. What is the opposition to supporting a standard like Ibera, or Matrix or similar?

**Comment by AkihiroSuda** [comment]
> They have it closed off so that just to sign up for access, you have to contact the workspace admin to get permission. Otherwise, you have to have an address with either @suse.com or @rancher.com. 

Doesn't seem true: https://slack.rancher.io/

**Comment by AkihiroSuda** [comment]
FYI we have GitHub Discussions too: https://github.com/lima-vm/lima/discussions

**Comment by ddl-mmercer** [comment]
Sorry, I deleted the comment when I wen't through the slack link comment posted above and noticed the sign-ups.  Hadn't realized it was 1 url for login and a completely separate one for registration.
