### ISSUE TITLE
mysql_install_db fails on sshfs mount

### ISSUE THREAD

**Issue by jjeising** [lima-vm/lima#575]
When trying to run `mariadb:10.7` the first time it executes `mysql_install_db`. The script fails to create one or the other table on the sshfs mount (`global_priv`, `roles_mapping`, … you'll get another file on each try).

```
[Note] [Entrypoint]: Initializing database files
[Warning] You need to use --log-bin to make --expire-logs-days or --binlog-expire-logs-seconds work.
ERROR: 1005  Can't create table `mysql`.`func` (errno: 175 "File too short; Expected more data in file")
[ERROR] Aborting
```

When starting the container with the mount on another directory, waiting for the database, copying the files to the mount inside the container and restarting the container everything seems to work fine.

Setup:
```
services:
  db:
    image: mariadb:10.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    volumes:
      - ./data/mariadb:/var/lib/mysql:rw
```

Environment:
```
limactl version 0.8.1
colima version 0.3.2
MariaDB 10.6 / 10.7
macOS 12.1
```

**Comment by AkihiroSuda** [comment]
This is similar to https://github.com/lima-vm/lima/discussions/505 .

Please use `lima nerdctl volume create` to create a named volume inside the guest ext4 filesystem.
