### ISSUE TITLE
release lima and limactl separetely

### ISSUE THREAD

**Issue by developer-guy** [lima-vm/lima#591]
I'm working on a way to install lima in arkade, [see](https://github.com/alexellis/arkade/issues/617). I noticed that we bundle up all the binaries into a single .tar.gz file when we release the lima tool which we didn't support in arkade. I'm just wondering that do we have a chance to release lima and limactl binaries separately? 

Thanks in advance. ✌️

**Comment by jandubois** [comment]
I have no idea how `arkade` works, but `lima` is not just a single file. `lima` is just a convenience wrapper for `limactl shell default`; the important file is `limactl`. But you would also need the binary for the guest agent:

```console
$ find _output -type f | grep -v /doc/
_output/bin/lima
_output/bin/limactl
_output/bin/nerdctl.lima
_output/share/lima/lima-guestagent.Linux-aarch64
_output/share/lima/lima-guestagent.Linux-x86_64
```

**Comment by afbjorklund** [comment]
> I have no idea how arkade works

Most of the binaries seem to be hardcoded straight into the map:
https://github.com/alexellis/arkade/blob/master/pkg/get/tools.go

**Comment by jandubois** [comment]
I don't know, it is not much of a "package manager" if all it does is install single executables. However, I realize that it can be handy to use something on a jump box that quickly installs `kubectl` or `helm` or whatever.

So theoretically you could build a single-executable `limactl` binary by embedding the guest agents and the sample configs, and then not bother with `lima` and `nerdctl.lima`. I just don't see the need for this, and if `arkade` wants it packaged like that, then that project should be responsible for creating the packages. Just like any other packaging project.

**Comment by AkihiroSuda** [comment]
Sorry, I'm not planning to support single-binary distribution.
If arkade really needs single-binary, arkade should create a self-extractable archive by itself.

cc @alexellis

**Comment by alexellis** [comment]
No worries. It's just nice to support community tools like this as download options.
