### ISSUE TITLE
Provide a `cpu` setting to override default `host` setting

### ISSUE THREAD

**Issue by jandubois** [lima-vm/lima#592]
It seems that sometimes the `-cpu host` option configures a CPU that cannot be used to create a VM. See for example https://github.com/rancher-sandbox/rancher-desktop/issues/1291#issuecomment-1020527274.

Changing to e.g. `-cpu Haswell` could fix the issue, but right now the only mechanism we have to change the setting is via the clumsy `$QEMU_SYSTEM_X86_64` environment variable, that is really only meant for debugging.

I propose adding a `cpu` field to `lima.yaml` that defaults to `host`, but allows the user to switch to a different CPU.

**Comment by AkihiroSuda** [comment]
Having `cpu` (singular) in addition to `cpus` (plural) might be confusing.

Maybe `cpuType`?
