### ISSUE TITLE
Reconsider disabling sshfs caching by default

### ISSUE THREAD

**Issue by jandubois** [lima-vm/lima#600]
This was already proposed in PR #556.

So far we just made the setting configurable, but the default is still `cache=no`.

Given the problems reported in #556 and elsewhere, e.g. https://github.com/rancher-sandbox/rancher-desktop/issues/1349, I wonder if we shouldn't have reverted the default as well when we made the setting configurable.

**Comment by AkihiroSuda** [comment]
I don't understand why disabling cache breaks their application, but disabling cache is generally safer than enabling it, no?

Maybe Rancher Desktop should just have a GUI checkbox to toggle the caching configuration?
The default value of the Rancher Desktop GUI may differ from the default value of Lima.

**Comment by jandubois** [comment]
> I don't understand why disabling cache breaks their application, but disabling cache is generally safer than enabling it, no?

It is not "their application", it seems to be breaking PHP. I can consistently reproduce the issue that `composer` (the PHP package manager) cannot install to the mounted host filesystem when caching is disabled, and https://github.com/abiosoft/colima/issues/129 seems to hint that file access from PHP generally has problems with this option/lima 0.8.1.

I have tried to look into it, but haven't found anything yet. Intuitively I would also think that disabling caching should be safer, but at least in the case of PHP it doesn't seem to be true.

@rfay Do you have any new/additional insight into this problem?

> The default value of the Rancher Desktop GUI may differ from the default value of Lima.

Of course, but I'm just talking about lima here. This is a regression in lima 0.8.1 relative to 0.8.0, and I wonder now what the benefits of disabling caching are that makes it worth it breaking compatibility with PHP.

I still would like to understand what is going on first, but I suspect both colima and Rancher Desktop will re-enable caching by default again, to fix the regression, and it would make sense to me for lima to do the same.

**Comment by rfay** [comment]
The bottom line is we need to get rid of sshfs :) 

I had severe problems with caching enabled, then more severe (different kind) with it disabled. So could be something with lima 0.8.1 for sure. I was baffled by the result.

**Comment by jandubois** [comment]
> I had severe problems with caching enabled, then more severe (different kind) with it disabled. So could be something with lima 0.8.1 for sure. I was baffled by the result.

@rfay So which problems were worse? 😄 

I have one update: After deleting `/usr/bin/unzip` I can successfully run `composer install` in the sample project. It seems to be cloning all the packages via git though, so maybe `composer install --from-source` would have the same effect.

**Comment by rfay** [comment]
It was worse with caching turned off. But completely different problems. Both automated testing discoveries. So high pressure situations, unlike a normal person working away.

**Comment by jandubois** [comment]
For me both `composer install` and `composer create-project` worked fine with caching enabled, and reproducibly fail with `cache=no`. Given the feedback in https://github.com/abiosoft/colima/issues/129 it looks like PHP worked reasonably well up to lima 0.8.0, but has been broken since then.

I wonder if @rfay's failures with caching enabled have been observed by anybody else, or if it was just in the automated CI environment.
