### ISSUE TITLE
`limactl edit` should print a warning (error?) when override.yaml exists 

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/lima#612]
### Description

`limactl edit` (https://github.com/lima-vm/lima/pull/572) does not work as expected when override.yaml exists.
At least we should print a warning when override.yaml exists.

**Comment by jandubois** [comment]
> `limactl edit` (#572) does not work as expected when override.yaml exists.

I guess it depends on what you expect. 😄 It works the same way editing the template works when you create an instance.
`override.yaml` will always take precedence over whatever you specify in the instance setting; that is why it is called `override`.

> At least we should print a warning when override.yaml exists.

Yes, fully agreed. Maybe even include the override.yaml settings commented out in the front for reference?

```yaml
# Warning: your ~/.lima/_config.override.yaml file includes the following settings,
# which will take precedence over anything configured in this lima.yaml:
# 
# env:
#   CONTAINER_NAMESPACE: k8s.io
...
```

**Comment by afbjorklund** [comment]
Can't say I fully understand what override.yaml _does_, but I guess it is instead of start parameters or something ?
