### ISSUE TITLE
Add command to show the start message again

### ISSUE THREAD

**Issue by afbjorklund** [lima-vm/lima#614]
### Description

In case you missed it and it scrolled off, or if you are doing it from a GUI and want to show a dialog to the user.

Currently the information is shown with the rest of the clutter, which can make it hard to screen scrape (or read)

```
INFO[0000] Using the existing instance "docker"         
INFO[0000] [hostagent] Starting QEMU (hint: to watch the boot progress, see "/home/anders/.lima/docker/serial.log") 
INFO[0000] SSH Local Port: 43151                        
INFO[0000] [hostagent] Waiting for the essential requirement 1 of 5: "ssh" 
INFO[0021] [hostagent] The essential requirement 1 of 5 is satisfied 
INFO[0021] [hostagent] Waiting for the essential requirement 2 of 5: "user session is ready for ssh" 
INFO[0021] [hostagent] The essential requirement 2 of 5 is satisfied 
INFO[0021] [hostagent] Waiting for the essential requirement 3 of 5: "sshfs binary to be installed" 
INFO[0021] [hostagent] The essential requirement 3 of 5 is satisfied 
INFO[0022] [hostagent] Waiting for the essential requirement 4 of 5: "/etc/fuse.conf to contain \"user_allow_other\"" 
INFO[0022] [hostagent] The essential requirement 4 of 5 is satisfied 
INFO[0022] [hostagent] Waiting for the essential requirement 5 of 5: "the guest agent to be running" 
INFO[0022] [hostagent] The essential requirement 5 of 5 is satisfied 
INFO[0022] [hostagent] Mounting "/home/anders"          
INFO[0022] [hostagent] Mounting "/tmp/lima"             
INFO[0022] [hostagent] Waiting for the optional requirement 1 of 1: "user probe 1/1" 
INFO[0022] [hostagent] Forwarding "/run/user/1000/docker.sock" (guest) to "/home/anders/.lima/docker/sock/docker.sock" (host) 
INFO[0022] [hostagent] Forwarding "/run/lima-guestagent.sock" (guest) to "/home/anders/.lima/docker/ga.sock" (host) 
INFO[0022] [hostagent] Not forwarding TCP 127.0.0.53:53 
INFO[0022] [hostagent] The optional requirement 1 of 1 is satisfied 
INFO[0022] [hostagent] Not forwarding TCP 0.0.0.0:22    
INFO[0022] [hostagent] Not forwarding TCP [::]:22       
INFO[0022] [hostagent] Waiting for the final requirement 1 of 1: "boot scripts must have finished" 
INFO[0025] [hostagent] The final requirement 1 of 1 is satisfied 
INFO[0025] READY. Run `limactl shell docker` to open the shell. 
INFO[0025] Message from the instance "docker":          
To run `docker` on the host (assumes docker-cli is installed):
$ export DOCKER_HOST=unix:///home/anders/.lima/docker/sock/docker.sock
$ docker ...
```

Something like `limactl message` to show the message again, perhaps ? I could just filter out the INFO, otherwise.

**Comment by afbjorklund** [comment]
Currently the information is just shown in the GUI if it fails, not if it succeeds. Which is OK for "default", which doesn't have any.

But when running "docker" or "k8s", there is some interesting information about `DOCKER_HOST` or `KUBE_CONFIG`.

**Comment by afbjorklund** [comment]
Seems like [INFO] is on stderr, so maybe showing stdout as-is would be fine.

**Comment by jandubois** [comment]
Not sure why you closed this. I would be supportive of evaluating `Message` before storing it in the instance store, so this would show the expanded template instead of e.g. this:

```console
$ limactl ls -f '{{.Message}}' docker
To run `docker` on the host (assumes docker-cli is installed), run the following commands:
------
docker context create lima --docker "host=unix://{{.Dir}}/sock/docker.sock"
docker context use lima
docker run hello-world
------
```

And `limactl ls --json` would then provide it in an easy to consume way as well.

I'm less sure about, but not opposed to also adding a `limactl ls --message` option as an alternative output format, similar to `limactl ls -f '{{printf "%s\n%s\n\n" .Name .Message}}'`, but with the following changes:

* Instances without a message would show a placeholder, like `<no message>` instead of an empty line
* All messages would be indented

```console
$ limactl ls --message
alpine
  <no message>
docker
  To run `docker` on the host (assumes docker-cli is installed), run the following commands:
  ------
  docker context create lima --docker "host=unix://{{.Dir}}/sock/docker.sock"
  docker context use lima
  docker run hello-world
  ------
```

**Comment by jandubois** [comment]
> I would be supportive of evaluating `Message` before storing it in the instance store

I know you can already do it manually like this:

```console
$ limactl ls -f "$(limactl ls -f '{{.Message}}' docker)" docker
To run `docker` on the host (assumes docker-cli is installed), run the following commands:
------
docker context create lima --docker "host=unix:///Users/jan/.lima/docker/sock/docker.sock"
docker context use lima
docker run hello-world
------
```

But I don't think anybody really needs the raw template string, so pre-evaluating it seems like a sensible thing.

**Comment by afbjorklund** [comment]
> Not sure why you closed this

I noticed that I could just save the stdout, all the messages went to stderr so it worked out for the GUI in the end (without it).

We could re-open it, if wanting to add the feature for CLI users. If interested, it was added in https://github.com/afbjorklund/lima-gui/commit/2c1f88f4f0eef11409d1a74c86c43d6a4976bc52

![lima-gui-docker-message](https://user-images.githubusercontent.com/10364051/151718088-085b5ddd-72db-484f-ab9f-0122bb723469.png)

_I should probably rethinking showing the command, as long as using a tempfile..._

**Comment by jandubois** [comment]
> I should probably rethink showing the full command, as long as using a tempfile...

I'm amused that your temp dir function has picked a (German) profanity. I remember that we once used to turn random numbers into 4 character suffixes for VM names, and we had to add a stop list of banned words. Well, we didn't want to ship a list of profanity either, so we just eliminated vowels and a few other letters from the target alphabet. 😄

**Comment by jandubois** [comment]
This issue has become redundant with #1267.
