### ISSUE TITLE
File system change events (inotify) support for mounted directories

### ISSUE THREAD

**Issue by charleskorn** [lima-vm/lima#615]
### Description

From https://github.com/abiosoft/colima/issues/151:

We're using Colima to run Docker in a VM on our macOS laptops. Colima uses Lima under the hood to run this VM.

Are there any plans to support file system change events for mounted directories through inotify?

This is a key feature for us as we use containers in scenarios like auto-reloading dev servers and re-running unit tests on changes.

If there are no plans to support it at the moment, what kind of effort would be involved in adding this? Depending on the effort required, we might be open to putting together a PR to add support for this.

**Comment by jandubois** [comment]
> what kind of effort would be involved in adding this

As I already commented in the colima issue, I'm not sure this is a possibility at all (generating inotify events). Even if you capture them on the host (fsevents), I think you would need to implement a custom notification mechanism in the guest and can't expect to use inotify, which is a kernel mechanism.

**Comment by AkihiroSuda** [comment]
In far future we may support inotify with virtiofs (not virtio-9p-pci).
https://lwn.net/Articles/874000/

**Comment by afbjorklund** [comment]
There were some earlier series, about the limits of inotify.
https://lwn.net/Articles/605128/

> Inotify reports only events that a user-space program triggers through the filesystem API. This constitutes a fairly serious limitation of the API. For example, it means that inotify does not inform us of events on monitored objects via a remote filesystem (e.g. NFS) operation.

Previously we "solved" it by keeping the files on the VM.

**Comment by atipugin** [comment]
Looks like virtiofs is already supported (although marked as experimental), but I still can't get FS events working. Tools like `entr` (which relies on inotify and kqueue) don't work. Interesting that FS notifications work fine with Docker Desktop (with same settings - VZ + virtiofs).

**Comment by lobshunter** [comment]
Looks like Apple's virtio-fs document doesn't mention anything about inotify. Inotify in docker desktop container does work(although it would drop DELETE event, and inject additional WRITE event). docker.log shows messages like `level=info msg="injected MODIFY event (ts: 1677314215061760000) on /host_mnt/private/xxx`, seems like it's doing some kind of inotify event injection 🤔.

**Comment by abiosoft** [comment]
>  docker.log shows messages like level=info msg="injected MODIFY event (ts: 1677314215061760000) on /host_mnt/private/xxx

That shows that Docker is manually handling the notify events i.e. the feature is missing in virtiofs.

**Comment by lobshunter** [comment]
> i.e. the feature is missing in virtiofs.

Looks like so. I just tried qemu-virtiofsd on a Linux host, host to guest inotify doesn't work either(so it's not Apple's issue). There was [some work](https://lwn.net/Articles/874000/) trying to add inotify support for FUSE, but seems like it wasn't merged in mainline.

**Comment by lobshunter** [comment]
I bet docker desktop watches files in host, and forwards events into guest(perhaps by invoking something like chmod/write).
Start a docker destop container _with a volume_, then execute lskq(1) in host, it would show docker is watching files.

It might not be a great solution to do the same in lima.

**Comment by henrik242** [comment]
I'm trying to get node/next.js development working with colima, and next.js doesn't pick up changes I do on the host. _However_, if I `touch` the changed file from within the container, next.js picks up the change and my web page refreshes.

So, as a (silly) workaround, maybe one can use a script or daemon in the container to continuously scan the files and touch any changed files?

**Comment by lobshunter** [comment]
> However, if I touch the changed file from within the container, next.js picks up the change and my web page refreshes.

Yes, guest to guest inotify works as expected, but host to guest inotify doesn't(most likely because FUSE protocol doesn't support it).

> maybe one can use a script or daemon in the container to continuously scan the files and touch any changed files?

As a personal workaround, that would work(just less performant, performance degrades linearly with the number of files being added).

**Comment by henrik242** [comment]
> As a personal workaround, that would work(just less performant, performance degrades linearly with the number of files being added).

Yeah, it's not ideal at all.  This is the easiest I could come up with, in case others need it:

```
touch /tmp/checkpoint
while true; do
  find src -newer /tmp/checkpoint -exec touch {} \;
  touch /tmp/checkpoint
  sleep 1
done
```

**Comment by henrik242** [comment]
Some more testing reveals that running the script on the host is a lot more responsive:
```
FOLDER=$1
TOUCH="docker exec -ti my-docker-guest touch"
CHKPT=/tmp/checkpoint
touch $CHKPT
while true; do
  (find "$FOLDER" -newer $CHKPT -type f -print -a -exec $TOUCH {} \; | grep -q .) && touch $CHKPT
  sleep 1
done
```

**Comment by igarridot** [comment]
After some hours (more hours that I'd like to admit), I'd like to share my findings regarding this topic.

In our particular scenario, as we had issues with default filesystem values while running pytest, we stablished lima filesystem overrides based on following comment: https://github.com/abiosoft/colima/issues/83#issuecomment-1339269542

It solved our permissions issues, but stopped file syncing inside containers. To solve that, we just mounted only once our home directory, as having both mountpoints causes kind of a loop:

```
mountType: 9p
mounts:
  - location: "/Users/__USER__"
    writable: true
    9p:
      securityModel: "mapped-xattr"
      protocolVersion: "9p2000.L"
      cache: "fscache"
      msize: 256Kib
  - location: /tmp/colima
    writable: true
    9p:
      securityModel: "mapped-xattr"
      protocolVersion: "9p2000.L"
      cache: "fscache"
      msize: 256Kib
```

And just setting `mountInotify: true` in our colima instance.

Optional, you can tune Linux VM machine kernel to speed up a bit the filesystem:

```
provision:
  - mode: system
    script: |
      sysctl -w dirty_background_bytes=20MB
      sysctl -w dirty_background_ratio=10
      sysctl -w dirty_ratio=15
      sysctl -w fs.inotify.max_user_watches=524288
      sysctl -w fs.inotify.max_user_instances=512
```

**Comment by linnik** [comment]
> You don't need to use the HEAD version. The latest regular version already supports `--mount-inotify`

option is here, but it does not work

**Comment by AkihiroSuda** [comment]
Linking the latest proposal by @balajiv113 
- https://github.com/lima-vm/lima/discussions/1853

**Comment by aeifn** [comment]
> the latest regular version already supports `--mount-inotify`

Is it possible to use something like that with `lima` only?

**Comment by balajiv113** [comment]
@aeifn There is a draft PR #1913

**Comment by aeifn** [comment]
> @aeifn There is a draft PR #1913

Thank you! It works for me (`vz`, `virtiofs`).
