### ISSUE TITLE
lima 0.8.2 instance not support CPU SSSE3

### ISSUE THREAD

**Issue by Junnplus** [lima-vm/lima#641]
### Description

I am running clickhouse using docker in lime and I found that after upgrading to lima 0.8.2, CPU SSSE3 is no supported, is this expected?

ref: https://github.com/ClickHouse/ClickHouse/issues/20237

**Comment by Junnplus** [comment]
May be related to https://github.com/lima-vm/lima/pull/494/files#diff-25a805e06b16efefb1e5acb2009e512cca20865126e3a6afa52df59dcb4cf0fbR226

**Comment by AkihiroSuda** [comment]
> May be related to https://github.com/lima-vm/lima/pull/494/files#diff-25a805e06b16efefb1e5acb2009e512cca20865126e3a6afa52df59dcb4cf0fbR226

Why?

**Comment by Junnplus** [comment]
@AkihiroSuda Sorry, I mean it should be related to this PR.

**Comment by jandubois** [comment]
> PR #494 use `qemu64` CPU instead of `Haswell-v4`, `qemu64` CPU does not contain the instruction set of SSSE3 by default.

I'm not sure why that switch was made; I assumed that `qemu64` provided better performance. If so, then the question may be if having SSSE3 support will make up for not getting the other gains from switching to `qemu64`.

I guess it would be nice to know the actual benchmarks used for comparison, and what the numbers are.

Either way, implementing #592 to give the user an option seems like a good idea.

**Comment by Junnplus** [comment]
> Either way, implementing https://github.com/lima-vm/lima/issues/592 to give the user an option seems like a good idea.

SGTM.
