### ISSUE TITLE
Revisit the cpuType type definition

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/lima#647]
> I already merged this PR, but on second thought we could define this as `[]struct{Type string, Arch Arch}` so that a single YAML can be used on multiple archs?

_Originally posted by @AkihiroSuda in https://github.com/lima-vm/lima/pull/643#discussion_r805548077_

**Comment by jandubois** [comment]
I don't know. Initially I thought that it would rarely be useful, but I can see it for `defaults.yaml`, so you can override the cpu type defaults for the different architectures.

If we want to change it, we should do it before the next release, so there is no backwards compatibility issue!

**Comment by jandubois** [comment]
> we could define this as `[]struct{Type string, Arch Arch}` so that a single YAML can be used on multiple archs?

I'm going to work on this, but I think it should be a `map[Arch]string` instead of a slice. It makes no sense to specify multiple CPU types for the same arch. The defaults would be:

```yaml
cpuType:
  aarch64: cortex-a72
  x86_64: qemu64
```

Let me know if I misunderstand!

**Comment by AkihiroSuda** [comment]
I thought it is inconsistent with the `images` struct, but not a huge deal probably, so SGTM

**Comment by jandubois** [comment]
> I thought it is inconsistent with the `images` struct, but not a huge deal probably, so SGTM

For images it (used to) make sense because you could have a faster local location, and a slower download location for the same arch as a fallback. Now that we have built-in caching, this seems questionable, but probably not worth changing.
