### ISSUE TITLE
Memory allocation fails on darwin arm64 with latest qemu

### ISSUE THREAD

**Issue by afbjorklund** [lima-vm/lima#680]
### Description

Starting the default with 4GiB fails:
`qemu-system-aarch64: Addressing limited to 32 bits, but memory exceeds it by 1073741824 bytes`

Need to reduce memory, to e.g. 2GiB.

Since https://github.com/qemu/qemu/commit/3715c251cc781b263fbd7f7c535fde7a4da401c3

Most likely the `highmem=off` parameter to qemu should be parametrized, and not used with later versions.

The reasons that caused it to be needed (for ARM) earlier, seems to no longer be true with QEMU 7.0.

This was: `QEMU emulator version 6.2.50 (v6.1.0-3974-gf6620d0b34-dirty)`

**Comment by AkihiroSuda** [comment]
If this is a regression of QEMU, this should be perhaps fixed in the QEMU upstream?

**Comment by afbjorklund** [comment]
To be honest I am not sure, like where this extra "highmem" parameter comes from ?

**Comment by AkihiroSuda** [comment]
> To be honest I am not sure, like where this extra "highmem" parameter comes from ?

https://github.com/lima-vm/lima/pull/24

cc @Tarik02 Could you take a look? What should we do?

**Comment by afbjorklund** [comment]
It might have to be versioned, based on the QEMU version.

I was thinking to make it a user-changeable option, at least ?

**Comment by Tarik02** [comment]
> cc @Tarik02 Could you take a look? What should we do?

Sorry for offtop, will check this after we win war with russia.
