### ISSUE TITLE
docker context create 'unable to resolve docker endpoint'

### ISSUE THREAD

**Issue by christhomas** [lima-vm/lima#728]
### Description

lima version: 0.9.0
machine: m1 max macbook

I'm following the instructions in the output of the limactl output and when i try to configure the docker context as provided, it fails with the following output

``` 
docker context create lima --docker "host=unix:///Users/<the-username>/.lima/docker/sock/docker.sock"
unable to resolve docker endpoint: parse "tcp://NAME    STATUS    SSH    ARCH    CPUS    MEMORY    DISK    DIR": invalid character " " in host name
```

**Comment by afbjorklund** [comment]
There seems to be some bad $DOCKER_HOST set, before running that "docker" command.

**Comment by christhomas** [comment]
Ah, that does seem to be the case, for an unrelated issue I rebooted my computer just now (software installation), opened a terminal, checked that variable and it's not set, then tried it again and it worked.

**Comment by christhomas** [comment]
I'd say we can close this, sorry for the confusion
