### ISSUE TITLE
Failed to start any RHEL 8-based Linux on M1 Pro mac (stuck on the GRUB menu)

### ISSUE THREAD

**Issue by echupriyanov** [lima-vm/lima#841]
### Description

I'm trying to start any arm64 RHEL 8 based Linux using lima with provided examples.
But it even can't boot and stuck on the GRUB menu:
<img width="889" alt="Снимок экрана 2022-05-03 в 00 03 41" src="https://user-images.githubusercontent.com/2070616/166327481-2f9e21b9-5146-4918-a749-13fe4210ef4f.png">

x86-64 VMs are working fine
Ubuntu arm64 is working fine too.
The only issue is with RHEL8 based distros. What can be wrong here?

**Comment by sdadh01** [comment]
I have the same issue (M1 Pro Mac, latest versions of everything). Before the grub menu appears in the serial.log this appears until grub times out:

```
EFI stub: ERROR: This 64 KB granular kernel is not supported by your CPU

  Failed to boot both default and fallback entries.

Press any key to continue...
```
Subtly different error to [issue 712](https://github.com/lima-vm/lima/issues/712) but maybe the same cause?

**Comment by blissdev** [comment]
I'm experiencing this issue as well on an M1 Max MBP.

**Comment by AkihiroSuda** [comment]
According to https://forums.rockylinux.org/t/installation-of-rocky-not-proceeding-in-macbook-pro-m1-silicon-chip/4734 :

> It’s unfortunately not possible right now. The aarch64 kernel assumes a 64k page size that is NOT supported on M1 macs. M1 page size is 4k or 16k.
> 
> EL9 should work on M1.

**Comment by AkihiroSuda** [comment]
Update: Oracle Linux 8 seems to work on M1 (thanks to @plexilcrf)

- https://github.com/lima-vm/lima/discussions/3522
