### ISSUE TITLE
Consider using qemu-vmnet driver for networking

### ISSUE THREAD

**Issue by rglonek** [lima-vm/lima#848]
### Description

If you use a socket vmnet driver with qemu, everything runs so much faster. See this fork I created for more details: https://github.com/rglonek/qemu-vmnet

Uses cgo and is a single binary. Allows for fairly fast networking and using the MacOS native networking driver.

**Comment by jandubois** [comment]
Thanks you, that looks like an implementation of https://github.com/lima-vm/vde_vmnet/issues/25, but unfortunately with an incompatible license. But at least it should allow us to experiment with the approach to see what speeds can be achieved when getting rid of VDE.

**Comment by AkihiroSuda** [comment]
I’m rather planning to decouple vde_vmnet from vde

- https://github.com/lima-vm/vde_vmnet/issues/25

**Comment by AkihiroSuda** [comment]
Decoupled vde_vmnet from VDE: https://github.com/lima-vm/socket_vmnet
