### ISSUE TITLE
nerdctl run fails on Debian VM with "failed to extract layer sha256:[...]: failed to mount /var/lib/containerd/tmpmounts/[...]: operation not permitted: unknown" when zsh is the default shell

### ISSUE THREAD

**Issue by davebarkerxyz** [lima-vm/lima#862]
### Description

limactl version: 0.10.0
ctr github.com/containerd/containerd v1.6.2

I created a Debian VM with `limactl start --name=default template://debian`.

Starting a container with `nerdctl run -p localhost:5432:5432 postgres -e POSTGRES_PASSWORD=postgres -d` fails with the following error:

```
FATA[0015] failed to extract layer sha256:95d804481634f13fc7cc6ad18cfea900988c8290bcdd6d8948bc56256db5f68a: failed to mount /var/lib/contain
erd/tmpmounts/containerd-mount2254351966: operation not permitted: unknown
```

It's unclear if this is an upstream issue or a problem with how containerd is provisioned with the Debian template in Lima.

**Comment by davebarkerxyz** [comment]
I've removed the homebrew installed lima v0.10.0 and manually installed lima v0.11.0 from GitHub releases. I've created a new Debian VM (template://debian) and repeated the steps above. This now works as expected. nerdctl, containerd and kernel versions are identical between the VMs (`nerdctl version 0.20.0`, `containerd github.com/containerd/containerd v1.6.4 212e8b6fa2f44b9c21b2798135fc6fb7c53efc16` and `5.10.0-14-arm64` respectively).

I'm not sure what change resulted in a working configuration, but I'm closing this issue for now. If anyone else has the same issue with Debian under Lima, upgrading to lima >= v0.11.0 may help.

**Comment by davebarkerxyz** [comment]
After further investigation, I've discovered that the issue manifests consistently when the Debian guest user's default shell is set to zsh.

Steps to reproduce:

Creating a new Debian guest: `limactl start --name=test template://debian`
Within the guest, install zsh: `sudo apt install zsh`
Set zsh as the default shell for the guest user: `sudo chsh myuser -s /usr/bin/zsh`
From the host, restart the guest: `limactl stop test && limactl start guest`
Open a shell on the guest: `limactl shell test`
Within the guest, try to create a new Postgres container: `nerdctl run -e POSTGRES_PASSWORD=postgres -p 127.0.0.1:5432:5432 postgres`


Interestingly, if your default shell is Bash and you start a new zsh shell by typing `zsh`, the container run command above works fine. It only fails if zsh is set as the default shell.

**Comment by davebarkerxyz** [comment]
It appears that this is caused by CONTAINERD_SNAPSHOTTER=fuse-overlayfs not being set by default under zsh, and /usr/sbin not being in $PATH.

Running `CONTAINERD_SNAPSHOTTER=fuse-overlayfs PATH=$PATH:/usr/sbin nerdctl run -e POSTGRES_PASSWORD=postgres -p 127.0.0.1:5432:5432 postgres` within zsh (where zsh is the default shell) works as expected.

I see that we set these in the default user's .bashrc in https://github.com/lima-vm/lima/blob/master/pkg/cidata/cidata.TEMPLATE.d/boot/20-rootless-base.sh

I'm not sure that setting them for every possible shell is viable (and zsh doesn't load the global configs in /etc/profile.d), but perhaps we can document somewhere accessible that these must be set for lima to be able to start containers out of the box with an alternative shell?

**Comment by afbjorklund** [comment]
Or just add something for zsh ?
