### ISSUE TITLE
Template Faasd install issue (solution suggested)

### ISSUE THREAD

**Issue by nunix** [lima-vm/lima#880]
### Description

I've been trying to install a new LIMA instance with the `faasd` template and the installation fails or doesn't install faasd.

After testing with Ubuntu template and comparing to K3s template, I could confirm that the issue comes from the provision script being run as `system` instead of `user`:

Current provision script (doesn't work):
```
...
provision:
- mode: system
  script: |
    #!/bin/sh
    curl -sfL https://raw.githubusercontent.com/openfaas/faasd/master/hack/install.sh | bash -s -
...
```

Working provision script:
```
...
provision:
- mode: user
  script: |
    #!/bin/sh
    curl -sfL https://raw.githubusercontent.com/openfaas/faasd/master/hack/install.sh | bash -s -
...
```

Finally, and as an option, the header of the `faasd` template explains what to do after the instance is up. This could be added as a `message` at the end of the template file:

```
...
message: |
  Get the faas-cli:
  $ curl -sLS https://cli.openfaas.com | sh
 
  You can now log into your gateway:
  $ export OPENFAAS_URL=http://localhost:8080
  $ limactl shell faasd sudo cat /var/lib/faasd/secrets/basic-auth-password | faas-cli login -u admin --password-stdin
  $
  $ faas-cli store deploy NodeInfo
 
  Deployed. 200 OK.
  URL: http://localhost:8080/function/nodeinfo


Hope this helps and please let me know if you need any further information.

**Comment by jandubois** [comment]
Thanks for filing the issue! Since you have the fix already figured out, would you mind submitting a PR as well?
