### ISSUE TITLE
Shared files do not update immediately on docker

### ISSUE THREAD

**Issue by chent11** [lima-vm/lima#905]
### Description
The files changed in the host and shared between the host and a docker vm would not update immediately in the docker vm.

### Steps to reproduce:
1. Create a docker environment with command:
```
limactl start docker.yaml
docker context create lima --docker "host=unix:///{path}/docker.sock"
docker context use lima
```

2. Change a file's content and check the file information by command:
```
file=source/main.cpp; TZ=utc gls -l --time-style=full-iso $file && docker run --rm -it -v "$(PWD)":/$(PWD) -w "/$(PWD)" ubuntu:latest bash -c "ls -l --time-style=full-iso $file"
```
Result:
```
-rw-r--r-- 1 xxxxxx staff 951 2022-06-16 15:19:42.514692541 +0000 source/main.cpp
-rw-r--r-- 1 root nogroup 951 2022-06-16 15:19:33.000000000 +0000 source/main.cpp
```

They are the same file, so they should be read as the same information. But as you can see, The second file is not updated.

It would take around 10s to wait for the docker and host to be "synchronized." Admittedly, sometimes it would be synchronized immediately, but most of the time, it won't.

**Comment by AkihiroSuda** [comment]
Please try disabling sshfs cache
https://github.com/lima-vm/lima/blob/fe004c81d78b75005c3c886f3b731dcc445cd815/examples/default.yaml#L45-L60

**Comment by chent11** [comment]
@AkihiroSuda Thank you! It works!
