### ISSUE TITLE
Support for additional user-specified Qemu arguments

### ISSUE THREAD

**Issue by abiosoft** [lima-vm/lima#932]
### Description

It would be nice if Lima has in-built support for passing additional arguments to Qemu. 

```yaml
# List of additional args to pass to QEMU.
# 🟢 Builtin default: null
qemuArgs: null
```

A use case exists with Colima; which currently utilises gvproxy as an additional network option and basically needed to hack around Lima to pass the extra arguments to Qemu.

I am willing to implement this if given the go-ahead.

**Comment by jandubois** [comment]
The code implementing the environment lookup is [here](https://github.com/lima-vm/lima/blob/3af6768651121beaa20d1cb75ccdbf1a80c869e9/pkg/qemu/qemu.go#L580-L599).

**Comment by abiosoft** [comment]
Oh nice, had no idea support for the environment variable exists, that suffices for Colima's use case.

Should I close this or do we think there are other benefits to implementing this?

**Comment by jandubois** [comment]
> Should I close this issue or do we think there are other benefits to implementing this feature?

Not sure. I think we were discussing this before, and only wanted to support it for "debugging" (it will also log a debug warning if you use this).

But if this is being used/needed as a regular feature, then we should acknowledge that it is a supported extension mechanism. Having support for it in `lima.yaml` has some advantages (can be used by `default.yaml` and `override.yaml`), but I'm generally wary of putting more and more specialized configuration options into Lima, especially if we want to also support an alternative backend (Apple VM framework) as well, so I don't know...

**Comment by abiosoft** [comment]
Alright, closing until we see a stronger argument in favour.

Thanks for the feedback.

**Comment by sneak** [comment]
Stronger argument in favor: allowing USB passthrough

**Comment by thanosz** [comment]
+1

**Comment by sneak** [comment]
After a bit more research, it seems that commandline apps don't have the entitlements that are needed by macOS to disconnect the native macOS driver for a USB device (to pass it through to a VM).

**Comment by Spectrik** [comment]
+1
