### ISSUE TITLE
The MinGW and MSYS2 terminals are not supported on Windows

### ISSUE THREAD

**Issue by afbjorklund** [lima-vm/lima#936]
### Description

The TTY works on Posix and it works on Windows command prompt (DOS),
but it does not work when using a Unix terminal such as [mintty](https://mintty.github.io/) on Windows.

* MinGW (like in Git for Windows)

* MSYS2

The detection uses `IsCygwinTerminal` rather than the usual `IsTerminal`,
and the `survey` module is hardcoded to use either/or (based on the GOOS)

* https://github.com/mattn/go-isatty

* https://github.com/AlecAivazis/survey

----

This breaks the template selection ("Incorrect function")

But it also breaks terminal handling when running shell

Other side effects was JSON logging to the terminal too

And different output when it comes to the downloader

**Comment by afbjorklund** [comment]
The code in logrus also failed to detect these terminals, overrriding with ForceColors

````
vendor/github.com/sirupsen/logrus/text_formatter.go:	isColored := f.ForceColors || (f.isTerminal && (runtime.GOOS != "windows"))
```

**Comment by afbjorklund** [comment]
The workaround for the template selection, is either to use `template://` or `winpty.exe`:

```
winpty limactl start
```

**Comment by Cactusinhand** [comment]
> The workaround for the template selection, is either to use template:// or winpty.exe:

@afbjorklund 
Sorry, what does `template://` mean here?
