### ISSUE TITLE
Evaluate OpenSSF's allstar

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/lima#945]
We may want to evaluate https://github.com/ossf/allstar to ensure that we are following the good security practices.

Allstar will open issues like this (after [24 hours](https://github.com/ossf/allstar/issues/89#issuecomment-1005122193))
- https://github.com/GoogleContainerTools/distroless/issues/861
- https://github.com/GoogleContainerTools/distroless/issues/771
(config: https://github.com/GoogleContainerTools/.allstar)

**Comment by AkihiroSuda** [comment]
cc @jandubois : I'm going to install this

![image](https://user-images.githubusercontent.com/9248427/178210655-273fe906-d891-4791-bdac-0cca36590131.png)

**Comment by jandubois** [comment]
Good idea! I just saw that one of the CNCF graduation requirements is

* Have achieved and maintained a Core Infrastructure Initiative [Best Practices Badge](https://bestpractices.coreinfrastructure.org/).

Can't start too early to work on that! 😄

**Comment by AkihiroSuda** [comment]
Installed the app and more than 24 hours passed, but nothing seemed to happen 😞

**Comment by AkihiroSuda** [comment]
> copy

We can just create single-line SECURITY.md with "See https://github.com/lima-vm/lima/blob/master/SECURITY.md" so that we do not need to sync the document across all the repos
